function buildTireModels()
%BUILDTireModelTIREMODELS Build and integrate the TireModel tire model variants.
%   This idempotent builder creates TireMF62, TireTTCMap and TireModel,
%   then replaces the VehiclePlant TireSimple reference with TireModel.

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "data"));
addpath(fullfile(projectRoot, "models", "components"));
addpath(fullfile(projectRoot, "models", "plant"));
addpath(fullfile(projectRoot, "scripts", "tire"));

dictionaryPath = fullfile(projectRoot, "data", "VehicleData.sldd");
assert(isfile(dictionaryPath), "FSAE:TireModel:DictionaryMissing", ...
    "VehicleData.sldd is missing.");
assertDictionaryEntries(dictionaryPath);

componentFolder = fullfile(projectRoot, "models", "components");
buildVectorModel("TireMF62", ...
    "MF62", ...
    componentFolder);
buildVectorModel("TireTTCMap", ...
    "TTCMap", ...
    componentFolder);
buildVariantModel(componentFolder);
integrateVehiclePlant(projectRoot);
fprintf("TireModel tire models built and integrated.\n");
end

function buildVectorModel(modelName, implementation, componentFolder)
closeIfLoaded(modelName);
new_system(modelName);
setModelConfiguration(modelName);

    inputNames = [ ...
    "SlipRatio", "SlipAngle", "CamberAngle", "NormalLoad", ...
    "RoadGripScale", "RoadMuLimit"];
outputNames = [ ...
    "TireForceXWheel", "TireForceYWheel", ...
    "MuUtilization", "SaturationScale"];
for index = 1:numel(inputNames)
    add_block("simulink/Sources/In1", ...
        modelName + "/" + inputNames(index), ...
        "Port", string(index), ...
        "PortDimensions", "4", ...
        "Position", [30, 50 + 70 * (index - 1), 60, ...
        70 + 70 * (index - 1)]);
end
add_block("simulink/Signal Routing/Mux", modelName + "/InputMux", ...
    "Inputs", "6", "Position", [130, 80, 135, 350]);
addCodegenEquation(modelName, implementation);
add_block("simulink/Signal Routing/Demux", modelName + "/OutputDemux", ...
    "Outputs", "[4 4 4 4]", "Position", [520, 100, 525, 300]);
for index = 1:numel(outputNames)
    add_block("simulink/Sinks/Out1", ...
        modelName + "/" + outputNames(index), ...
        "Port", string(index), ...
        "Position", [620, 90 + 70 * (index - 1), 650, ...
        110 + 70 * (index - 1)]);
end
for index = 1:numel(inputNames)
    add_line(modelName, inputNames(index) + "/1", ...
        "InputMux/" + string(index), "autorouting", "on");
end
add_line(modelName, "InputMux/1", "TireEquation/1", ...
    "autorouting", "on");
add_line(modelName, "TireEquation/1", "OutputDemux/1", ...
    "autorouting", "on");
for index = 1:numel(outputNames)
    add_line(modelName, "OutputDemux/" + string(index), ...
        outputNames(index) + "/1", "autorouting", "on");
end
save_system(modelName, fullfile(componentFolder, modelName + ".slx"));
close_system(modelName);
end

function addCodegenEquation(modelName, implementation)
functionBlock = matlabFunctionBlock();
add_block(functionBlock, modelName + "/TireEquation", ...
    "Position", [290, 160, 450, 250]);
if implementation == "MF62"
    script = join([ ...
        "function output = tireEquation(input)", ...
        "%#codegen", ...
        "output = evaluateTireMF62Codegen(input, TireMFParameters);", ...
        "end"], newline);
    setMatlabFunctionScript(modelName + "/TireEquation", script);
    addMatlabFunctionParameter(modelName + "/TireEquation", ...
        "TireMFParameters");
elseif implementation == "TTCMap"
    script = join([ ...
        "function output = tireEquation(input)", ...
        "%#codegen", ...
        "output = evaluateTTCMapCodegen(input, TireMapPoints, " + ...
            "TireMapForces, TireMapScale, TireMapLowerBound, " + ...
            "TireMapUpperBound, TireInputPressurePa);", ...
        "end"], newline);
    setMatlabFunctionScript(modelName + "/TireEquation", script);
    parameterNames = [ ...
        "TireMapPoints", "TireMapForces", "TireMapScale", ...
        "TireMapLowerBound", "TireMapUpperBound", ...
        "TireInputPressurePa"];
    for parameterName = parameterNames
        addMatlabFunctionParameter(modelName + "/TireEquation", ...
            parameterName);
    end
else
    error("FSAE:TireModel:Implementation", ...
        "Unknown tire implementation '%s'.", implementation);
end
end

function buildVariantModel(componentFolder)
modelName = "TireModel";
closeIfLoaded(modelName);
new_system(modelName);
setModelConfiguration(modelName);

inputNames = [ ...
    "SlipRatio", "SlipAngle", "CamberAngle", "NormalLoad", ...
    "RoadGripScale", "RoadMuLimit"];
outputNames = [ ...
    "TireForceXWheel", "TireForceYWheel", ...
    "MuUtilization", "SaturationScale"];
for index = 1:numel(inputNames)
    add_block("simulink/Sources/In1", ...
        modelName + "/" + inputNames(index), ...
        "Port", string(index), ...
        "PortDimensions", "4", ...
        "Position", [30, 60 + 65 * (index - 1), 60, ...
        80 + 65 * (index - 1)]);
end
add_block(variantSubsystemBlock(), modelName + "/TireVariant", ...
    "Position", [180, 75, 360, 335]);
configureVariantSubsystem(modelName + "/TireVariant");
for index = 1:numel(outputNames)
    add_block("simulink/Sinks/Out1", ...
        modelName + "/" + outputNames(index), ...
        "Port", string(index), ...
        "Position", [500, 85 + 70 * (index - 1), 530, ...
        105 + 70 * (index - 1)]);
end
for index = 1:numel(inputNames)
    add_line(modelName, inputNames(index) + "/1", ...
        "TireVariant/" + string(index), "autorouting", "on");
end
for index = 1:numel(outputNames)
    add_line(modelName, "TireVariant/" + string(index), ...
        outputNames(index) + "/1", "autorouting", "on");
end
save_system(modelName, fullfile(componentFolder, modelName + ".slx"));
close_system(modelName);
end

function configureVariantSubsystem(variantPath)
allBlocks = find_system(variantPath, SearchDepth = 1, ...
    MatchFilter = @Simulink.match.allVariants, Type = "Block");
for index = 1:numel(allBlocks)
    block = string(allBlocks{index});
    if block == variantPath
        continue
    end
    blockType = string(get_param(block, "BlockType"));
    if blockType == "Inport" || blockType == "Outport"
        delete_block(block);
    end
end

choices = find_system(variantPath, SearchDepth = 1, ...
    MatchFilter = @Simulink.match.allVariants, BlockType = "SubSystem");
choices = setdiff(string(choices), variantPath, "stable");
assert(numel(choices) == 2, "FSAE:TireModel:VariantTemplate", ...
    "Expected two default Variant Subsystem choices.");
set_param(choices(1), "Name", "TireSimpleChoice");
set_param(choices(2), "Name", "TireMF62Choice");
add_block(variantPath + "/TireSimpleChoice", ...
    variantPath + "/TireTTCMapChoice");

choiceNames = ["TireSimpleChoice", "TireMF62Choice", "TireTTCMapChoice"];
modelNames = ["TireSimple", "TireMF62", "TireTTCMap"];
conditions = [ ...
    "TireSelection.ModelMode == 0", ...
    "TireSelection.ModelMode == 1", ...
    "TireSelection.ModelMode == 2"];
for index = 1:numel(choiceNames)
    choicePath = variantPath + "/" + choiceNames(index);
    set_param(choicePath, "VariantControl", conditions(index));
    populateVariantChoice(choicePath, modelNames(index));
end

inputNames = [ ...
    "SlipRatio", "SlipAngle", "CamberAngle", "NormalLoad", ...
    "RoadGripScale", "RoadMuLimit"];
outputNames = [ ...
    "TireForceXWheel", "TireForceYWheel", ...
    "MuUtilization", "SaturationScale"];
for index = 1:numel(inputNames)
    add_block("simulink/Sources/In1", variantPath + "/" + ...
        inputNames(index), "Port", string(index), ...
        "PortDimensions", "4", ...
        "Position", [30, 50 + 60 * (index - 1), 60, ...
        70 + 60 * (index - 1)]);
end
for index = 1:numel(outputNames)
    add_block("simulink/Sinks/Out1", variantPath + "/" + ...
        outputNames(index), "Port", string(index), ...
        "Position", [500, 70 + 70 * (index - 1), 530, ...
        90 + 70 * (index - 1)]);
end
end

function populateVariantChoice(choicePath, referencedModel)
blocks = find_system(choicePath, SearchDepth = 1, ...
    MatchFilter = @Simulink.match.allVariants, Type = "Block");
for index = 1:numel(blocks)
    block = string(blocks{index});
    if block ~= choicePath
        delete_block(block);
    end
end
inputNames = [ ...
    "SlipRatio", "SlipAngle", "CamberAngle", "NormalLoad", ...
    "RoadGripScale", "RoadMuLimit"];
outputNames = [ ...
    "TireForceXWheel", "TireForceYWheel", ...
    "MuUtilization", "SaturationScale"];
for index = 1:numel(inputNames)
    add_block("simulink/Sources/In1", ...
        choicePath + "/" + inputNames(index), ...
        "Port", string(index), ...
        "PortDimensions", "4", ...
        "Position", [25, 40 + 55 * (index - 1), 55, ...
        60 + 55 * (index - 1)]);
end
add_block(modelReferenceBlock(), choicePath + "/Model", ...
    "ModelName", referencedModel, ...
    "Position", [160, 75, 330, 280]);
for index = 1:numel(outputNames)
    add_block("simulink/Sinks/Out1", ...
        choicePath + "/" + outputNames(index), ...
        "Port", string(index), ...
        "Position", [435, 65 + 65 * (index - 1), 465, ...
        85 + 65 * (index - 1)]);
end
for index = 1:numel(inputNames)
    add_line(choicePath, inputNames(index) + "/1", ...
        "Model/" + string(index), "autorouting", "on");
end
for index = 1:numel(outputNames)
    add_line(choicePath, "Model/" + string(index), ...
        outputNames(index) + "/1", "autorouting", "on");
end
end

function integrateVehiclePlant(projectRoot)
model = "VehiclePlant";
open_system(model);
oldPath = model + "/TireSimple";
newPath = model + "/TireModel";
if getSimulinkBlockHandle(oldPath) ~= -1
    set_param(oldPath, "ModelName", "TireModel");
    set_param(oldPath, "Name", "TireModel");
elseif getSimulinkBlockHandle(newPath) ~= -1
    set_param(newPath, "ModelName", "TireModel");
else
    error("FSAE:TireModel:PlantTireBlock", ...
        "VehiclePlant has no TireSimple or TireModel reference.");
end
ports = get_param(newPath, "PortHandles");
signalNames = [ ...
    "TireFx", "TireFy", "MuUtilization", "SaturationScale"];
for index = 1:numel(signalNames)
    line = get_param(ports.Outport(index), "Line");
    assert(line ~= -1, "FSAE:TireModel:PlantTireLine", ...
        "VehiclePlant TireModel output %d is unconnected.", index);
    set_param(line, "Name", signalNames(index));
end
save_system(model, fullfile(projectRoot, "models", "plant", ...
    "VehiclePlant.slx"));
close_system(model);
end

function setModelConfiguration(model)
set_param(model, ...
    "DataDictionary", "VehicleData.sldd", ...
    "SolverType", "Variable-step", ...
    "Solver", "ode45", ...
    "StartTime", "0.0", ...
    "StopTime", "1", ...
    "SaveOutput", "on", ...
    "SignalLogging", "on", ...
    "ModelReferenceNumInstancesAllowed", "Multi");
end

function path = matlabFunctionBlock()
load_system("simulink");
matches = find_system("simulink", LookUnderMasks = "all", ...
    FollowLinks = "on", Name = "MATLAB Function");
assert(~isempty(matches), "FSAE:TireModel:MATLABFunctionBlock", ...
    "Could not resolve MATLAB Function block.");
path = matches{1};
end

function setMatlabFunctionScript(blockPath, script)
stateflowRoot = sfroot;
chart = find(stateflowRoot, "-isa", "Stateflow.EMChart", ...
    "Path", char(blockPath));
assert(isscalar(chart), "FSAE:TireModel:MATLABFunctionChart", ...
    "Could not uniquely resolve MATLAB Function chart '%s'.", blockPath);
chart.Script = char(script);
end

function addMatlabFunctionParameter(blockPath, parameterName)
stateflowRoot = sfroot;
chart = find(stateflowRoot, "-isa", "Stateflow.EMChart", ...
    "Path", char(blockPath));
assert(isscalar(chart), "FSAE:TireModel:MATLABFunctionChart", ...
    "Could not uniquely resolve MATLAB Function chart '%s'.", blockPath);
parameter = Stateflow.Data(chart);
parameter.Name = char(parameterName);
parameter.Scope = "Parameter";
parameter.Props.Array.Size = "-1";
end

function path = variantSubsystemBlock()
load_system("simulink");
matches = find_system("simulink", LookUnderMasks = "all", ...
    FollowLinks = "on", Name = "Variant Subsystem");
assert(~isempty(matches), "FSAE:TireModel:VariantBlock", ...
    "Could not resolve Variant Subsystem library block.");
path = matches{1};
end

function path = modelReferenceBlock()
load_system("simulink");
matches = find_system("simulink", LookUnderMasks = "all", ...
    FollowLinks = "on", BlockType = "ModelReference", ...
    Name = "Model");
assert(~isempty(matches), "FSAE:TireModel:ModelReferenceBlock", ...
    "Could not resolve Model Reference library block.");
path = matches{1};
end

function assertDictionaryEntries(dictionaryPath)
dictionary = Simulink.data.dictionary.open(dictionaryPath);
cleanup = onCleanup(@() close(dictionary));
designData = getSection(dictionary, "Design Data");
requiredEntries = [ ...
    "TireSelectedProfile", "TireSelection", ...
    "TireMFParameters", "TireMapPoints", "TireMapForces", ...
    "TireMapScale", "TireMapLowerBound", ...
    "TireMapUpperBound", "TireInputPressurePa"];
for entryName = requiredEntries
    getEntry(designData, entryName);
end
end

function closeIfLoaded(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end
