function configureAdaptiveAutocrossDriverChart()
%CONFIGUREADAPTIVEAUTOCROSSDRIVERCHART Install the autonomous core script.
%   MATLAB Function blocks are Stateflow.EMChart objects.  This helper is
%   intentionally limited to the chart script, chart parameter data, and
%   model-workspace defaults; graphical structure is maintained separately.

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
modelPath = fullfile(projectRoot, "models", "driver", ...
    "AdaptiveAutocrossDriver.slx");
sourcePath = fullfile(projectRoot, "scripts", "path_tracking", ...
    "fsaeAdaptiveAutocrossDriverCore.m");
stepPath = fullfile(projectRoot, "scripts", "path_tracking", ...
    "fsaeAdaptiveAutocrossDriverStep.m");
assert(isfile(modelPath), "FSAE:AAD:MissingModel", ...
    "AdaptiveAutocrossDriver.slx is missing.");
assert(isfile(sourcePath), "FSAE:AAD:MissingCore", ...
    "The adaptive autocross driver core is missing.");
assert(isfile(stepPath), "FSAE:AAD:MissingStep", ...
    "The adaptive autocross driver step function is missing.");
addpath(fileparts(stepPath), "-begin");

open_system(modelPath);
chartPath = "AdaptiveAutocrossDriver/AdaptiveDriverCore";
chart = sfroot().find("-isa", "Stateflow.EMChart", "Path", chartPath);
assert(isscalar(chart), "FSAE:AAD:MissingChart", ...
    "Could not resolve MATLAB Function chart %s.", chartPath);

script = fileread(sourcePath);
chart.Script = strrep(script, ...
    "fsaeAdaptiveAutocrossDriverCore", "fcn");
chart.ChartUpdate = "DISCRETE";

resetData = chart.find("-isa", "Stateflow.Data", "Name", "reset");
assert(isscalar(resetData), "FSAE:AAD:MissingResetData", ...
    "Could not resolve the adaptive driver reset chart data.");
resetData.Scope = "Input";

chart.SampleTime = "AADControlSampleTime";

parameterDefaults = struct( ...
    "AADControlSampleTime", 0.01, ...
    "AADWheelbase", 1.54, ...
    "AADCGToFrontAxle", 0.847, ...
    "AADCGToRearAxle", 0.693, ...
    "AADFrontHalfEnvelope", 0.69525, ...
    "AADRearHalfEnvelope", 0.67525, ...
    "AADProjectionSearchWindow", 30.0, ...
    "AADMinimumSteeringPreview", 1.00, ...
    "AADSteeringPreviewTime", 0.18, ...
    "AADMaximumSteeringPreview", 4.0, ...
    "AADHeadingGain", 1.8, ...
    "AADCrossTrackGain", 4.0, ...
    "AADBoundaryGain", 2.0, ...
    "AADMinimumSteeringSpeed", 1.0, ...
    "AADMaximumSteeringAngle", 0.50, ...
    "AADMaximumSteeringRate", 6.0, ...
    "AADSteeringWheelRatio", 1.0, ...
    "AADLateralAccelerationLimit", 13.5, ...
    "AADMaximumAcceleration", 16.0, ...
    "AADMaximumDeceleration", 8.0, ...
    "AADPlanningDeceleration", 6.0, ...
    "AADMaximumSpeed", 32.0, ...
    "AADSpeedPreviewDistance", 190.0, ...
    "AADSpeedPreviewStep", 0.75, ...
    "AADCurvatureFilterHalfWindow", 2.0, ...
    "AADCurvatureSafetyFactor", 1.0, ...
    "AADSpeedSafetyFactor", 1.0, ...
    "AADSpeedKp", 4.0, ...
    "AADSpeedKi", 0.20, ...
    "AADSpeedFeedforwardGain", 0.60, ...
    "AADExitSpeedFeedforwardGain", 0.60, ...
    "AADPreviewBrakingEnabled", true, ...
    "AADPreviewBrakingActivationDistance", 45.0, ...
    "AADPreviewBrakeFeedforwardGain", 0.65, ...
    "AADPreviewBrakingDecelerationScale", 0.90, ...
    "AADAntiWindupGain", 1.0, ...
    "AADReferencePathCurvatureBlendStart", 0.15, ...
    "AADReferencePathCurvatureBlendEnd", 0.30, ...
    "AADReferencePathMaximumBlend", 0.0, ...
    "AADBoundaryPreviewDistance", 6.0, ...
    "AADBoundaryReserve", 0.50, ...
    "AADEmergencyBoundaryMargin", 0.25, ...
    "AADEnableTV", true, ...
    "AADEnableTC", true, ...
    "AADBrakePressurePerAcceleration", 1.0e4);

oldParameters = chart.find("-isa", "Stateflow.Data", ...
    "Scope", "Parameter");
for index = 1:numel(oldParameters)
    if startsWith(string(oldParameters(index).Name), "PathTracking")
        delete(oldParameters(index));
    end
end

parameterNames = string(fieldnames(parameterDefaults));
for parameterName = parameterNames.'
    data = chart.find("-isa", "Stateflow.Data", ...
        "Name", parameterName);
    if isempty(data)
        data = Stateflow.Data(chart);
        data.Name = char(parameterName);
    end
    data.Scope = "Parameter";
end

modelWorkspace = get_param("AdaptiveAutocrossDriver", "ModelWorkspace");
for parameterName = parameterNames.'
    assignin(modelWorkspace, parameterName, ...
        parameterDefaults.(parameterName));
end

set_param("AdaptiveAutocrossDriver", ...
    "StopTime", "10", "Solver", "ode4", "FixedStep", "0.01");
save_system("AdaptiveAutocrossDriver", modelPath);
end
