function battery = installBatteryMapData(options)
%INSTALLBATTERYMAPDATA Import the E41 accumulator data into VehicleData.sldd.
%   Electrical layout and cell ratings are read from data/BatteryMaps/ESF.xlsx.
%   The 4 mOhm cell resistance ceiling and 15 A continuous charge limit come
%   from the INR21700-RS50 manufacturer specification. The three-point OCV
%   curve is an explicit placeholder because neither source contains an
%   OCV-versus-SOC map.

arguments
    options.DictionaryPath (1, 1) string = defaultDictionaryPath()
    options.WorkbookPath (1, 1) string = defaultWorkbookPath()
    options.DatasheetPath (1, 1) string = defaultDatasheetPath()
end

mustBeFile(options.WorkbookPath);
mustBeFile(options.DatasheetPath);

cellData = readcell(options.WorkbookPath, ...
    Sheet = "规格书 Datasheet", Range = "C3:D11");
packData = readcell(options.WorkbookPath, ...
    Sheet = "电池箱 Accumulator", Range = "E3:F6");
segmentData = readmatrix(options.WorkbookPath, ...
    Sheet = "电池箱 Accumulator", Range = "B12:C17");
connectorData = readcell(options.WorkbookPath, ...
    Sheet = "电池箱 Accumulator", Range = "U10");
mainFuseData = readcell(options.WorkbookPath, ...
    Sheet = "电池箱 Accumulator", Range = "U20");
connectorLimit = numericValue(connectorData{1}, "connector ampacity");
mainFuseRating = numericValue(mainFuseData{1}, "main fuse rating");

cellModel = string(cellData{2, 1});
cellCapacityAh = numericValue(cellData{3, 1}, "cell capacity");
cellMaximumVoltage = numericValue(cellData{4, 1}, ...
    "cell maximum voltage");
cellNominalVoltage = numericValue(cellData{5, 1}, ...
    "cell nominal voltage");
cellMinimumVoltage = numericValue(cellData{6, 1}, ...
    "cell minimum voltage");
cellMaxDischargeCurrent = numericValue(cellData{8, 1}, ...
    "cell continuous discharge current");
maxCellTemperature = numericValue(cellData{9, 1}, ...
    "maximum cell temperature");

packMaximumVoltage = numericValue(packData{2, 1}, ...
    "pack maximum voltage");
packNominalVoltage = numericValue(packData{3, 1}, ...
    "pack nominal voltage");
totalCells = numericValue(packData{4, 1}, "total cell count");

validateattributes(segmentData, {'numeric'}, ...
    {'size', [6, 2], 'positive', 'integer', 'finite'}, ...
    mfilename, "segmentData");
parallelCellsBySegment = segmentData(:, 1).';
seriesCellsBySegment = segmentData(:, 2).';
if numel(unique(parallelCellsBySegment)) ~= 1
    error("FSAE:BatteryMap:UnequalParallelCount", ...
        "The current model requires the same parallel count in every segment.");
end

parallelCells = parallelCellsBySegment(1);
seriesCells = sum(seriesCellsBySegment);
derivedTotalCells = sum(parallelCellsBySegment .* seriesCellsBySegment);
assertClose(derivedTotalCells, totalCells, 0, "total cell count");
assertClose(seriesCells * cellMaximumVoltage, packMaximumVoltage, ...
    1e-9, "maximum pack voltage");
assertClose(seriesCells * cellNominalVoltage, packNominalVoltage, ...
    1e-9, "nominal pack voltage");

cellMaxChargeCurrent = 15.0;
cellResistanceUpperBound = 4.0e-3;
packCapacityAh = parallelCells * cellCapacityAh;
packResistance = seriesCells * cellResistanceUpperBound / parallelCells;
packDischargeCurrentLimit = min( ...
    parallelCells * cellMaxDischargeCurrent, connectorLimit);
packChargeCurrentLimit = parallelCells * cellMaxChargeCurrent;
minimumVoltage = seriesCells * cellMinimumVoltage;
nominalEnergy = packNominalVoltage * packCapacityAh * 3600;
maximumEnergy = packMaximumVoltage * packCapacityAh * 3600;

dictionary = Simulink.data.dictionary.open(options.DictionaryPath);
cleanup = onCleanup(@() close(dictionary));
designData = getSection(dictionary, "Design Data");
batteryEntry = getEntry(designData, "Battery");
battery = getValue(batteryEntry);

updated = "2026-08-03";
workbookSource = "ESF.xlsx / Accumulator and Datasheet sheets";
cellSource = "_INR21700-RS50_2025.1.2_1_.pdf";
derivedSource = "DerivedFromBatteryMaps";

battery.CellModel = fixedRecord(cellModel, "1", workbookSource, ...
    "High", updated, "INR21700-RS50 cell model declared by the ESF.");
battery.SeriesCells = fixedRecord(seriesCells, "1", derivedSource, ...
    "High", updated, "Sum of the six ESF segment series-cell counts.");
battery.ParallelCells = fixedRecord(parallelCells, "1", workbookSource, ...
    "High", updated, "All six ESF segments use three parallel cells.");
battery.TotalCells = fixedRecord(totalCells, "1", workbookSource, ...
    "High", updated, "ESF total; cross-checked against the segment table.");
battery.SeriesCellsBySegment = fixedRecord(seriesCellsBySegment, "1", ...
    workbookSource, "High", updated, ...
    "Segment order 1--6: [23 24 23 24 23 24] series cells.");
battery.CellCapacityAh = fixedRecord(cellCapacityAh, "A*hr", ...
    workbookSource, "High", updated, "Nominal cell capacity from the ESF.");
battery.PackCapacityAh = fixedRecord(packCapacityAh, "A*hr", ...
    derivedSource, "High", updated, ...
    "Three parallel 5 Ah cells give 15 Ah pack capacity.");
battery.CellMinimumVoltage = fixedRecord(cellMinimumVoltage, "V", ...
    workbookSource, "High", updated, "Cell discharge cut-off voltage.");
battery.CellNominalVoltage = fixedRecord(cellNominalVoltage, "V", ...
    workbookSource, "High", updated, "Nominal cell voltage.");
battery.CellMaximumVoltage = fixedRecord(cellMaximumVoltage, "V", ...
    workbookSource, "High", updated, "Cell end-of-charge voltage.");
battery.MinimumVoltage = fixedRecord(minimumVoltage, "V", ...
    derivedSource, "High", updated, ...
    "Series cell count multiplied by the 2.5 V cell cut-off.");
battery.NominalEnergy = fixedRecord(nominalEnergy, "J", ...
    derivedSource, "High", updated, ...
    "Nominal voltage multiplied by 15 Ah; distinct from ESF maximum-voltage energy.");

battery.CellMaxDischargeCurrent = boundedRecord( ...
    cellMaxDischargeCurrent, NaN, cellMaxDischargeCurrent, "A", ...
    cellSource, "High", updated, ...
    "Manufacturer maximum continuous discharge current at 80 degC cut-off.", false);
battery.CellMaxChargeCurrent = boundedRecord( ...
    cellMaxChargeCurrent, NaN, cellMaxChargeCurrent, "A", ...
    cellSource, "High", updated, ...
    "Manufacturer maximum continuous charge current.", false);
battery.PackDischargeCurrentLimit = boundedRecord( ...
    packDischargeCurrentLimit, NaN, connectorLimit, "A", ...
    derivedSource, "Medium", updated, ...
    "Minimum of the 3p cell limit and the ESF connector ampacity; fuse time-current behavior is not modeled.", false);
battery.PackChargeCurrentLimit = boundedRecord( ...
    packChargeCurrentLimit, NaN, packChargeCurrentLimit, "A", ...
    derivedSource, "High", updated, ...
    "Three parallel cells multiplied by the 15 A cell charge limit.", false);
battery.MainFuseRatedCurrent = fixedRecord(mainFuseRating, "A", ...
    workbookSource, "High", updated, ...
    "FWP 700 V main-fuse nominal rating; not used as an instantaneous current clamp.");
battery.MaxCellTemperature = boundedRecord(maxCellTemperature, NaN, ...
    maxCellTemperature, "degC", workbookSource, "High", updated, ...
    "Cell surface temperature limit; thermal dynamics are not yet modeled.", false);

battery.CellResistance = boundedRecord(cellResistanceUpperBound, 0, ...
    cellResistanceUpperBound, "Ohm", cellSource, "Medium", updated, ...
    "Conservative use of the datasheet 1 kHz ACIR ceiling as an ohmic model parameter; replace with DC pulse identification.", false);
battery.PackResistance = boundedRecord(packResistance, 0, ...
    packResistance, "Ohm", derivedSource, "Medium", updated, ...
    "141s3p scaling of the 4 mOhm per-cell ACIR ceiling.", false);
battery.OCVSOCBreakpoints = boundedRecord([0, 0.5, 1], 0, 1, "1", ...
    "DesignPlaceholder", "Low", updated, ...
    "Three-point OCV approximation because BatteryMaps contains no OCV-SOC curve.", true);
battery.CellOCVValues = boundedRecord( ...
    [cellMinimumVoltage, cellNominalVoltage, cellMaximumVoltage], ...
    cellMinimumVoltage, cellMaximumVoltage, "V", ...
    "DesignPlaceholder", "Low", updated, ...
    "Maps 0/50/100% SOC to min/nominal/max cell voltage; replace with test data.", true);

assertClose(battery.Capacity.Value, maximumEnergy, 1e-6, ...
    "existing Battery.Capacity energy");
setValue(batteryEntry, battery);
saveChanges(dictionary);
end

function output = fixedRecord(value, unit, source, confidence, updated, notes)
output = boundedRecord(value, NaN, NaN, unit, source, confidence, ...
    updated, notes, false);
end

function output = boundedRecord(value, lowerBound, upperBound, unit, ...
        source, confidence, updated, notes, isPlaceholder)
output = struct( ...
    "Value", value, ...
    "LowerBound", lowerBound, ...
    "UpperBound", upperBound, ...
    "Unit", char(unit), ...
    "Source", char(source), ...
    "Confidence", char(confidence), ...
    "LastUpdated", char(updated), ...
    "IsMeasured", false, ...
    "IsPlaceholder", logical(isPlaceholder), ...
    "Notes", char(notes));
end

function value = numericValue(input, label)
if isnumeric(input) && isscalar(input)
    value = double(input);
else
    value = str2double(string(input));
end
validateattributes(value, {'double'}, {'scalar', 'real', 'finite'}, ...
    mfilename, label);
end

function assertClose(actual, expected, tolerance, label)
if abs(double(actual) - double(expected)) > tolerance
    error("FSAE:BatteryMap:CrossCheckFailed", ...
        "%s cross-check failed: actual %.12g, expected %.12g.", ...
        label, actual, expected);
end
end

function path = defaultDictionaryPath()
path = fullfile(projectRoot(), "data", "VehicleData.sldd");
end

function path = defaultWorkbookPath()
path = fullfile(projectRoot(), "data", "BatteryMaps", "ESF.xlsx");
end

function path = defaultDatasheetPath()
path = fullfile(projectRoot(), "data", "BatteryMaps", ...
    "_INR21700-RS50_2025.1.2_1_.pdf");
end

function root = projectRoot()
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
end
