function vehicle = installE41VehicleParameters(options)
%INSTALLE41VEHICLEPARAMETERS Install the E41 suspension/steering data.
%   Values come from "E41悬架转向参数表 .docx". Fixed values are converted
%   to SI units. The steering ratio is stored as the midpoint scalar used by
%   the current model, with the document's 2.5--4.5 range retained as bounds.

arguments
    options.DictionaryPath (1, 1) string = defaultDictionaryPath()
end

dictionary = Simulink.data.dictionary.open(options.DictionaryPath);
cleanup = onCleanup(@() close(dictionary));
designData = getSection(dictionary, "Design Data");
vehicleEntry = getEntry(designData, "Vehicle");
vehicle = getValue(vehicleEntry);

source = "E41SuspensionSteeringParameterTable";
derivedSource = "DerivedFromE41ParameterTable";
updated = "2026-08-02";

vehicle.Mass = fixedRecord(320.0, "kg", source, "High", updated, ...
    "Vehicle mass including driver; supplied by the E41 parameter table.");
vehicle.Wheelbase = fixedRecord(1.540, "m", source, "High", updated, ...
    "Converted from 1540 mm.");
vehicle.TrackFront = fixedRecord(1.200, "m", source, "High", updated, ...
    "Converted from 1200 mm.");
vehicle.TrackRear = fixedRecord(1.160, "m", source, "High", updated, ...
    "Converted from 1160 mm.");
vehicle.CGHeight = fixedRecord(0.300, "m", source, "Medium", updated, ...
    "Target CG height from the E41 parameter table; not a measurement.");
vehicle.StaticLoadDistributionFront = fixedRecord(0.45, "1", source, ...
    "High", updated, "Target static front axle load fraction.");
vehicle.StaticLoadDistributionRear = fixedRecord(0.55, "1", source, ...
    "High", updated, "Target static rear axle load fraction.");
vehicle.CGToFrontAxle = fixedRecord(1.540 * 0.55, "m", ...
    derivedSource, "High", updated, ...
    "Derived from wheelbase and the 45:55 front:rear static load ratio.");

vehicle.RollCenterHeightFront = fixedRecord(0.040, "m", source, ...
    "High", updated, "Converted from 40 mm.");
vehicle.RollCenterHeightRear = fixedRecord(0.060, "m", source, ...
    "High", updated, "Converted from 60 mm.");
vehicle.VirtualSwingArmLengthFront = fixedRecord(1.500, "m", source, ...
    "High", updated, "Converted from 1500 mm.");
vehicle.VirtualSwingArmLengthRear = fixedRecord(1.800, "m", source, ...
    "High", updated, "Converted from 1800 mm.");
vehicle.KingpinInclinationFront = fixedRecord(5.0, "deg", source, ...
    "High", updated, "Front kingpin inclination.");
vehicle.KingpinInclinationRear = fixedRecord(2.0, "deg", source, ...
    "High", updated, "Rear kingpin inclination.");
vehicle.CasterAngleFront = fixedRecord(7.0, "deg", source, "High", ...
    updated, "Front caster angle.");
vehicle.CasterAngleRear = fixedRecord(0.0, "deg", source, "High", ...
    updated, "Rear caster angle.");
vehicle.ScrubRadiusFront = fixedRecord(0.035, "m", source, "High", ...
    updated, "Converted from the table's 35 mm front scrub radius.");
vehicle.ScrubRadiusRear = fixedRecord(0.045, "m", source, "High", ...
    updated, "Converted from the table's 45 mm rear scrub radius.");
vehicle.MechanicalTrailFront = fixedRecord(0.040, "m", source, ...
    "High", updated, "Converted from 40 mm.");
vehicle.MechanicalTrailRear = fixedRecord(0.0, "m", source, "High", ...
    updated, "Rear mechanical trail is zero in the source table.");
vehicle.RideFrequencyFront = fixedRecord(3.6, "Hz", source, "Medium", ...
    updated, "The source table omits the unit; interpreted as ride frequency in Hz.");
vehicle.RideFrequencyRear = fixedRecord(3.2, "Hz", source, "Medium", ...
    updated, "The source table omits the unit; interpreted as ride frequency in Hz.");

vehicle.SuspensionLeverageRatioFront = fixedRecord(0.923, "1", ...
    source, "High", updated, ...
    "Wheel travel divided by spring travel, per the source table label.");
vehicle.SuspensionLeverageRatioRear = fixedRecord(0.882, "1", ...
    source, "High", updated, ...
    "Wheel travel divided by spring travel, using the same convention as front.");
vehicle.SpringRateFront = fixedRecord(32.69e3, "N/m", source, ...
    "High", updated, "Front spring stiffness converted from 32.69 N/mm.");
vehicle.SpringRateRear = fixedRecord(23.59e3, "N/m", source, ...
    "High", updated, "Rear spring stiffness converted from 23.59 N/mm.");
vehicle.WheelRateFront = fixedRecord(76.74e3, "N/m", source, ...
    "High", updated, ...
    "Direct front suspension line stiffness; this value reproduces the tabulated spring roll stiffness.");
vehicle.WheelRateRear = fixedRecord(60.64e3, "N/m", source, ...
    "High", updated, ...
    "Direct rear suspension line stiffness; this value reproduces the tabulated spring roll stiffness.");
vehicle.SuspensionLinearStiffnessFront = fixedRecord(76.74e3, ...
    "N/m", source, "High", updated, ...
    "Front per-wheel suspension line stiffness converted from 76.74 N/mm.");
vehicle.SuspensionLinearStiffnessRear = fixedRecord(60.64e3, ...
    "N/m", source, "High", updated, ...
    "Rear per-wheel suspension line stiffness converted from 60.64 N/mm.");

vehicle.SpringRollStiffnessFront = fixedRecord(964.34, "N*m/deg", ...
    source, "High", updated, "Front suspension spring roll stiffness.");
vehicle.SpringRollStiffnessRear = fixedRecord(712.07, "N*m/deg", ...
    source, "High", updated, "Rear suspension spring roll stiffness.");
vehicle.SpringRollGradientFront = fixedRecord(0.45, "deg/g", source, ...
    "High", updated, "Front spring-only roll gradient from the source table.");
vehicle.SpringRollGradientRear = fixedRecord(0.62, "deg/g", source, ...
    "High", updated, "Rear spring-only roll gradient from the source table.");
vehicle.AntiRollBarBladeStiffness = fixedRecord(4415.01, "N*m/deg", ...
    source, "High", updated, "Anti-roll-bar blade/ear stiffness.");
vehicle.AntiRollBarStiffnessFront = fixedRecord(1.955, "N*m/deg", ...
    source, "High", updated, "Front anti-roll-bar stiffness.");
vehicle.AntiRollBarStiffnessRear = fixedRecord(1.423, "N*m/deg", ...
    source, "High", updated, "Rear anti-roll-bar stiffness.");
vehicle.RollStiffnessFront = fixedRecord(979.98, "N*m/deg", source, ...
    "High", updated, "Front total roll stiffness.");
vehicle.RollStiffnessRear = fixedRecord(723.45, "N*m/deg", source, ...
    "High", updated, "Rear total roll stiffness.");
vehicle.RollGradientFront = fixedRecord(0.45, "deg/g", source, ...
    "High", updated, "Front total roll gradient from the source table.");
vehicle.RollGradientRear = fixedRecord(0.61, "deg/g", source, ...
    "High", updated, "Rear total roll gradient from the source table.");
vehicle.RollStiffnessDistributionFront = fixedRecord( ...
    979.98 / (979.98 + 723.45), "1", derivedSource, "High", updated, ...
    "Derived from the front and rear total roll stiffness values.");

vehicle.SteeringRatio = boundedRecord(3.5, 2.5, 4.5, "1", source, ...
    "Medium", updated, ...
    "Current scalar model value is the midpoint of the table's variable 2.5--4.5 angular ratio.");
vehicle.AckermannRate = boundedRecord(NaN, NaN, NaN, "1", source, ...
    "Unknown", updated, ...
    "The Ackermann-rate value cell is blank in the source table.", true);

setValue(vehicleEntry, vehicle);
synchronizeTorqueVectoringAlias(designData, "TorqueVectoringVehicleMass", vehicle.Mass.Value);
synchronizeTorqueVectoringAlias(designData, "TorqueVectoringWheelbase", vehicle.Wheelbase.Value);
synchronizeTorqueVectoringAlias(designData, "TorqueVectoringTrackFront", vehicle.TrackFront.Value);
synchronizeTorqueVectoringAlias(designData, "TorqueVectoringTrackRear", vehicle.TrackRear.Value);
saveChanges(dictionary);
end

function output = fixedRecord(value, unit, source, confidence, updated, notes)
output = boundedRecord(value, NaN, NaN, unit, source, confidence, ...
    updated, notes, false);
end

function output = boundedRecord(value, lowerBound, upperBound, unit, ...
        source, confidence, updated, notes, isPlaceholder)
if nargin < 9
    isPlaceholder = false;
end
output = struct( ...
    "Value", value, ...
    "LowerBound", lowerBound, ...
    "UpperBound", upperBound, ...
    "Unit", char(unit), ...
    "Source", char(source), ...
    "Confidence", char(confidence), ...
    "LastUpdated", char(updated), ...
    "IsMeasured", false, ...
    "IsPlaceholder", logical(isPlaceholder), ...
    "Notes", char(notes));
end

function synchronizeTorqueVectoringAlias(designData, name, value)
try
    entry = getEntry(designData, name);
catch exception
    if contains(exception.identifier, "EntryNotFound") || ...
            contains(exception.message, "does not exist", IgnoreCase = true)
        return
    end
    rethrow(exception)
end
parameter = getValue(entry);
if isa(parameter, "Simulink.Parameter")
    parameter.Value = value;
    setValue(entry, parameter);
else
    setValue(entry, value);
end
end

function path = defaultDictionaryPath()
projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
path = fullfile(projectRoot, "data", "VehicleData.sldd");
end
