function catalog = listVehicleParameters(projectRoot, options)
%LISTVEHICLEPARAMETERS Read editable scalar vehicle parameters from the dictionary.
%   The catalog covers the physical vehicle and simulation groups stored in
%   VehicleData.sldd. Numeric vectors, maps, buses, and other compound data
%   remain outside this scalar editor.

arguments
    projectRoot (1, 1) string = defaultProjectRoot()
    options.DictionaryPath (1, 1) string = ""
end

dictionaryPath = options.DictionaryPath;
if strlength(dictionaryPath) == 0
    dictionaryPath = fullfile(projectRoot, "data", "VehicleData.sldd");
end
assert(isfile(dictionaryPath), "FSAE:VehicleParameters:MissingDictionary", ...
    "VehicleData.sldd was not found: %s", dictionaryPath);

dictionary = Simulink.data.dictionary.open(dictionaryPath);
cleanup = onCleanup(@() close(dictionary));
designData = getSection(dictionary, "Design Data");

groupNames = ["Vehicle", "Tire", "Aero", "Powertrain", ...
    "Battery", "Brake", "Simulation"];
groupLabels = ["整车", "轮胎", "空气动力", "动力总成", ...
    "电池", "制动", "仿真"];

groups = strings(0, 1);
labels = strings(0, 1);
names = strings(0, 1);
paths = strings(0, 1);
values = zeros(0, 1);
units = strings(0, 1);
lowerBounds = zeros(0, 1);
upperBounds = zeros(0, 1);
sources = strings(0, 1);
confidences = strings(0, 1);
placeholders = false(0, 1);
notes = strings(0, 1);

for groupIndex = 1:numel(groupNames)
    groupName = groupNames(groupIndex);
    groupValue = getValue(getEntry(designData, char(groupName)));
    if ~isstruct(groupValue) || ~isscalar(groupValue)
        continue
    end
    fieldNames = string(fieldnames(groupValue));
    for fieldIndex = 1:numel(fieldNames)
        fieldName = fieldNames(fieldIndex);
        record = groupValue.(char(fieldName));
        if ~isstruct(record) || ~isscalar(record) || ...
                ~isfield(record, "Value")
            continue
        end
        value = record.Value;
        if ~(isnumeric(value) && isreal(value) && isscalar(value))
            continue
        end

        groups(end + 1, 1) = groupName; %#ok<AGROW>
        labels(end + 1, 1) = groupLabels(groupIndex); %#ok<AGROW>
        names(end + 1, 1) = chineseParameterName( ...
            groupName, fieldName); %#ok<AGROW>
        paths(end + 1, 1) = groupName + "." + fieldName; %#ok<AGROW>
        values(end + 1, 1) = double(value); %#ok<AGROW>
        units(end + 1, 1) = stringMetadata(record, "Unit", "1"); %#ok<AGROW>
        lowerBounds(end + 1, 1) = numericMetadata( ...
            record, "LowerBound", NaN); %#ok<AGROW>
        upperBounds(end + 1, 1) = numericMetadata( ...
            record, "UpperBound", NaN); %#ok<AGROW>
        sources(end + 1, 1) = stringMetadata( ...
            record, "Source", ""); %#ok<AGROW>
        confidences(end + 1, 1) = stringMetadata( ...
            record, "Confidence", ""); %#ok<AGROW>
        placeholders(end + 1, 1) = logicalMetadata( ...
            record, "IsPlaceholder", false); %#ok<AGROW>
        notes(end + 1, 1) = stringMetadata(record, "Notes", ""); %#ok<AGROW>
    end
end

catalog = table(groups, labels, names, paths, values, units, ...
    lowerBounds, upperBounds, sources, confidences, placeholders, notes, ...
    'VariableNames', {'Group', 'GroupLabel', 'Name', 'Path', 'Value', ...
    'Unit', 'LowerBound', 'UpperBound', 'Source', 'Confidence', ...
    'IsPlaceholder', 'Notes'});
assert(~isempty(catalog), "FSAE:VehicleParameters:EmptyCatalog", ...
    "No editable scalar records were found in %s.", dictionaryPath);
end

function name = chineseParameterName(groupName, fieldName)
switch groupName
    case "Vehicle"
        fields = [ ...
            "Mass", "Wheelbase", "TrackFront", "TrackRear", ...
            "CGHeight", "CGToFrontAxle", "InertiaYaw", ...
            "InertiaPitch", "InertiaRoll", "SteeringRatio", ...
            "WheelRateFront", "WheelRateRear", ...
            "RollStiffnessDistributionFront", ...
            "StaticLoadDistributionFront", ...
            "StaticLoadDistributionRear", "SpringRateFront", ...
            "SpringRateRear", "SuspensionLeverageRatioFront", ...
            "SuspensionLeverageRatioRear", "RollStiffnessFront", ...
            "RollStiffnessRear", "RollCenterHeightFront", ...
            "RollCenterHeightRear", "VirtualSwingArmLengthFront", ...
            "VirtualSwingArmLengthRear", "KingpinInclinationFront", ...
            "KingpinInclinationRear", "CasterAngleFront", ...
            "CasterAngleRear", "ScrubRadiusFront", "ScrubRadiusRear", ...
            "MechanicalTrailFront", "MechanicalTrailRear", ...
            "RideFrequencyFront", "RideFrequencyRear", ...
            "SuspensionLinearStiffnessFront", ...
            "SuspensionLinearStiffnessRear", ...
            "SpringRollStiffnessFront", "SpringRollStiffnessRear", ...
            "SpringRollGradientFront", "SpringRollGradientRear", ...
            "AntiRollBarBladeStiffness", ...
            "AntiRollBarStiffnessFront", "AntiRollBarStiffnessRear", ...
            "RollGradientFront", "RollGradientRear", "AckermannRate"];
        chineseNames = [ ...
            "整车质量", "轴距", "前轮距", "后轮距", ...
            "质心高度", "质心至前轴距离", "横摆转动惯量", ...
            "俯仰转动惯量", "侧倾转动惯量", "转向传动比", ...
            "前轮轮上刚度", "后轮轮上刚度", ...
            "前轴侧倾刚度分配", "前轴静态载荷分配", ...
            "后轴静态载荷分配", "前弹簧刚度", "后弹簧刚度", ...
            "前悬架杠杆比", "后悬架杠杆比", ...
            "前轴总侧倾刚度", "后轴总侧倾刚度", ...
            "前轴侧倾中心高度", "后轴侧倾中心高度", ...
            "前轴虚拟摆臂长度", "后轴虚拟摆臂长度", ...
            "前主销内倾角", "后主销内倾角", ...
            "前主销后倾角", "后主销后倾角", ...
            "前轮主销偏距", "后轮主销偏距", ...
            "前轮机械拖距", "后轮机械拖距", ...
            "前轴偏频", "后轴偏频", ...
            "前悬架线刚度", "后悬架线刚度", ...
            "前轴弹簧侧倾刚度", "后轴弹簧侧倾刚度", ...
            "前轴弹簧侧倾梯度", "后轴弹簧侧倾梯度", ...
            "防倾杆刀片刚度", "前防倾杆侧倾刚度", ...
            "后防倾杆侧倾刚度", "前轴总侧倾梯度", ...
            "后轴总侧倾梯度", "阿克曼率"];
    case "Tire"
        fields = [ ...
            "UnloadedRadius", "EffectiveRadius", "WheelInertia", ...
            "RelaxationLengthLongitudinal", "RelaxationLengthLateral", ...
            "LowSpeedEpsilon", "LongitudinalStiffness", ...
            "LateralStiffness", "CamberStiffness", "ForceEpsilon", ...
            "LinearStiffnessReferenceLoad", ...
            "LinearStiffnessReferencePressure"];
        chineseNames = [ ...
            "轮胎自由半径", "轮胎有效滚动半径", "车轮转动惯量", ...
            "纵向松弛长度", "横向松弛长度", "低速正则化阈值", ...
            "轮胎纵向刚度", "轮胎侧偏刚度", "轮胎外倾刚度", ...
            "轮胎力正则化阈值", "线性刚度参考载荷", ...
            "线性刚度参考胎压"];
    case "Aero"
        fields = [ ...
            "CdA", "ClAFront", "ClARear", "YawCorrection", ...
            "SpeedEpsilon", "DownforceBalanceFront", ...
            "DownforceBalanceRear"];
        chineseNames = [ ...
            "空气阻力面积", "前轴下压力面积", "后轴下压力面积", ...
            "偏航阻力修正系数", "气动速度正则化阈值", ...
            "前轴下压力分配", "后轴下压力分配"];
    case "Powertrain"
        fields = [ ...
            "GearRatio", "GearEfficiency", "MotorTorqueLimit", ...
            "MotorSpeedLimit", "MotorResponseTime", ...
            "InverterEfficiency"];
        chineseNames = [ ...
            "传动比", "传动效率", "电机扭矩上限", ...
            "电机转速上限", "电机响应时间", "逆变器效率"];
    case "Battery"
        fields = [ ...
            "NominalVoltage", "Capacity", "PowerLimitDrive", ...
            "PowerLimitRegen", "InitialSOC", "SOCLowerLimit", ...
            "SOCUpperLimit", "PowerEpsilon", "MaximumVoltage", ...
            "SeriesCells", "ParallelCells", "TotalCells", ...
            "CellCapacityAh", "PackCapacityAh", ...
            "CellMinimumVoltage", "CellNominalVoltage", ...
            "CellMaximumVoltage", "MinimumVoltage", "NominalEnergy", ...
            "CellMaxDischargeCurrent", "CellMaxChargeCurrent", ...
            "PackDischargeCurrentLimit", "PackChargeCurrentLimit", ...
            "MainFuseRatedCurrent", "MaxCellTemperature", ...
            "CellResistance", "PackResistance"];
        chineseNames = [ ...
            "电池包额定电压", "电池包能量容量", "驱动功率上限", ...
            "再生功率上限", "初始荷电状态", "荷电状态下限", ...
            "荷电状态上限", "电池功率正则化阈值", ...
            "电池包最高电压", "串联电芯数", "并联电芯数", ...
            "电芯总数", "单体容量", "电池包容量", ...
            "单体最低电压", "单体额定电压", "单体最高电压", ...
            "电池包最低电压", "电池包额定能量", ...
            "单体最大放电电流", "单体最大充电电流", ...
            "电池包放电电流上限", "电池包充电电流上限", ...
            "主熔断器额定电流", "单体最高温度", ...
            "单体内阻", "电池包内阻"];
    case "Brake"
        fields = [ ...
            "MaxPressure", "TorquePerPressureFront", ...
            "TorquePerPressureRear", "PressureRatioRearToFront", ...
            "MaxPressureRear", "ReferencePressureFront", ...
            "ReferencePressureRear", "ReferenceForceFront", ...
            "ReferenceForceRear", "ForcePerPressureFront", ...
            "ForcePerPressureRear", "ForceDistributionFront", ...
            "ForceDistributionRear", ...
            "SynchronousAdhesionCoefficient"];
        chineseNames = [ ...
            "前制动回路最大压力", "前轮制动力矩压力增益", ...
            "后轮制动力矩压力增益", "后前制动压力比", ...
            "后制动回路最大压力", "前制动参考压力", ...
            "后制动参考压力", "前轮参考制动力", ...
            "后轮参考制动力", "前轮制动力压力增益", ...
            "后轮制动力压力增益", "前轴制动力分配", ...
            "后轴制动力分配", "同步附着系数"];
    case "Simulation"
        fields = [ ...
            "TsMotor", "TsSensor", "TsController", "TsDriver", ...
            "TsEnergyManagement", "StopTimeSmoke", "Gravity"];
        chineseNames = [ ...
            "电机采样时间", "传感器采样时间", "控制器采样时间", ...
            "驾驶员采样时间", "能量管理采样时间", ...
            "冒烟仿真停止时间", "重力加速度"];
    otherwise
        fields = strings(0, 1);
        chineseNames = strings(0, 1);
end

index = find(fields == fieldName, 1);
if isempty(index)
    name = "待翻译参数：" + fieldName;
else
    name = chineseNames(index);
end
end

function value = numericMetadata(record, fieldName, defaultValue)
value = defaultValue;
if isfield(record, fieldName)
    candidate = record.(fieldName);
    if isnumeric(candidate) && isreal(candidate) && isscalar(candidate)
        value = double(candidate);
    end
end
end

function value = stringMetadata(record, fieldName, defaultValue)
value = string(defaultValue);
if isfield(record, fieldName)
    candidate = string(record.(fieldName));
    if isscalar(candidate) && ~ismissing(candidate)
        value = candidate;
    end
end
end

function value = logicalMetadata(record, fieldName, defaultValue)
value = logical(defaultValue);
if isfield(record, fieldName)
    candidate = record.(fieldName);
    if (islogical(candidate) || isnumeric(candidate)) && isscalar(candidate)
        value = logical(candidate);
    end
end
end

function root = defaultProjectRoot()
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
end
