function project = setupProject()
%SETUPPROJECT Create or update the FSAE MATLAB Project configuration.

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
requiredFolders = [ ...
    "data", ...
    "models/top", "models/plant", "models/controller", "models/driver", ...
    "models/components", "models/libraries", ...
    "scripts/initialization", "scripts/path_tracking", "scripts/track", "scripts/tire", "scripts/ggv", ...
    "scripts/lap_time", "scripts/simulation", "scripts/reporting", ...
    "scripts/torque_vectoring", "scripts/vehicle_10dof", "scripts/unified_control", ...
    "simulation", ...
    "scenarios/Acceleration", "scenarios/Skidpad", ...
    "scenarios/Autocross", "scenarios/Endurance", ...
    "scenarios/OpenLoopTests", ...
    "tests/unit", "tests/integration", "tests/regression", ...
    "tests/reference", "tests/common", "tests/smoke", ...
    "tests/battery", "tests/path_tracking", "tests/quasi_static", ...
    "tests/vehicle_dynamics", "tests/open_loop_components", "tests/open_loop_scenarios", "tests/tire", "tests/torque_vectoring", ...
    "tests/vehicle_10dof", "tests/unified_control", "tests/quasi_static/results", "tests/torque_vectoring/results", ...
    "tests/vehicle_10dof/results", "tests/unified_control/results", ...
    "results", "tools", "cache"];

for folder = requiredFolders
    absoluteFolder = fullfile(projectRoot, folder);
    if ~isfolder(absoluteFolder)
        mkdir(absoluteFolder);
    end
end

project = getOrCreateProject(projectRoot);
project.Name = "FSAE_Simulation";

pathFolders = [ ...
    "data", "models/top", "models/plant", "models/controller", ...
    "models/driver", "models/components", "models/libraries", ...
    "scripts/initialization", "scripts/path_tracking", "scripts/track", "scripts/tire", "scripts/ggv", ...
    "scripts/lap_time", "scripts/simulation", "simulation", ...
    "scripts/reporting", "scripts/torque_vectoring", "scripts/vehicle_10dof", "scripts/unified_control", ...
    "scenarios/OpenLoopTests", "tests/common", "tests/smoke", ...
    "tests/path_tracking", "tests/quasi_static", ...
    "tests/vehicle_dynamics", "tests/open_loop_components", "tests/open_loop_scenarios", "tests/tire", "tests/torque_vectoring", ...
    "tests/vehicle_10dof", "tests/unified_control"];
for folder = pathFolders
    addPath(project, char(folder));
end

registrationFolders = [".satk", "data", "models", "scripts", "simulation", ...
    "scenarios", "tests", "tools"];
for folder = registrationFolders
    addFolderIncludingChildFiles(project, char(folder));
end
projectDocuments = ["README.md", "ROADMAP.md", "CHANGELOG.md", ...
    "OPEN_QUESTIONS.md"];
for projectDocument = projectDocuments
    if isfile(fullfile(projectRoot, projectDocument))
        addFile(project, char(projectDocument));
    end
end
if isfile(fullfile(projectRoot, "results", ".gitkeep"))
    addFile(project, "results/.gitkeep");
end

% Transient results and Simulink autosave files must not become project files.
projectFiles = project.Files;
for fileIndex = 1:numel(projectFiles)
    projectFilePath = string(projectFiles(fileIndex).Path);
    relativePath = string(erase(projectFilePath, projectRoot + filesep));
    isGeneratedResult = startsWith(relativePath, "results" + filesep) && ...
        relativePath ~= "results" + filesep + ".gitkeep";
    isGeneratedTestResult = startsWith(relativePath, "tests" + filesep) && ...
        contains(relativePath, filesep + "results" + filesep) && ...
        ~endsWith(relativePath, filesep + "results" + filesep + "README.md");
    isRetiredDocumentationPath = relativePath == "docs" || ...
        startsWith(relativePath, "docs" + filesep);
    isAutosave = any(endsWith(projectFilePath, [".autosave", ".asv"], ...
        IgnoreCase = true));
    if isGeneratedResult || isGeneratedTestResult || ...
            isRetiredDocumentationPath || isAutosave
        removeFile(project, projectFilePath);
    end
end

rootFiles = ["AGENTS_FSAE_Simulink.md", "README.md", ...
    ".gitignore", ".gitattributes"];
for file = rootFiles
    if isfile(fullfile(projectRoot, file))
        addFile(project, char(file));
    end
end

generatedFolder = fullfile(project.RootFolder, "cache");
project.SimulinkCacheFolder = generatedFolder;
project.SimulinkCodeGenFolder = generatedFolder;
project.DependencyCacheFile = fullfile(generatedFolder, "dep_cache.graphml");

% Apply the same locations to the active MATLAB session. Project properties
% are persisted, but fileGenControl also covers models opened outside the
% Project interface during this session.
Simulink.fileGenControl( ...
    "set", ...
    "CacheFolder", char(generatedFolder), ...
    "CodeGenFolder", char(generatedFolder), ...
    "createDir", true);

createProjectFoundationDataDictionary(projectRoot);
addFile(project, "data/VehicleData.sldd");
addPath(project, "data");

fprintf("FSAE project configured: %s\n", project.RootFolder);
end

function project = getOrCreateProject(projectRoot)
try
    project = currentProject;
    if ~strcmpi(string(project.RootFolder), projectRoot)
        close(project);
        project = openProject(projectRoot);
    end
catch
    projectMetadata = fullfile(projectRoot, "resources", "project");
    if isfolder(projectMetadata)
        project = openProject(projectRoot);
    else
        project = matlab.project.createProject( ...
            Folder = projectRoot, Name = "FSAE_Simulation");
    end
end
end
