function cases = createUnifiedControlScenarioMatrix(options)
%CREATEUnifiedControlSCENARIOMATRIX Build traceable UnifiedControl feature-combination cases.

arguments
    options.Profiles (1, :) string = [ ...
        "Baseline", "TVOnly", "TCOnly", "RegenEnergy", ...
        "TVTC", "AllFeatures", "NoRegen"]
    options.Event (1, 1) string = "Skidpad"
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scenarios", "Skidpad"));

switch lower(options.Event)
    case "skidpad"
        scenario = createPathTrackingSkidpadScenario();
    otherwise
        error("FSAE:UnifiedControl:UnknownEvent", ...
            "Unsupported UnifiedControl verification event '%s'.", options.Event);
end

definitions = struct( ...
    "Baseline", [false, false, true, false], ...
    "TVOnly", [true, false, false, false], ...
    "TCOnly", [false, true, false, false], ...
    "RegenEnergy", [false, false, true, true], ...
    "TVTC", [true, true, false, false], ...
    "AllFeatures", [true, true, true, true], ...
    "NoRegen", [true, true, false, true]);

cases = struct.empty(0, 1);
for index = 1:numel(options.Profiles)
    profile = options.Profiles(index);
    if ~isfield(definitions, profile)
        error("FSAE:UnifiedControl:UnknownProfile", ...
            "Unknown UnifiedControl feature profile '%s'.", profile);
    end
    enable = definitions.(profile);
    fingerprint = profile + "_TV" + string(double(enable(1))) + ...
        "_TC" + string(double(enable(2))) + ...
        "_REGEN" + string(double(enable(3))) + ...
        "_ENERGY" + string(double(enable(4)));
    caseDefinition = struct( ...
        "Name", options.Event + "_" + profile, ...
        "Profile", profile, ...
        "Event", options.Event, ...
        "ModelName", "FSAE_UnifiedControl_ClosedLoop", ...
        "Scenario", scenario, ...
        "TireModel", "MF62", ...
        "EnableTV", logical(enable(1)), ...
        "EnableTC", logical(enable(2)), ...
        "EnableRegen", logical(enable(3)), ...
        "EnableEnergyManagement", logical(enable(4)), ...
        "ConfigurationFingerprint", fingerprint);
    if index == 1
        cases = caseDefinition;
    else
        cases(index, 1) = caseDefinition;
    end
end
end
