function report = runUnifiedControlFunctionVerification(options)
%RUNUnifiedControlFUNCTIONVERIFICATION Verify UnifiedControl allocation functions without Simulink.

arguments
    options.DictionaryPath (1, 1) string = defaultDictionaryPath()
    options.SaveSummary (1, 1) logical = true
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "unified_control"));
installUnifiedControlData(DictionaryPath = options.DictionaryPath);
p = loadParameters(options.DictionaryPath);

nominal = defaultCase(p);
nominal.DesiredLongitudinalForce = 1000.0;
nominalResult = runCase(nominal, p);
assert(max(nominalResult.MotorTorque) - min(nominalResult.MotorTorque) ...
    <= 0.05, "FSAE:UnifiedControlNominalBalance", ...
    "Nominal straight-drive allocation is not balanced.");

yawCase = nominal;
yawCase.DesiredYawMoment = 100.0;
yawCase.EnableTV = true;
yawResult = runCase(yawCase, p);
assert(yawResult.MotorTorque(2) > yawResult.MotorTorque(1) && ...
    yawResult.MotorTorque(4) > yawResult.MotorTorque(3) && ...
    yawResult.AllocatedYawMoment > 0.0, "FSAE:UnifiedControlYawSign", ...
    "Positive yaw request did not increase right-wheel torque.");

tcCase = yawCase;
tcCase.EnableTC = true;
tcCase.WheelSpeed(1) = (tcCase.LongitudinalSpeed / ...
    p.UnifiedControlTireEffectiveRadius) * 1.20;
tcCase.MotorSpeed = tcCase.WheelSpeed .* p.UnifiedControlGearRatio;
tcResult = runCase(tcCase, p);
assert(tcResult.TCActive && ...
    tcResult.MotorTorque(1) < tcResult.MotorTorque(2), ...
    "FSAE:UnifiedControlTCActivation", ...
    "Single-wheel overslip did not derate the affected drive channel.");

powerCase = nominal;
powerCase.DesiredLongitudinalForce = 1.0e5;
powerCase.MotorSpeed(:) = 1000.0;
powerCase.PreviousMotorTorque(:) = p.UnifiedControlMotorTorqueLimit;
powerResult = runCase(powerCase, p);
assert(powerResult.TotalPower <= p.UnifiedControlDrivePowerLimit + 1.0, ...
    "FSAE:UnifiedControlDrivePower", "Drive power limit was exceeded.");

regenCase = nominal;
regenCase.DesiredLongitudinalForce = -1.0e5;
regenCase.MotorSpeed(:) = 1000.0;
regenCase.PreviousMotorTorque(:) = 0.0;
regenResult = runCase(regenCase, p);
assert(regenResult.TotalPower >= -p.UnifiedControlRegenPowerLimit - 1.0, ...
    "FSAE:UnifiedControlRegenPower", "Regenerative power limit was exceeded.");
assert(all(regenResult.FrictionBrakeTorque >= 0.0), ...
    "FSAE:UnifiedControlBrakeSign", "Friction-brake torque must be nonnegative.");

frictionCase = regenCase;
frictionCase.EnableRegen = false;
frictionCase.PreviousMotorTorque(:) = 0.0;
frictionResult = runCase(frictionCase, p);
assert(all(frictionResult.MotorTorque >= -1.0e-12) && ...
    all(frictionResult.RegenTorque == 0.0) && ...
    any(frictionResult.FrictionBrakeTorque > 0.0), ...
    "FSAE:UnifiedControlFrictionOnly", ...
    "Disabled regeneration did not transfer braking to friction brakes.");

invalidCase = nominal;
invalidCase.WheelSpeedValid(1) = false;
invalidResult = runCase(invalidCase, p);
assert(invalidResult.ControllerMode == uint8(3) && ...
    invalidResult.MotorTorque(1) <= 0.0, ...
    "FSAE:UnifiedControlDegradedWheel", ...
    "Invalid wheel speed did not select degraded drive inhibition.");

disabledCase = nominal;
disabledCase.EnableActuation = false;
disabledResult = runCase(disabledCase, p);
assert(all(disabledResult.MotorTorque == 0.0) && ...
    all(disabledResult.FrictionBrakeTorque == 0.0) && ...
    disabledResult.ControllerMode == uint8(0), ...
    "FSAE:UnifiedControlDisabled", "Disabled actuation was not fail-safe zero.");

releaseCase = nominal;
releaseCase.DesiredLongitudinalForce = 0.0;
releaseCase.PreviousMotorTorque = powerResult.MotorTorque;
releaseResult = runCase(releaseCase, p);
rateStep = p.UnifiedControlMotorTorqueRateLimit * p.UnifiedControlSampleTime;
assert(all(abs(releaseResult.MotorTorque - ...
    releaseCase.PreviousMotorTorque) <= rateStep + 1.0e-9), ...
    "FSAE:UnifiedControlRateRecovery", "Recovery exceeded the motor torque-rate bound.");

verifyTCHysteresis(p, nominal);
verifyEstimatorConservation(p, nominal);

report = struct( ...
    "Status", "PASS", ...
    "ScenarioCount", 10, ...
    "NominalTorqueSpread", max(nominalResult.MotorTorque) - ...
        min(nominalResult.MotorTorque), ...
    "PositiveYawDelivered", yawResult.AllocatedYawMoment, ...
    "TCPeerTorqueMargin", tcResult.MotorTorque(2) - ...
        tcResult.MotorTorque(1), ...
    "PeakDrivePower", powerResult.TotalPower, ...
    "PeakRegenPowerMagnitude", max(0.0, -regenResult.TotalPower), ...
    "RecoveryTorqueStep", max(abs(releaseResult.MotorTorque - ...
        releaseCase.PreviousMotorTorque)), ...
    "ParameterCaveat", ...
        "UnifiedControl control thresholds remain tentative pending vehicle data.");
if options.SaveSummary
    resultFolder = fullfile(projectRoot, "tests", "unified_control", "results");
    if ~isfolder(resultFolder)
        mkdir(resultFolder);
    end
    save(fullfile(resultFolder, "UnifiedControlFunctionVerificationSummary.mat"), ...
        "report", "-v7.3");
end
disp(report)
end

function output = runCase(input, p)
[output.MotorTorque, output.FrictionBrakeTorque, output.RegenTorque, ...
    output.TotalPower, output.AllocatedYawMoment, ...
    output.WheelTorqueUnconstrained, output.ControllerSaturated, ...
    output.TCActive, output.RegenActive, output.EnergyManagementActive, ...
    output.ControllerMode, output.ConstraintFlags, ...
    output.PreviousMotorTorqueNext, output.TCStateNext] = ...
    unifiedControlUnifiedAllocationStep(input.DesiredLongitudinalForce, ...
    input.DesiredYawMoment, input.LongitudinalSpeed, input.WheelSpeed, ...
    input.MotorSpeed, input.AccelX, input.AccelY, input.BatterySOC, ...
    input.WheelSpeedValid, input.PowertrainValid, input.EnableTV, ...
    input.EnableTC, input.EnableRegen, input.EnableEnergyManagement, ...
    input.EnableActuation, input.PreviousMotorTorque, ...
    input.TCStatePrevious, p.UnifiedControlSampleTime, p.UnifiedControlVehicleMass, ...
    p.UnifiedControlGravity, p.UnifiedControlWheelbase, p.UnifiedControlCGHeight, ...
    p.UnifiedControlStaticLoadDistributionFront, ...
    p.UnifiedControlRollStiffnessDistributionFront, p.UnifiedControlTrackFront, ...
    p.UnifiedControlTrackRear, p.UnifiedControlTireEffectiveRadius, p.UnifiedControlLowSpeedEpsilon, ...
    p.UnifiedControlGearRatio, p.UnifiedControlGearEfficiency, p.UnifiedControlMotorTorqueLimit, ...
    p.UnifiedControlMotorSpeedLimit, p.UnifiedControlInverterEfficiency, p.UnifiedControlDrivePowerLimit, ...
    p.UnifiedControlRegenPowerLimit, p.UnifiedControlBrakeMaxTorque, ...
    p.UnifiedControlBatterySOCUpperLimit, p.UnifiedControlPowerEpsilon, ...
    p.UnifiedControlMotorTorqueRateLimit, p.UnifiedControlFrictionEstimate, p.UnifiedControlTCSlipOn, ...
    p.UnifiedControlTCSlipOff, p.UnifiedControlTCSlipFullCut, p.UnifiedControlMinimumNormalLoad, ...
    p.UnifiedControlEnergyDriveFraction, p.UnifiedControlForcePriorityWeight, ...
    p.UnifiedControlYawPriorityWeight, p.UnifiedControlRegularizationWeight, ...
    p.UnifiedControlAllocatorIterations);
end

function input = defaultCase(p)
input = struct( ...
    "DesiredLongitudinalForce", 0.0, ...
    "DesiredYawMoment", 0.0, ...
    "LongitudinalSpeed", 10.0, ...
    "WheelSpeed", ones(4, 1) .* 10.0 ./ p.UnifiedControlTireEffectiveRadius, ...
    "MotorSpeed", ones(4, 1) .* 10.0 ./ ...
        p.UnifiedControlTireEffectiveRadius .* p.UnifiedControlGearRatio, ...
    "AccelX", 0.0, ...
    "AccelY", 0.0, ...
    "BatterySOC", 0.5, ...
    "WheelSpeedValid", true(4, 1), ...
    "PowertrainValid", true, ...
    "EnableTV", false, ...
    "EnableTC", false, ...
    "EnableRegen", true, ...
    "EnableEnergyManagement", false, ...
    "EnableActuation", true, ...
    "PreviousMotorTorque", zeros(4, 1), ...
    "TCStatePrevious", false(4, 1));
end

function verifyTCHysteresis(p, nominal)
wheelSpeed = nominal.WheelSpeed;
wheelSpeed(1) = nominal.LongitudinalSpeed * 1.15 / ...
    p.UnifiedControlTireEffectiveRadius;
[~, ~, ~, ~, stateOn] = unifiedControlEstimateWheelConstraints( ...
    nominal.LongitudinalSpeed, wheelSpeed, 0.0, 0.0, true(4, 1), ...
    true, false(4, 1), p.UnifiedControlVehicleMass, p.UnifiedControlGravity, p.UnifiedControlWheelbase, ...
    p.UnifiedControlCGHeight, p.UnifiedControlStaticLoadDistributionFront, ...
    p.UnifiedControlRollStiffnessDistributionFront, p.UnifiedControlTrackFront, p.UnifiedControlTrackRear, ...
    p.UnifiedControlTireEffectiveRadius, p.UnifiedControlLowSpeedEpsilon, ...
    p.UnifiedControlFrictionEstimate, p.UnifiedControlMinimumNormalLoad, p.UnifiedControlTCSlipOn, ...
    p.UnifiedControlTCSlipOff, p.UnifiedControlTCSlipFullCut);
wheelSpeed(1) = nominal.LongitudinalSpeed * 1.10 / ...
    p.UnifiedControlTireEffectiveRadius;
[~, ~, ~, ~, stateHeld] = unifiedControlEstimateWheelConstraints( ...
    nominal.LongitudinalSpeed, wheelSpeed, 0.0, 0.0, true(4, 1), ...
    true, stateOn, p.UnifiedControlVehicleMass, p.UnifiedControlGravity, p.UnifiedControlWheelbase, ...
    p.UnifiedControlCGHeight, p.UnifiedControlStaticLoadDistributionFront, ...
    p.UnifiedControlRollStiffnessDistributionFront, p.UnifiedControlTrackFront, p.UnifiedControlTrackRear, ...
    p.UnifiedControlTireEffectiveRadius, p.UnifiedControlLowSpeedEpsilon, ...
    p.UnifiedControlFrictionEstimate, p.UnifiedControlMinimumNormalLoad, p.UnifiedControlTCSlipOn, ...
    p.UnifiedControlTCSlipOff, p.UnifiedControlTCSlipFullCut);
wheelSpeed(1) = nominal.LongitudinalSpeed * 1.05 / ...
    p.UnifiedControlTireEffectiveRadius;
[~, ~, ~, ~, stateOff] = unifiedControlEstimateWheelConstraints( ...
    nominal.LongitudinalSpeed, wheelSpeed, 0.0, 0.0, true(4, 1), ...
    true, stateHeld, p.UnifiedControlVehicleMass, p.UnifiedControlGravity, p.UnifiedControlWheelbase, ...
    p.UnifiedControlCGHeight, p.UnifiedControlStaticLoadDistributionFront, ...
    p.UnifiedControlRollStiffnessDistributionFront, p.UnifiedControlTrackFront, p.UnifiedControlTrackRear, ...
    p.UnifiedControlTireEffectiveRadius, p.UnifiedControlLowSpeedEpsilon, ...
    p.UnifiedControlFrictionEstimate, p.UnifiedControlMinimumNormalLoad, p.UnifiedControlTCSlipOn, ...
    p.UnifiedControlTCSlipOff, p.UnifiedControlTCSlipFullCut);
assert(stateOn(1) && stateHeld(1) && ~stateOff(1), ...
    "FSAE:UnifiedControlTCHysteresis", "TC hysteresis did not latch and release correctly.");
end

function verifyEstimatorConservation(p, nominal)
[normalLoad, ~, tireCapacity] = unifiedControlEstimateWheelConstraints( ...
    nominal.LongitudinalSpeed, nominal.WheelSpeed, 3.0, 6.0, ...
    true(4, 1), false, false(4, 1), p.UnifiedControlVehicleMass, p.UnifiedControlGravity, ...
    p.UnifiedControlWheelbase, p.UnifiedControlCGHeight, p.UnifiedControlStaticLoadDistributionFront, ...
    p.UnifiedControlRollStiffnessDistributionFront, p.UnifiedControlTrackFront, p.UnifiedControlTrackRear, ...
    p.UnifiedControlTireEffectiveRadius, p.UnifiedControlLowSpeedEpsilon, ...
    p.UnifiedControlFrictionEstimate, p.UnifiedControlMinimumNormalLoad, p.UnifiedControlTCSlipOn, ...
    p.UnifiedControlTCSlipOff, p.UnifiedControlTCSlipFullCut);
assert(all(normalLoad > 0.0) && abs(sum(normalLoad) - ...
    p.UnifiedControlVehicleMass * p.UnifiedControlGravity) <= 1.0e-9 && ...
    all(tireCapacity >= 0.0), "FSAE:UnifiedControlLoadConservation", ...
    "Estimated loads are not positive and mass-conserving.");
end

function parameters = loadParameters(dictionaryPath)
dictionary = Simulink.data.dictionary.open(dictionaryPath);
cleanup = onCleanup(@() close(dictionary));
section = getSection(dictionary, "Design Data");
names = ["UnifiedControlSampleTime", "UnifiedControlVehicleMass", "UnifiedControlGravity", ...
    "UnifiedControlWheelbase", "UnifiedControlCGHeight", "UnifiedControlStaticLoadDistributionFront", ...
    "UnifiedControlRollStiffnessDistributionFront", "UnifiedControlTrackFront", "UnifiedControlTrackRear", ...
    "UnifiedControlTireEffectiveRadius", "UnifiedControlLowSpeedEpsilon", "UnifiedControlGearRatio", ...
    "UnifiedControlGearEfficiency", "UnifiedControlMotorTorqueLimit", "UnifiedControlMotorSpeedLimit", ...
    "UnifiedControlInverterEfficiency", "UnifiedControlDrivePowerLimit", "UnifiedControlRegenPowerLimit", ...
    "UnifiedControlBrakeMaxTorque", "UnifiedControlBatterySOCUpperLimit", "UnifiedControlPowerEpsilon", ...
    "UnifiedControlMotorTorqueRateLimit", "UnifiedControlFrictionEstimate", "UnifiedControlTCSlipOn", ...
    "UnifiedControlTCSlipOff", "UnifiedControlTCSlipFullCut", "UnifiedControlMinimumNormalLoad", ...
    "UnifiedControlEnergyDriveFraction", "UnifiedControlForcePriorityWeight", ...
    "UnifiedControlYawPriorityWeight", "UnifiedControlRegularizationWeight", ...
    "UnifiedControlAllocatorIterations"];
for name = names
    value = getValue(getEntry(section, name));
    parameters.(name) = valueOf(value);
end
end

function value = valueOf(input)
if isa(input, "Simulink.Parameter")
    value = input.Value;
elseif isstruct(input) && isfield(input, "Value")
    value = input.Value;
else
    value = input;
end
end

function path = defaultDictionaryPath()
projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
path = fullfile(projectRoot, "data", "VehicleData.sldd");
end
