function controlDesign = installTorqueVectoringControlData(options)
%INSTALLTorqueVectoringCONTROLDATA Install traceable TorqueVectoring runtime parameters.
%   Physical aliases are copied deterministically from the shared vehicle
%   parameter records. Control gains and stability limits are explicitly
%   marked as tentative design placeholders pending OQ-011.

arguments
    options.DictionaryPath (1, 1) string = defaultDictionaryPath()
end

dictionary = Simulink.data.dictionary.open(options.DictionaryPath);
cleanup = onCleanup(@() close(dictionary));
designData = getSection(dictionary, "Design Data");

vehicle = getValue(getEntry(designData, "Vehicle"));
tire = getValue(getEntry(designData, "Tire"));
powertrain = getValue(getEntry(designData, "Powertrain"));
battery = getValue(getEntry(designData, "Battery"));
brake = getValue(getEntry(designData, "Brake"));
simulation = getValue(getEntry(designData, "Simulation"));

controlDesign = struct( ...
    "SchemaVersion", "1.0", ...
    "Status", "TENTATIVE_TorqueVectoring_CONTROL_DESIGN", ...
    "ObjectivePriority", ...
        "yaw-rate tracking, then path error; energy is monitored", ...
    "YawKp", record(360.0, "N*m/(rad/s)", ...
        "ControlDesignPlaceholder", "Low"), ...
    "YawKi", record(90.0, "N*m/rad", ...
        "ControlDesignPlaceholder", "Low"), ...
    "YawAntiWindupGain", record(4.0, "1/s", ...
        "ControlDesignPlaceholder", "Low"), ...
    "YawMomentLimit", record(350.0, "N*m", ...
        "ControlDesignPlaceholder", "Low"), ...
    "UndersteerGradient", record(0.0, "s^2/m", ...
        "NeutralSteerPlaceholder", "Low"), ...
    "MinimumControlSpeed", record(1.0, "m/s", ...
        "NumericalProtectionDesign", "Design"), ...
    "FrictionEstimate", record(1.0, "1", ...
        "ConservativeControlDesignReference", "Low"), ...
    "LateralAccelerationLimit", record(8.0, "m/s^2", ...
        "ConservativeControlDesignPlaceholder", "Low"), ...
    "YawRateLimit", record(2.5, "rad/s", ...
        "ControlDesignPlaceholder", "Low"), ...
    "Notes", ...
        "The controller retains a conservative 1.0 friction estimate; " + ...
        "tire forces use the independent road grip scale and optional absolute limit.");

runtime = {
    "TorqueVectoringControlSampleTime", valueOf(simulation.TsController), "s", ...
        "Shared Simulation.TsController";
    "TorqueVectoringWheelbase", valueOf(vehicle.Wheelbase), "m", ...
        "Shared Vehicle.Wheelbase";
    "TorqueVectoringTrackFront", valueOf(vehicle.TrackFront), "m", ...
        "Shared Vehicle.TrackFront";
    "TorqueVectoringTrackRear", valueOf(vehicle.TrackRear), "m", ...
        "Shared Vehicle.TrackRear";
    "TorqueVectoringVehicleMass", valueOf(vehicle.Mass), "kg", ...
        "Shared Vehicle.Mass";
    "TorqueVectoringTireEffectiveRadius", valueOf(tire.EffectiveRadius), "m", ...
        "Shared Tire.EffectiveRadius";
    "TorqueVectoringGearRatio", valueOf(powertrain.GearRatio), "1", ...
        "Shared Powertrain.GearRatio";
    "TorqueVectoringGearEfficiency", valueOf(powertrain.GearEfficiency), "1", ...
        "Shared Powertrain.GearEfficiency";
    "TorqueVectoringMotorTorqueLimit", valueOf(powertrain.MotorTorqueLimit), "N*m", ...
        "Shared Powertrain.MotorTorqueLimit";
    "TorqueVectoringMotorSpeedLimit", valueOf(powertrain.MotorSpeedLimit), "rad/s", ...
        "Shared Powertrain.MotorSpeedLimit";
    "TorqueVectoringInverterEfficiency", valueOf(powertrain.InverterEfficiency), "1", ...
        "Shared Powertrain.InverterEfficiency";
    "TorqueVectoringDrivePowerLimit", valueOf(battery.PowerLimitDrive), "W", ...
        "Shared Battery.PowerLimitDrive";
    "TorqueVectoringRegenPowerLimit", valueOf(battery.PowerLimitRegen), "W", ...
        "Shared Battery.PowerLimitRegen";
    "TorqueVectoringBatterySOCUpperLimit", valueOf(battery.SOCUpperLimit), "1", ...
        "Shared Battery.SOCUpperLimit";
    "TorqueVectoringBrakeMaxTorque", valueOf(brake.MaxTorquePerWheel), "N*m", ...
        "Shared Brake.MaxTorquePerWheel";
    "TorqueVectoringPowerEpsilon", valueOf(battery.PowerEpsilon), "W", ...
        "Shared Battery.PowerEpsilon";
    "TorqueVectoringGravity", valueOf(simulation.Gravity), "m/s^2", ...
        "Shared Simulation.Gravity";
    "TorqueVectoringYawKp", controlDesign.YawKp.Value, controlDesign.YawKp.Unit, ...
        controlDesign.YawKp.Source;
    "TorqueVectoringYawKi", controlDesign.YawKi.Value, controlDesign.YawKi.Unit, ...
        controlDesign.YawKi.Source;
    "TorqueVectoringYawAntiWindupGain", controlDesign.YawAntiWindupGain.Value, ...
        controlDesign.YawAntiWindupGain.Unit, ...
        controlDesign.YawAntiWindupGain.Source;
    "TorqueVectoringYawMomentLimit", controlDesign.YawMomentLimit.Value, ...
        controlDesign.YawMomentLimit.Unit, ...
        controlDesign.YawMomentLimit.Source;
    "TorqueVectoringUndersteerGradient", controlDesign.UndersteerGradient.Value, ...
        controlDesign.UndersteerGradient.Unit, ...
        controlDesign.UndersteerGradient.Source;
    "TorqueVectoringMinimumControlSpeed", controlDesign.MinimumControlSpeed.Value, ...
        controlDesign.MinimumControlSpeed.Unit, ...
        controlDesign.MinimumControlSpeed.Source;
    "TorqueVectoringFrictionEstimate", controlDesign.FrictionEstimate.Value, ...
        controlDesign.FrictionEstimate.Unit, ...
        controlDesign.FrictionEstimate.Source;
    "TorqueVectoringLateralAccelerationLimit", ...
        controlDesign.LateralAccelerationLimit.Value, ...
        controlDesign.LateralAccelerationLimit.Unit, ...
        controlDesign.LateralAccelerationLimit.Source;
    "TorqueVectoringYawRateLimit", controlDesign.YawRateLimit.Value, ...
        controlDesign.YawRateLimit.Unit, ...
        controlDesign.YawRateLimit.Source;
    "TorqueVectoringMaximumAcceleration", 8.0, "m/s^2", ...
        "PathTracking control envelope placeholder";
    "TorqueVectoringMaximumDeceleration", 8.0, "m/s^2", ...
        "PathTracking control envelope placeholder";
    "TorqueVectoringEnableTV", false, "1", ...
        "Scenario configuration switch"
    };

for row = 1:size(runtime, 1)
    parameter = Simulink.Parameter(runtime{row, 2});
    parameter.Unit = runtime{row, 3};
    parameter.Description = "TorqueVectoring runtime parameter; source=" + ...
        string(runtime{row, 4});
    setEntry(designData, runtime{row, 1}, parameter);
end
setEntry(designData, "TorqueVectoringControlDesign", controlDesign);
saveChanges(dictionary);
end

function value = valueOf(recordValue)
if isa(recordValue, "Simulink.Parameter")
    value = recordValue.Value;
elseif isstruct(recordValue) && isfield(recordValue, "Value")
    value = recordValue.Value;
else
    value = recordValue;
end
end

function output = record(value, unit, source, confidence)
output = struct( ...
    "Value", value, "LowerBound", NaN, "UpperBound", NaN, ...
    "Unit", unit, "Source", source, "Confidence", confidence, ...
    "LastUpdated", "2026-07-31", "IsMeasured", false, ...
    "IsPlaceholder", true);
end

function setEntry(section, name, value)
try
    entry = getEntry(section, name);
    setValue(entry, value);
catch exception
    if contains(exception.identifier, "EntryNotFound") || ...
            contains(exception.message, "does not exist", ...
            IgnoreCase = true)
        addEntry(section, name, value);
    else
        rethrow(exception);
    end
end
end

function path = defaultDictionaryPath()
projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
path = fullfile(projectRoot, "data", "VehicleData.sldd");
end
