function [SteeringWheelAngleRequest, SteeringRackAngleRequest, ...
    LongitudinalAccelerationRequest, DriveTorqueRequest, ...
    BrakePressureRequest, EnableTV, EnableTC, EnableRegen, ...
    EnableEnergyManagement, DriverMode] = ...
    fsaeAdaptiveAutocrossDriverCore(trackData, sensor)
%FSAEADAPTIVEAUTOCROSSDRIVERCORE Simulink wrapper for the adaptive driver.
%   This wrapper accepts track geometry and sensor state directly, including
%   the GGV reference-speed ceiling stored in trackData.ReferenceSpeed.

persistent driverState
if isempty(driverState)
    driverState = struct( ...
        "PreviousIndex", 1.0, ...
        "PreviousReferenceIndex", 1.0, ...
        "PreviousSteering", 0.0, ...
        "SpeedIntegrator", 0.0);
end

config = struct( ...
    "ControlSampleTime", AADControlSampleTime, ...
    "Wheelbase", AADWheelbase, ...
    "CGToFrontAxle", AADCGToFrontAxle, ...
    "CGToRearAxle", AADCGToRearAxle, ...
    "FrontHalfEnvelope", AADFrontHalfEnvelope, ...
    "RearHalfEnvelope", AADRearHalfEnvelope, ...
    "ProjectionSearchWindow", AADProjectionSearchWindow, ...
    "MinimumSteeringPreview", AADMinimumSteeringPreview, ...
    "SteeringPreviewTime", AADSteeringPreviewTime, ...
    "MaximumSteeringPreview", AADMaximumSteeringPreview, ...
    "HeadingGain", AADHeadingGain, ...
    "CrossTrackGain", AADCrossTrackGain, ...
    "BoundaryGain", AADBoundaryGain, ...
    "MinimumSteeringSpeed", AADMinimumSteeringSpeed, ...
    "MaximumSteeringAngle", AADMaximumSteeringAngle, ...
    "MaximumSteeringRate", AADMaximumSteeringRate, ...
    "SteeringWheelRatio", AADSteeringWheelRatio, ...
    "LateralAccelerationLimit", AADLateralAccelerationLimit, ...
    "MaximumAcceleration", AADMaximumAcceleration, ...
    "MaximumDeceleration", AADMaximumDeceleration, ...
    "PlanningDeceleration", AADPlanningDeceleration, ...
    "MaximumSpeed", AADMaximumSpeed, ...
    "SpeedPreviewDistance", AADSpeedPreviewDistance, ...
    "SpeedPreviewStep", AADSpeedPreviewStep, ...
    "CurvatureFilterHalfWindow", AADCurvatureFilterHalfWindow, ...
    "CurvatureSafetyFactor", AADCurvatureSafetyFactor, ...
    "SpeedSafetyFactor", AADSpeedSafetyFactor, ...
    "SpeedKp", AADSpeedKp, ...
    "SpeedKi", AADSpeedKi, ...
    "SpeedFeedforwardGain", AADSpeedFeedforwardGain, ...
    "ExitSpeedFeedforwardGain", AADExitSpeedFeedforwardGain, ...
    "AntiWindupGain", AADAntiWindupGain, ...
    "ReferencePathCurvatureBlendStart", ...
        AADReferencePathCurvatureBlendStart, ...
    "ReferencePathCurvatureBlendEnd", ...
        AADReferencePathCurvatureBlendEnd, ...
    "ReferencePathMaximumBlend", AADReferencePathMaximumBlend, ...
    "BoundaryPreviewDistance", AADBoundaryPreviewDistance, ...
    "BoundaryReserve", AADBoundaryReserve, ...
    "EmergencyBoundaryMargin", AADEmergencyBoundaryMargin, ...
    "EnableTV", AADEnableTV, ...
    "BrakePressurePerAcceleration", AADBrakePressurePerAcceleration);

[command, driverState] = fsaeAdaptiveAutocrossDriverStep( ...
    trackData, sensor, driverState, config);

SteeringWheelAngleRequest = command.SteeringWheelAngleRequest;
SteeringRackAngleRequest = command.SteeringRackAngleRequest;
LongitudinalAccelerationRequest = ...
    command.LongitudinalAccelerationRequest;
DriveTorqueRequest = command.DriveTorqueRequest;
BrakePressureRequest = command.BrakePressureRequest;
EnableTV = command.EnableTV;
EnableTC = command.EnableTC;
EnableRegen = command.EnableRegen;
EnableEnergyManagement = command.EnableEnergyManagement;
DriverMode = command.DriverMode;
end
