function [command, nextState, debug] = ...
    fsaeAdaptiveAutocrossDriverStep(trackData, sensor, state, config)
%FSAEADAPTIVEAUTOCROSSDRIVERSTEP GGV-bounded autonomous driver step.
%   The driver tracks the GGV reference-speed ceiling while independently
%   projecting the vehicle, controlling path/boundary error, and retaining
%   a geometry-only speed fallback when no valid reference is available.
%   All distances are m, speeds m/s, accelerations m/s^2, and angles rad.

command = zeroCommand();
nextState = state;
debug = zeroDebug();

sampleCount = min(double(trackData.SampleCount), ...
    double(numel(trackData.X)));
poseIsFinite = isfinite(sensor.PositionX) && ...
    isfinite(sensor.PositionY) && isfinite(sensor.Heading) && ...
    isfinite(sensor.LongitudinalSpeed);
trackIsUsable = sampleCount >= 2 && ...
    isfinite(trackData.SampleDistance) && trackData.SampleDistance > 0 && ...
    isfinite(trackData.X(1)) && isfinite(trackData.Y(1));
if ~trackIsUsable || ~sensor.PoseValid || ~poseIsFinite
    command = failSafeCommand(config);
    nextState.PreviousIndex = 1.0;
    nextState.PreviousReferenceIndex = 1.0;
    nextState.PreviousSteering = 0.0;
    nextState.SpeedIntegrator = 0.0;
    return
end

isClosed = logical(trackData.IsClosed);
physicalPreviousIndex = floor(double(state.PreviousIndex));
if physicalPreviousIndex < 1 || physicalPreviousIndex > sampleCount
    physicalPreviousIndex = 1;
end
[physicalIndex, physicalFraction, physicalProjectedX, ...
    physicalProjectedY] = projectVehicle( ...
    trackData.X, trackData.Y, sensor.PositionX, sensor.PositionY, ...
    physicalPreviousIndex, sampleCount, isClosed, ...
    config.ProjectionSearchWindow);
nextState.PreviousIndex = physicalIndex;
physicalNextIndex = adjacentIndex(physicalIndex + 1, ...
    sampleCount, isClosed);
physicalHeading = interpolateAngle(trackData.Heading(physicalIndex), ...
    trackData.Heading(physicalNextIndex), physicalFraction);
physicalCurvature = interpolateLinear( ...
    trackData.Curvature(physicalIndex), ...
    trackData.Curvature(physicalNextIndex), physicalFraction);
currentLeftWidth = interpolateLinear( ...
    trackData.LeftHalfWidth(physicalIndex), ...
    trackData.LeftHalfWidth(physicalNextIndex), physicalFraction);
currentRightWidth = interpolateLinear( ...
    trackData.RightHalfWidth(physicalIndex), ...
    trackData.RightHalfWidth(physicalNextIndex), physicalFraction);

[boundaryMargin, boundaryCorrectionSign] = ...
    projectVehicleEnvelopeClearance(trackData, sensor, ...
    physicalIndex, sampleCount, isClosed, config);

referencePathValid = logical(trackData.ReferencePathValid) && ...
    isfinite(trackData.ReferenceSampleDistance) && ...
    trackData.ReferenceSampleDistance > 0.0;
if referencePathValid
    referenceIndex = physicalIndex;
    referenceFraction = physicalFraction;
    referenceNextIndex = adjacentIndex(referenceIndex + 1, ...
        sampleCount, isClosed);
    referenceProjectedX = interpolateLinear( ...
        trackData.ReferenceX(referenceIndex), ...
        trackData.ReferenceX(referenceNextIndex), referenceFraction);
    referenceProjectedY = interpolateLinear( ...
        trackData.ReferenceY(referenceIndex), ...
        trackData.ReferenceY(referenceNextIndex), referenceFraction);
    % Reference arrays share the physical station index; preview distances
    % therefore use the physical station spacing even when the offset path
    % has a slightly different geometric length.
    referenceSampleDistance = double(trackData.SampleDistance);
else
    referenceIndex = physicalIndex;
    referenceFraction = physicalFraction;
    referenceProjectedX = physicalProjectedX;
    referenceProjectedY = physicalProjectedY;
    referenceSampleDistance = double(trackData.SampleDistance);
end
nextState.PreviousReferenceIndex = referenceIndex;
referenceNextIndex = adjacentIndex(referenceIndex + 1, ...
    sampleCount, isClosed);
referenceHeading = interpolateAngle( ...
    trackData.ReferenceHeading(referenceIndex), ...
    trackData.ReferenceHeading(referenceNextIndex), referenceFraction);

referenceBlend = referencePathBlend(referencePathValid, ...
    boundaryMargin, physicalCurvature, config);
[previewBoundaryMargin, previewBoundaryCorrectionSign] = ...
    previewReferenceEnvelopeClearance(trackData, referenceIndex, ...
    referenceFraction, referenceSampleDistance, sampleCount, ...
    isClosed, config);
previewBoundaryMargin = interpolateLinear(boundaryMargin, ...
    previewBoundaryMargin, referenceBlend);
controlBoundaryMargin = min(boundaryMargin, previewBoundaryMargin);
if previewBoundaryMargin < boundaryMargin
    boundaryCorrectionSign = previewBoundaryCorrectionSign;
end
referenceBlend = referencePathBlend(referencePathValid, ...
    controlBoundaryMargin, physicalCurvature, config);
projectedX = interpolateLinear(physicalProjectedX, ...
    referenceProjectedX, referenceBlend);
projectedY = interpolateLinear(physicalProjectedY, ...
    referenceProjectedY, referenceBlend);
currentHeading = interpolateAngle(physicalHeading, ...
    referenceHeading, referenceBlend);
deltaX = sensor.PositionX - projectedX;
deltaY = sensor.PositionY - projectedY;
lateralError = -deltaX * sin(currentHeading) + ...
    deltaY * cos(currentHeading);
if lateralError >= 0.0
    availableHalfWidth = max(currentLeftWidth, 0.0);
else
    availableHalfWidth = max(currentRightWidth, 0.0);
end
speedMagnitude = max(0.0, double(sensor.LongitudinalSpeed));
steeringPreview = min(config.MaximumSteeringPreview, ...
    max(config.MinimumSteeringPreview, ...
    config.SteeringPreviewTime * speedMagnitude));
[physicalTargetIndex, physicalTargetFraction] = offsetCoordinate( ...
    physicalIndex, physicalFraction, steeringPreview, ...
    trackData.SampleDistance, sampleCount, isClosed);
physicalTargetNextIndex = adjacentIndex(physicalTargetIndex + 1, ...
    sampleCount, isClosed);
physicalTargetHeading = interpolateAngle( ...
    trackData.Heading(physicalTargetIndex), ...
    trackData.Heading(physicalTargetNextIndex), physicalTargetFraction);
physicalTargetCurvature = filteredCurvature(trackData.Curvature, ...
    physicalTargetIndex, sampleCount, isClosed, ...
    config.CurvatureFilterHalfWindow);
[referenceTargetIndex, referenceTargetFraction] = offsetCoordinate( ...
    referenceIndex, referenceFraction, steeringPreview, ...
    referenceSampleDistance, ...
    sampleCount, isClosed);
referenceTargetNextIndex = adjacentIndex(referenceTargetIndex + 1, ...
    sampleCount, isClosed);
referenceTargetHeading = interpolateAngle( ...
    trackData.ReferenceHeading(referenceTargetIndex), ...
    trackData.ReferenceHeading(referenceTargetNextIndex), ...
    referenceTargetFraction);
referenceTargetCurvature = filteredCurvature( ...
    trackData.ReferenceCurvature, referenceTargetIndex, ...
    sampleCount, isClosed, config.CurvatureFilterHalfWindow);
targetHeading = interpolateAngle(physicalTargetHeading, ...
    referenceTargetHeading, referenceBlend);
targetCurvature = interpolateLinear(physicalTargetCurvature, ...
    referenceTargetCurvature, referenceBlend);

headingError = wrapAngle(targetHeading - sensor.Heading);
speedForSteering = max(speedMagnitude, config.MinimumSteeringSpeed);
widthScale = max(availableHalfWidth - ...
    max(config.FrontHalfEnvelope, config.RearHalfEnvelope), 0.10);
normalizedError = min(2.0, abs(lateralError) / widthScale);
boundaryUrgency = min(2.0, max(0.0, ...
    (config.BoundaryReserve - controlBoundaryMargin) / ...
    max(config.BoundaryReserve + ...
    config.EmergencyBoundaryMargin, 1.0e-6)));
effectiveCrossTrackGain = config.CrossTrackGain * ...
    (1.0 + config.BoundaryGain * ...
    (normalizedError^2 + boundaryUrgency^2));
curvatureFeedForward = atan(config.Wheelbase * targetCurvature);
feedbackSteering = config.HeadingGain * headingError - ...
    atan2(effectiveCrossTrackGain * lateralError, speedForSteering);
boundarySteering = boundaryCorrectionSign * ...
    0.5 * config.MaximumSteeringAngle * min(1.0, boundaryUrgency);
requestedSteering = saturate(curvatureFeedForward + ...
    feedbackSteering + boundarySteering, config.MaximumSteeringAngle);
steeringRateLimit = config.MaximumSteeringRate * ...
    config.ControlSampleTime;
steeringDelta = saturate(requestedSteering - ...
    state.PreviousSteering, steeringRateLimit);
command.SteeringRackAngleRequest = state.PreviousSteering + ...
    steeringDelta;
nextState.PreviousSteering = command.SteeringRackAngleRequest;
command.SteeringWheelAngleRequest = config.SteeringWheelRatio * ...
    command.SteeringRackAngleRequest;

[safeSpeed, limitingCurvature] = onlineSpeedCeiling(trackData, ...
    referenceIndex, referenceFraction, sampleCount, isClosed, config);
referenceAcceleration = referenceAccelerationFeedforward(trackData, ...
    referenceIndex, referenceFraction, referenceSampleDistance, ...
    sampleCount, isClosed, config);
% Positive feedforward reduces acceleration lag. Braking remains closed-loop
% so a falling reference cannot combine with lateral-capacity limiting and
% over-brake a hairpin below the speed needed for stable path tracking.
referenceAcceleration = max(0.0, referenceAcceleration);
% Preserve a continuous path to zero speed at the physical edge. This hard
% envelope guarantee is intentionally independent of the GGV speed ceiling.
if controlBoundaryMargin < config.BoundaryReserve
    normalizedMargin = controlBoundaryMargin / ...
        max(config.BoundaryReserve, 1.0e-6);
    normalizedMargin = min(1.0, max(0.0, normalizedMargin));
    boundaryScale = normalizedMargin;
    safeSpeed = safeSpeed * boundaryScale;
end
if boundaryMargin <= 0.0
    safeSpeed = 0.0;
end

if sensor.IMUValid && isfinite(sensor.AccelY)
    lateralAcceleration = abs(sensor.AccelY);
else
    lateralAcceleration = speedMagnitude^2 * abs(targetCurvature);
end
lateralUtilization = min(1.0, lateralAcceleration / ...
    max(config.LateralAccelerationLimit, 1.0e-6));
combinedCapacityScale = sqrt(max(0.0, ...
    1.0 - lateralUtilization^2));
availableAcceleration = config.MaximumAcceleration * ...
    combinedCapacityScale;
availableDeceleration = config.MaximumDeceleration * ...
    max(0.25, combinedCapacityScale);

speedError = safeSpeed - speedMagnitude;
integratorForControl = state.SpeedIntegrator;
if speedError <= 0.0
    % SafeSpeed is a hard ceiling, not a symmetric reference.  Positive
    % integral memory must never keep accelerating an overspeed vehicle.
    integratorForControl = min(0.0, integratorForControl);
end
feedforwardGain = scheduledFeedforwardGain(trackData, ...
    referenceIndex, referenceFraction, referenceSampleDistance, ...
    sampleCount, isClosed, referenceAcceleration, targetCurvature, ...
    controlBoundaryMargin, requestedSteering, config);
unsaturatedAcceleration = feedforwardGain * ...
    referenceAcceleration + ...
    config.SpeedKp * speedError + ...
    integratorForControl;
if speedError <= 0.0
    unsaturatedAcceleration = min(0.0, unsaturatedAcceleration);
end
if controlBoundaryMargin < config.EmergencyBoundaryMargin
    availableAcceleration = 0.0;
end
if boundaryMargin <= 0.0
    availableDeceleration = config.MaximumDeceleration;
end
command.LongitudinalAccelerationRequest = min( ...
    availableAcceleration, max(-availableDeceleration, ...
    unsaturatedAcceleration));
antiWindupError = command.LongitudinalAccelerationRequest - ...
    unsaturatedAcceleration;
nextState.SpeedIntegrator = integratorForControl + ...
    config.ControlSampleTime * (config.SpeedKi * speedError + ...
    config.AntiWindupGain * antiWindupError);
nextState.SpeedIntegrator = saturate(nextState.SpeedIntegrator, ...
    config.MaximumDeceleration);

command.BrakePressureRequest = max(0.0, ...
    -command.LongitudinalAccelerationRequest) * ...
    config.BrakePressurePerAcceleration;
command.EnableTV = logical(config.EnableTV);
command.EnableTC = true;
command.EnableRegen = true;
command.DriverMode = uint8(2);

debug.SafeSpeed = safeSpeed;
debug.LateralError = lateralError;
debug.HeadingError = headingError;
debug.BoundaryMargin = boundaryMargin;
debug.TargetCurvature = targetCurvature;
debug.LimitingCurvature = limitingCurvature;
debug.LateralUtilization = lateralUtilization;
debug.ProjectedX = projectedX;
debug.ProjectedY = projectedY;
end

function blend = referencePathBlend(referencePathValid, ...
        boundaryMargin, physicalCurvature, config)
if ~referencePathValid
    blend = 0.0;
    return
end
marginCoordinate = (boundaryMargin - ...
    config.EmergencyBoundaryMargin) / max(config.BoundaryReserve - ...
    config.EmergencyBoundaryMargin, 1.0e-6);
marginWeight = smoothStep01(marginCoordinate);
curvatureCoordinate = (abs(physicalCurvature) - ...
    config.ReferencePathCurvatureBlendStart) / ...
    max(config.ReferencePathCurvatureBlendEnd - ...
    config.ReferencePathCurvatureBlendStart, 1.0e-6);
curvatureWeight = 1.0 - smoothStep01(curvatureCoordinate);
blend = min(1.0, max(0.0, config.ReferencePathMaximumBlend)) * ...
    marginWeight * curvatureWeight;
end

function [clearance, correctionSign] = ...
        previewReferenceEnvelopeClearance(trackData, referenceIndex, ...
        referenceFraction, referenceSampleDistance, sampleCount, ...
        isClosed, config)
previewDistance = max(0.0, double(config.BoundaryPreviewDistance));
[referenceTargetIndex, referenceTargetFraction] = offsetCoordinate( ...
    referenceIndex, referenceFraction, previewDistance, ...
    referenceSampleDistance, sampleCount, isClosed);
referenceNextIndex = adjacentIndex(referenceTargetIndex + 1, ...
    sampleCount, isClosed);
clearance = interpolateLinear( ...
    trackData.ReferenceEnvelopeClearance(referenceTargetIndex), ...
    trackData.ReferenceEnvelopeClearance(referenceNextIndex), ...
    referenceTargetFraction);
direction = interpolateLinear( ...
    trackData.ReferenceBoundaryCorrectionSign(referenceTargetIndex), ...
    trackData.ReferenceBoundaryCorrectionSign(referenceNextIndex), ...
    referenceTargetFraction);
correctionSign = 0.0;
if direction < -0.5
    correctionSign = -1.0;
elseif direction > 0.5
    correctionSign = 1.0;
end
end

function gain = scheduledFeedforwardGain(trackData, baseIndex, ...
        baseFraction, sampleDistance, sampleCount, isClosed, ...
        referenceAcceleration, targetCurvature, boundaryMargin, ...
        requestedSteering, config)
gain = config.SpeedFeedforwardGain;
if referenceAcceleration <= 0.0 || ...
        boundaryMargin < config.BoundaryReserve || ...
        abs(requestedSteering) >= 0.95 * config.MaximumSteeringAngle
    return
end
previewDistance = max(double(sampleDistance), ...
    double(config.SpeedPreviewStep));
[previewIndex, previewFraction] = offsetCoordinate(baseIndex, ...
    baseFraction, previewDistance, sampleDistance, sampleCount, isClosed);
previewNextIndex = adjacentIndex(previewIndex + 1, sampleCount, isClosed);
previewCurvature = abs(interpolateLinear( ...
    trackData.ReferenceCurvature(previewIndex), ...
    trackData.ReferenceCurvature(previewNextIndex), previewFraction));
cornerIsOpening = previewCurvature + 0.01 < abs(targetCurvature) && ...
    previewCurvature < 0.06 && abs(targetCurvature) < 0.10;
pathIsStraight = previewCurvature < 0.04 && ...
    abs(targetCurvature) < 0.06;
if cornerIsOpening || pathIsStraight
    gain = max(gain, config.ExitSpeedFeedforwardGain);
end
end

function acceleration = referenceAccelerationFeedforward(trackData, ...
        baseIndex, baseFraction, sampleDistance, sampleCount, ...
        isClosed, config)
% Convert the local v^2-versus-distance gradient into acceleration demand.
nextIndex = adjacentIndex(baseIndex + 1, sampleCount, isClosed);
currentSpeed = interpolateLinear(trackData.ReferenceSpeed(baseIndex), ...
    trackData.ReferenceSpeed(nextIndex), baseFraction);
previewDistance = max(double(sampleDistance), ...
    double(config.SpeedPreviewStep));
[previewIndex, previewFraction] = offsetCoordinate(baseIndex, ...
    baseFraction, previewDistance, sampleDistance, ...
    sampleCount, isClosed);
previewNextIndex = adjacentIndex(previewIndex + 1, sampleCount, isClosed);
previewSpeed = interpolateLinear(trackData.ReferenceSpeed(previewIndex), ...
    trackData.ReferenceSpeed(previewNextIndex), previewFraction);
if ~isfinite(currentSpeed) || currentSpeed <= 0.0 || ...
        ~isfinite(previewSpeed) || previewSpeed <= 0.0
    acceleration = 0.0;
    return
end
currentSpeed = min(config.MaximumSpeed, max(0.0, currentSpeed));
previewSpeed = min(config.MaximumSpeed, max(0.0, previewSpeed));
acceleration = (previewSpeed^2 - currentSpeed^2) / ...
    (2.0 * max(previewDistance, 1.0e-6));
acceleration = min(config.MaximumAcceleration, ...
    max(-config.PlanningDeceleration, acceleration));
end

function [clearance, correctionSign] = ...
        projectVehicleEnvelopeClearance(trackData, sensor, ...
        baseIndex, sampleCount, isClosed, config)
[clearance, correctionSign] = projectPoseEnvelopeClearance( ...
    trackData, sensor.PositionX, sensor.PositionY, sensor.Heading, ...
    baseIndex, sampleCount, isClosed, config);
end

function [clearance, correctionSign] = ...
        projectPoseEnvelopeClearance(trackData, positionX, positionY, ...
        heading, baseIndex, sampleCount, isClosed, config)
% Project all four nominal tire outer-edge points onto actual track segments.
localPoints = [ ...
    config.CGToFrontAxle, config.FrontHalfEnvelope; ...
    config.CGToFrontAxle, -config.FrontHalfEnvelope; ...
    -config.CGToRearAxle, config.RearHalfEnvelope; ...
    -config.CGToRearAxle, -config.RearHalfEnvelope];
cosineHeading = cos(heading);
sineHeading = sin(heading);
minimumLeftClearance = realmax;
minimumRightClearance = realmax;
for pointIndex = 1:4
    localX = localPoints(pointIndex, 1);
    localY = localPoints(pointIndex, 2);
    pointX = positionX + localX * cosineHeading - ...
        localY * sineHeading;
    pointY = positionY + localX * sineHeading + ...
        localY * cosineHeading;
    [pointIndexOnTrack, pointFraction, projectedX, projectedY] = ...
        projectVehicle(trackData.X, trackData.Y, pointX, pointY, ...
        baseIndex, sampleCount, isClosed, ...
        config.ProjectionSearchWindow);
    pointNextIndex = adjacentIndex(pointIndexOnTrack + 1, ...
        sampleCount, isClosed);
    pointHeading = interpolateAngle( ...
        trackData.Heading(pointIndexOnTrack), ...
        trackData.Heading(pointNextIndex), pointFraction);
    pointLateralError = -(pointX - projectedX) * sin(pointHeading) + ...
        (pointY - projectedY) * cos(pointHeading);
    pointLeftWidth = interpolateLinear( ...
        trackData.LeftHalfWidth(pointIndexOnTrack), ...
        trackData.LeftHalfWidth(pointNextIndex), pointFraction);
    pointRightWidth = interpolateLinear( ...
        trackData.RightHalfWidth(pointIndexOnTrack), ...
        trackData.RightHalfWidth(pointNextIndex), pointFraction);
    if pointLateralError >= 0.0
        pointClearance = pointLeftWidth - pointLateralError;
        minimumLeftClearance = min(minimumLeftClearance, pointClearance);
    else
        pointClearance = pointRightWidth + pointLateralError;
        minimumRightClearance = min(minimumRightClearance, pointClearance);
    end
end
clearance = min(minimumLeftClearance, minimumRightClearance);
sideTolerance = 1.0e-9;
if minimumLeftClearance < minimumRightClearance - sideTolerance
    correctionSign = -1.0;
elseif minimumRightClearance < minimumLeftClearance - sideTolerance
    correctionSign = 1.0;
else
    correctionSign = 0.0;
end
end

function [bestIndex, bestFraction, projectedX, projectedY] = ...
    projectVehicle(pathX, pathY, vehicleX, vehicleY, previousIndex, ...
    sampleCount, isClosed, searchWindow)
window = min(floor(double(searchWindow)), floor(sampleCount / 2));
bestIndex = previousIndex;
bestFraction = 0.0;
projectedX = pathX(previousIndex);
projectedY = pathY(previousIndex);
bestDistanceSquared = realmax;
for offset = -window:window
    candidate = adjacentIndex(previousIndex + offset, ...
        sampleCount, isClosed);
    if ~isClosed && candidate >= sampleCount
        candidate = sampleCount - 1;
    end
    nextCandidate = adjacentIndex(candidate + 1, sampleCount, isClosed);
    segmentX = pathX(nextCandidate) - pathX(candidate);
    segmentY = pathY(nextCandidate) - pathY(candidate);
    segmentLengthSquared = segmentX^2 + segmentY^2;
    if segmentLengthSquared > eps
        fraction = ((vehicleX - pathX(candidate)) * segmentX + ...
            (vehicleY - pathY(candidate)) * segmentY) / ...
            segmentLengthSquared;
        fraction = min(1.0, max(0.0, fraction));
    else
        fraction = 0.0;
    end
    candidateX = pathX(candidate) + fraction * segmentX;
    candidateY = pathY(candidate) + fraction * segmentY;
    distanceSquared = (candidateX - vehicleX)^2 + ...
        (candidateY - vehicleY)^2;
    if distanceSquared < bestDistanceSquared
        bestDistanceSquared = distanceSquared;
        bestIndex = candidate;
        bestFraction = fraction;
        projectedX = candidateX;
        projectedY = candidateY;
    end
end
end

function [safeSpeed, limitingCurvature] = onlineSpeedCeiling( ...
    trackData, baseIndex, baseFraction, sampleCount, isClosed, config)
nextIndex = adjacentIndex(baseIndex + 1, sampleCount, isClosed);
ggvSpeedCeiling = interpolateLinear( ...
    trackData.ReferenceSpeed(baseIndex), ...
    trackData.ReferenceSpeed(nextIndex), baseFraction);
if isfinite(ggvSpeedCeiling) && ggvSpeedCeiling > 0.0
    safeSpeed = min(config.MaximumSpeed, max(0.0, ggvSpeedCeiling));
    limitingCurvature = curvatureMagnitudeEnvelope( ...
        trackData.ReferenceCurvature, baseIndex, sampleCount, ...
        isClosed, config.CurvatureFilterHalfWindow);
    return
end

% Retain the geometry-only planner as a fail-safe for scenarios that do not
% provide a positive GGV speed ceiling.
safeSpeed = max(config.MaximumSpeed, 0.0);
limitingCurvature = 0.0;
previewStep = max(config.SpeedPreviewStep, ...
    max(trackData.SampleDistance, 0.05));
previewCount = min(255, ceil(config.SpeedPreviewDistance / previewStep));
decelerationLimit = max(0.25 * config.MaximumDeceleration, 0.10);
for previewIndex = 0:255
    if previewIndex > previewCount
        break
    end
    distanceAhead = double(previewIndex) * previewStep;
    [sampleIndex, ~] = offsetCoordinate(baseIndex, baseFraction, ...
        distanceAhead, trackData.SampleDistance, sampleCount, isClosed);
    curvature = curvatureMagnitudeEnvelope(trackData.Curvature, ...
        sampleIndex, sampleCount, isClosed, ...
        config.CurvatureFilterHalfWindow);
    protectedCurvature = max(config.CurvatureSafetyFactor * ...
        curvature, 1.0e-6);
    cornerSpeed = sqrt(max(config.LateralAccelerationLimit, 0.10) / ...
        protectedCurvature) * config.SpeedSafetyFactor;
    cornerSpeed = min(config.MaximumSpeed, max(0.0, cornerSpeed));
    planningDeceleration = min(decelerationLimit, ...
        max(config.PlanningDeceleration, 0.10));
    reachableSpeed = sqrt(max(0.0, cornerSpeed^2 + ...
        2.0 * planningDeceleration * distanceAhead));
    if reachableSpeed < safeSpeed
        safeSpeed = reachableSpeed;
        limitingCurvature = curvature;
    end
end
end

function curvature = filteredCurvature(curvatureData, ...
    centerIndex, sampleCount, isClosed, halfWindow)
window = min(20, max(0, floor(double(halfWindow))));
curvatureSum = 0.0;
weightSum = 0.0;
for offset = -20:20
    if abs(offset) <= window
        index = adjacentIndex(centerIndex + offset, sampleCount, isClosed);
        weight = double(window + 1 - abs(offset));
        curvatureSum = curvatureSum + weight * curvatureData(index);
        weightSum = weightSum + weight;
    end
end
curvature = curvatureSum / max(weightSum, 1.0);
end

function curvature = curvatureMagnitudeEnvelope(curvatureData, centerIndex, ...
    sampleCount, isClosed, halfWindow)
window = min(20, max(0, floor(double(halfWindow))));
curvature = 0.0;
for offset = -20:20
    if abs(offset) <= window
        index = adjacentIndex(centerIndex + offset, sampleCount, isClosed);
        curvature = max(curvature, abs(curvatureData(index)));
    end
end
end

function [index, fraction] = offsetCoordinate(baseIndex, baseFraction, ...
    distanceAhead, sampleDistance, sampleCount, isClosed)
protectedSpacing = max(double(sampleDistance), 1.0e-6);
coordinate = double(baseIndex - 1) + baseFraction + ...
    distanceAhead / protectedSpacing;
if isClosed
    coordinate = mod(coordinate, sampleCount);
    baseCoordinate = floor(coordinate);
    index = baseCoordinate + 1;
    fraction = coordinate - baseCoordinate;
else
    coordinate = min(double(sampleCount - 1), max(0.0, coordinate));
    if coordinate >= sampleCount - 1
        index = sampleCount;
        fraction = 0.0;
    else
        baseCoordinate = floor(coordinate);
        index = baseCoordinate + 1;
        fraction = coordinate - baseCoordinate;
    end
end
end

function index = adjacentIndex(rawIndex, sampleCount, isClosed)
if isClosed
    index = mod(rawIndex - 1, sampleCount) + 1;
else
    index = min(sampleCount, max(1, rawIndex));
end
index = floor(index);
end

function output = interpolateLinear(first, second, fraction)
output = first + fraction * (second - first);
end

function output = interpolateAngle(first, second, fraction)
difference = wrapAngle(second - first);
output = wrapAngle(first + fraction * difference);
end

function output = smoothStep01(input)
coordinate = min(1.0, max(0.0, input));
output = coordinate^2 * (3.0 - 2.0 * coordinate);
end

function output = wrapAngle(input)
output = atan2(sin(input), cos(input));
end

function output = saturate(input, limit)
protectedLimit = max(0.0, double(limit));
output = min(protectedLimit, max(-protectedLimit, input));
end

function command = zeroCommand()
command = struct( ...
    "SteeringWheelAngleRequest", 0.0, ...
    "SteeringRackAngleRequest", 0.0, ...
    "LongitudinalAccelerationRequest", 0.0, ...
    "DriveTorqueRequest", 0.0, ...
    "BrakePressureRequest", 0.0, ...
    "EnableTV", false, ...
    "EnableTC", false, ...
    "EnableRegen", true, ...
    "EnableEnergyManagement", false, ...
    "DriverMode", uint8(0));
end

function command = failSafeCommand(config)
command = zeroCommand();
command.LongitudinalAccelerationRequest = ...
    -max(0.0, config.MaximumDeceleration);
command.BrakePressureRequest = ...
    max(0.0, config.MaximumDeceleration) * ...
    config.BrakePressurePerAcceleration;
command.EnableTC = true;
command.EnableRegen = true;
command.DriverMode = uint8(2);
end

function debug = zeroDebug()
debug = struct( ...
    "SafeSpeed", 0.0, ...
    "LateralError", 0.0, ...
    "HeadingError", 0.0, ...
    "BoundaryMargin", 0.0, ...
    "TargetCurvature", 0.0, ...
    "LimitingCurvature", 0.0, ...
    "LateralUtilization", 0.0, ...
    "ProjectedX", 0.0, ...
    "ProjectedY", 0.0);
end
