classdef TrackScenarioTest < matlab.unittest.TestCase
    %TRACKSCENARIOTEST Regression tests for PathTracking event-track geometry.

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            projectRoot = string(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            folders = [ ...
                fullfile(projectRoot, "scripts", "track"), ...
                fullfile(projectRoot, "scripts", "simulation"), ...
                fullfile(projectRoot, "scenarios", "Skidpad"), ...
                fullfile(projectRoot, "scenarios", "Autocross"), ...
                fullfile(projectRoot, "scenarios", "Endurance"), ...
                fullfile(projectRoot, "scenarios", "Acceleration")];
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                folders(1)));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                folders(2)));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                folders(3)));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                folders(4)));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                folders(5)));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                folders(6)));
        end
    end

    methods (Test)
        function testSkidpadCompleteRunGeometry(testCase)
            scenario = createPathTrackingSkidpadScenario(SampleDistance = 0.1);
            track = scenario.Track;
            trackData = makePathTrackingTrackData(track);
            pathS = (0:numel(track.X) - 1)' * track.SampleDistance;
            rightCurvature = track.Curvature( ...
                pathS > track.TimingLineS + 1.0 & ...
                pathS < track.RightLoopsEndS - 1.0);
            leftCurvature = track.Curvature( ...
                pathS > track.RightLoopsEndS + 1.0 & ...
                pathS < track.FinishLineS - 1.0);

            testCase.verifyFalse(track.IsClosed);
            testCase.verifyEqual(track.RunSequence, ...
                "Entry -> Right x2 -> Left x2 -> Exit");
            testCase.verifyEqual(track.RightCircleLapCount, 2);
            testCase.verifyEqual(track.LeftCircleLapCount, 2);
            testCase.verifyEqual([track.X(1), track.Y(1)], [0, -20], ...
                AbsTol = 1.0e-10);
            testCase.verifyEqual([track.X(end), track.Y(end)], [0, 20], ...
                AbsTol = 1.0e-10);
            testCase.verifyEqual(track.Length, ...
                40 + 8 * pi * track.CenterlineRadius, AbsTol = 2.0e-3);
            testCase.verifyEqual(min(track.X), -18.25, AbsTol = 2.0e-3);
            testCase.verifyEqual(max(track.X), 18.25, AbsTol = 2.0e-3);
            testCase.verifyEqual(track.PathWidth, 3.0, AbsTol = 1.0e-12);
            testCase.verifyEqual(double(trackData.SampleCount), ...
                numel(track.X));
            testCase.verifyLessThan(mean(rightCurvature), 0);
            testCase.verifyGreaterThan(mean(leftCurvature), 0);
        end

        function testAutocrossIsCounterclockwise(testCase)
            scenario = createPathTrackingAutocrossScenario();
            track = scenario.Track;
            signedArea = 0.5 * sum(track.X .* circshift(track.Y, -1) - ...
                circshift(track.X, -1) .* track.Y);

            testCase.verifyGreaterThan(signedArea, 0);
            testCase.verifyEqual(track.TraversalDirection, ...
                "counterclockwise");
            testCase.verifyEqual([track.X(1), track.Y(1)], [0, 0], ...
                AbsTol = 1.0e-12);
            testCase.verifyEqual(track.Length, 1000.0, ...
                AbsTol = 1.0e-10);
            testCase.verifyEqual(numel(track.X), 2000);
            testCase.verifyEqual(track.SourceDocument, ...
                "2024 FSEC竞赛手册Handbook");
            testCase.verifyEqual(track.SourceImageSHA256, ...
                "C769CEBF8EAE4CAA92D0BE26629C7665D393E9EADDB17C0314140CC57E7A0531");
            testCase.verifyTrue(isfile(track.SourceImage));
            testCase.verifyGreaterThanOrEqual( ...
                track.SourceTraceCoverage, 0.95);
            testCase.verifyTrue( ...
                track.ExtractionSettings.PruneSkeletonSpurs);
            testCase.verifyGreaterThan(size( ...
                track.ExtractionSettings.SupplementalPathWaypoints, 1), 2);
            testCase.verifySubstring(track.EventUsage, ...
                "not an official Autocross layout");

            closedStep = hypot(circshift(track.X, -1) - track.X, ...
                circshift(track.Y, -1) - track.Y);
            testCase.verifyEqual(mean(closedStep), ...
                track.SampleDistance, AbsTol = 2.0e-3);
            testCase.verifyLessThan(max(closedStep), ...
                1.2 * track.SampleDistance);
        end

        function testImageDerivedTrackUsesNamedDataFile(testCase)
            dataFolder = string(tempname);
            cleanup = onCleanup(@() removeFolderIfPresent(dataFolder));

            firstScenario = createPathTrackingAutocrossScenario( ...
                DataFolder = dataFolder);
            secondScenario = createPathTrackingAutocrossScenario( ...
                DataFolder = dataFolder);

            testCase.verifyFalse(firstScenario.Track.TrackData.Loaded);
            testCase.verifyTrue(secondScenario.Track.TrackData.Loaded);
            testCase.verifyTrue(isfile( ...
                secondScenario.Track.TrackData.File));
            testCase.verifyEqual(secondScenario.Track.TrackData.File, ...
                fullfile(dataFolder, "autocross.mat"));
            testCase.verifyEqual(secondScenario.Track.X, ...
                firstScenario.Track.X, AbsTol = 0.0);
            testCase.verifyEqual(secondScenario.Track.Y, ...
                firstScenario.Track.Y, AbsTol = 0.0);
            clear cleanup
        end

        function testGeneratedTracksUseNamedDataFiles(testCase)
            dataFolder = string(tempname);
            cleanup = onCleanup(@() removeFolderIfPresent(dataFolder));

            firstAcceleration = createPathTrackingAccelerationScenario( ...
                TargetSpeed = 10.0, DataFolder = dataFolder);
            secondAcceleration = createPathTrackingAccelerationScenario( ...
                TargetSpeed = 20.0, DataFolder = dataFolder);
            firstSkidpad = createPathTrackingSkidpadScenario( ...
                TargetSpeed = 6.0, DataFolder = dataFolder);
            secondSkidpad = createPathTrackingSkidpadScenario( ...
                TargetSpeed = 9.0, DataFolder = dataFolder);

            testCase.verifyFalse( ...
                firstAcceleration.Track.TrackData.Loaded);
            testCase.verifyTrue( ...
                secondAcceleration.Track.TrackData.Loaded);
            testCase.verifyEqual(secondAcceleration.Track.TrackData.File, ...
                fullfile(dataFolder, "acceleration.mat"));
            testCase.verifyEqual(secondAcceleration.Track.X, ...
                firstAcceleration.Track.X, AbsTol = 0.0);
            testCase.verifyEqual(secondAcceleration.Track.ReferenceSpeed, ...
                20.0 * ones(size(secondAcceleration.Track.X)), ...
                AbsTol = 0.0);

            testCase.verifyFalse(firstSkidpad.Track.TrackData.Loaded);
            testCase.verifyTrue(secondSkidpad.Track.TrackData.Loaded);
            testCase.verifyEqual(secondSkidpad.Track.TrackData.File, ...
                fullfile(dataFolder, "skidpad.mat"));
            testCase.verifyEqual(secondSkidpad.Track.X, ...
                firstSkidpad.Track.X, AbsTol = 0.0);
            testCase.verifyGreaterThan( ...
                max(secondSkidpad.Track.ReferenceSpeed), ...
                max(firstSkidpad.Track.ReferenceSpeed));
            testCase.verifyNotEqual( ...
                secondSkidpad.Track.TrackData.File, ...
                secondAcceleration.Track.TrackData.File);
            clear cleanup
        end

        function testClosedTrackPlotPathJoinsFinishToStart(testCase)
            scenario = createPathTrackingAutocrossScenario();
            track = scenario.Track;
            [plotX, plotY] = closeTrackPlotPath( ...
                track, double(track.X(:)), double(track.Y(:)));

            testCase.verifyGreaterThan(hypot( ...
                track.X(end) - track.X(1), ...
                track.Y(end) - track.Y(1)), 0.0);
            testCase.verifyNumElements(plotX, numel(track.X) + 1);
            testCase.verifyNumElements(plotY, numel(track.Y) + 1);
            testCase.verifyEqual([plotX(end), plotY(end)], ...
                [plotX(1), plotY(1)], AbsTol = 0.0);
            testCase.verifyEqual(plotX(1:end - 1), track.X, ...
                AbsTol = 0.0);
            testCase.verifyEqual(plotY(1:end - 1), track.Y, ...
                AbsTol = 0.0);
        end

        function testClosedTrackFinalViewSharesStartFinishMarker(testCase)
            scenario = createPathTrackingAutocrossScenario();
            result = struct( ...
                "Time", [0; 1], ...
                "Vehicle", struct( ...
                    "X", [scenario.Track.X(1); scenario.Track.X(100)], ...
                    "Y", [scenario.Track.Y(1); scenario.Track.Y(100)], ...
                    "Speed", [1; 2]), ...
                "Track", struct("EventDistance", [0; 10]), ...
                "Meta", struct, ...
                "Metrics", struct);
            cfg = struct( ...
                "Driver", struct("Model", "test"), ...
                "Vehicle", struct("DynamicsModel", "test"));
            figureHandle = createFinalTrackViewFigure( ...
                scenario, result, cfg, Visible = "off");
            cleanup = onCleanup(@() close(figureHandle));

            startMarker = findobj(figureHandle, ...
                "Tag", "FSAE_StartMarker");
            finishMarker = findobj(figureHandle, ...
                "Tag", "FSAE_FinishMarker");

            testCase.verifyEqual( ...
                [startMarker.XData, startMarker.YData], ...
                [scenario.Track.X(1), scenario.Track.Y(1)], ...
                AbsTol = 0.0);
            testCase.verifyEqual( ...
                [finishMarker.XData, finishMarker.YData], ...
                [startMarker.XData, startMarker.YData], AbsTol = 0.0);
        end

        function testTrackDataFallsBackToPhysicalReferencePath(testCase)
            scenario = createPathTrackingAutocrossScenario();

            trackData = makePathTrackingTrackData(scenario.Track);
            sampleCount = double(trackData.SampleCount);

            testCase.verifyFalse(trackData.ReferencePathValid);
            testCase.verifyEqual(trackData.ReferenceSampleDistance, ...
                scenario.Track.SampleDistance, AbsTol = 1.0e-12);
            testCase.verifyEqual(trackData.ReferenceX(1:sampleCount), ...
                scenario.Track.X, AbsTol = 1.0e-12);
            testCase.verifyEqual(trackData.ReferenceY(1:sampleCount), ...
                scenario.Track.Y, AbsTol = 1.0e-12);
        end

        function testTrackDataPacksRacingReferencePath(testCase)
            scenario = createPathTrackingAutocrossScenario();
            track = scenario.Track;
            track.RacingLineX = track.X + 0.10;
            track.RacingLineY = track.Y - 0.05;
            track.RacingLineHeading = track.Heading + 0.01;
            track.RacingLineCurvature = 0.90 * track.Curvature;
            track.RacingLineSampleDistance = ...
                0.99 * track.SampleDistance;
            track.RacingLineEnvelopeClearance = ...
                0.80 * ones(size(track.X));
            track.RacingLineBoundaryCorrectionSign = ...
                zeros(size(track.X));

            trackData = makePathTrackingTrackData(track);
            sampleCount = double(trackData.SampleCount);

            testCase.verifyTrue(trackData.ReferencePathValid);
            testCase.verifyEqual(trackData.ReferenceSampleDistance, ...
                track.RacingLineSampleDistance, AbsTol = 1.0e-12);
            testCase.verifyEqual(trackData.ReferenceX(1:sampleCount), ...
                track.RacingLineX, AbsTol = 1.0e-12);
            testCase.verifyEqual(trackData.ReferenceCurvature(1:sampleCount), ...
                track.RacingLineCurvature, AbsTol = 1.0e-12);
            testCase.verifyEqual( ...
                trackData.ReferenceEnvelopeClearance(1:sampleCount), ...
                track.RacingLineEnvelopeClearance, AbsTol = 1.0e-12);
        end

        function testEnduranceIsCounterclockwise(testCase)
            scenario = createPathTrackingEnduranceScenario(NumberOfLaps = 2);
            track = scenario.Track;
            signedArea = 0.5 * sum(track.X .* circshift(track.Y, -1) - ...
                circshift(track.X, -1) .* track.Y);

            testCase.verifyGreaterThan(signedArea, 0);
            testCase.verifyEqual(track.TraversalDirection, ...
                "counterclockwise");
            testCase.verifyEqual(scenario.NumberOfLaps, 2);
            testCase.verifyEqual(track.SourceDocument, ...
                "2024 FSEC竞赛手册Handbook");
            testCase.verifySubstring(track.EventUsage, ...
                "Endurance geometry extracted");
            testCase.verifyTrue(endsWith(track.TrackData.File, ...
                fullfile("trackdata", "endurance.mat")));
        end

        function testAutocrossAndEnduranceShareNewSource(testCase)
            autocross = createPathTrackingAutocrossScenario();
            endurance = createPathTrackingEnduranceScenario(NumberOfLaps = 2);

            testCase.verifyEqual(endurance.Track.X, ...
                autocross.Track.X, AbsTol = 1.0e-12);
            testCase.verifyEqual(endurance.Track.Y, ...
                autocross.Track.Y, AbsTol = 1.0e-12);
            testCase.verifyEqual(endurance.Track.SourceImageSHA256, ...
                autocross.Track.SourceImageSHA256);
            testCase.verifyNotEqual(endurance.ID, autocross.ID);
        end

        function testAutocrossMarkedRegionsStartAndLateTurnAreRegularized( ...
                testCase)
            scenario = createPathTrackingAutocrossScenario();
            track = scenario.Track;
            s = (0:numel(track.X) - 1)' * track.SampleDistance;

            startMask = s <= 16.0 | s >= track.Length - 16.0;
            startPoints = [track.X(startMask), track.Y(startMask)];
            centeredPoints = startPoints - mean(startPoints, 1);
            [~, ~, directions] = svd(centeredPoints, 0);
            normalDirection = directions(:, 2);
            straightDeviation = abs(centeredPoints * normalDirection);

            lateTurnMask = s >= track.Length - 80.0 & ...
                s <= track.Length - 30.0;
            testCase.verifyLessThan(max(straightDeviation), 0.01);
            testCase.verifyLessThan(max(abs(track.X(startMask))), ...
                1.0e-10);
            testCase.verifyLessThan(track.Y(2), 0.0);
            testCase.verifyGreaterThan(track.Y(end), 0.0);
            testCase.verifyLessThan(max(abs( ...
                track.Curvature(startMask))), 0.01);
            testCase.verifyLessThan(max(abs( ...
                track.Curvature(lateTurnMask))), 0.22);
            testCase.verifyGreaterThan( ...
                track.GeometryRegularization.LateTurnPeakCurvatureBefore, ...
                0.50);
            testCase.verifyLessThan( ...
                track.GeometryRegularization.LateTurnPeakCurvatureAfter, ...
                0.22);
            regularization = track.GeometryRegularization;
            peakBefore = regularization.MarkedRegionPeakCurvatureBefore;
            peakAfter = regularization.MarkedRegionPeakCurvatureAfter;
            for regionIndex = 1:3
                testCase.verifyLessThan(peakAfter(regionIndex), ...
                    0.85 * peakBefore(regionIndex));
            end
            testCase.verifyEqual(regularization.StraightInnerDistance, ...
                16.0);
            testCase.verifyEqual(regularization.StraightOuterDistance, ...
                42.0);
            testCase.verifyEqual(regularization.StraightDirection, ...
                [0.0, -1.0]);
        end

        function testDirectionReversalSwapsTrackSides(testCase)
            track = makeClockwiseSquareTrack();
            orientedTrack = orientPathTrackingClosedTrack( ...
                track, "counterclockwise");

            testCase.verifyEqual(orientedTrack.LeftHalfWidth, ...
                [4; 7; 6; 5], AbsTol = 1.0e-12);
            testCase.verifyEqual(orientedTrack.RightHalfWidth, ...
                [1; 4; 3; 2], AbsTol = 1.0e-12);
            testCase.verifyTrue(orientedTrack.DirectionWasReversed);
            testCase.verifyGreaterThan(orientedTrack.SignedArea, 0);
        end

        function testOpenTrackCompletesAtPathEnd(testCase)
            scenario = createPathTrackingSkidpadScenario(SampleDistance = 0.5);
            sampleCount = numel(scenario.Track.X);
            [state, beforeFinish] = replayTrack( ...
                scenario, 1:sampleCount - 1, struct);
            [state, atFinish] = replayTrack( ...
                scenario, sampleCount, state);

            testCase.verifyFalse(beforeFinish);
            testCase.verifyTrue(atFinish);
            testCase.verifyEqual(state.EventDistance, ...
                scenario.Track.Length, AbsTol = scenario.Track.SampleDistance);
        end

        function testClosedTrackCompletesAfterRequestedLaps(testCase)
            scenario = createPathTrackingEnduranceScenario( ...
                NumberOfLaps = 2, SampleDistance = 0.5);
            sampleCount = numel(scenario.Track.X);
            [state, afterOneLap] = replayTrack( ...
                scenario, [1:sampleCount, 1], struct);
            [state, afterTwoLaps] = replayTrack( ...
                scenario, [2:sampleCount, 1], state);

            testCase.verifyFalse(afterOneLap);
            testCase.verifyTrue(afterTwoLaps);
            testCase.verifyEqual(state.EventDistance, ...
                2 * scenario.Track.Length, ...
                AbsTol = scenario.Track.SampleDistance);
        end

        function testStationaryAtFinishDoesNotComplete(testCase)
            scenario = createPathTrackingSkidpadScenario(SampleDistance = 0.5);
            sampleCount = numel(scenario.Track.X);
            [state, firstSample] = replayTrack( ...
                scenario, sampleCount, struct);
            [state, repeatedSample] = replayTrack( ...
                scenario, sampleCount, state);

            testCase.verifyFalse(firstSample);
            testCase.verifyFalse(repeatedSample);
            testCase.verifyEqual(state.EventDistance, 0, AbsTol = 1.0e-12);
        end

        function testOpenFinishGateCrossingCompletes(testCase)
            scenario = createPathTrackingSkidpadScenario(SampleDistance = 0.5);
            pathEnd = scenario.Track.Length;
            beforeFinish = struct( ...
                "Vehicle", struct("X", 0, "Y", 19.8), ...
                "Track", struct("PathS", pathEnd));
            afterFinish = struct( ...
                "Vehicle", struct("X", 0, "Y", 20.2), ...
                "Track", struct("PathS", pathEnd));

            [state, beforeCrossing] = updateLapCompletionState( ...
                struct, scenario, beforeFinish);
            [state, afterCrossing] = updateLapCompletionState( ...
                state, scenario, afterFinish);

            testCase.verifyFalse(beforeCrossing);
            testCase.verifyTrue(afterCrossing);
            testCase.verifyLessThan(state.EventDistance, ...
                scenario.Track.SampleDistance);
        end
    end
end

function [state, isComplete] = replayTrack(scenario, indices, state)
isComplete = false;
for index = reshape(indices, 1, [])
    snapshot = struct( ...
        "Vehicle", struct( ...
        "X", scenario.Track.X(index), ...
        "Y", scenario.Track.Y(index)));
    [state, isComplete] = updateLapCompletionState( ...
        state, scenario, snapshot);
end
end

function track = makeClockwiseSquareTrack()
track = struct( ...
    "IsClosed", true, ...
    "SampleDistance", 1.0, ...
    "X", [0; 0; 1; 1], ...
    "Y", [0; 1; 1; 0], ...
    "Heading", zeros(4, 1), ...
    "Curvature", zeros(4, 1), ...
    "ReferenceSpeed", [10; 20; 30; 40], ...
    "LeftHalfWidth", [1; 2; 3; 4], ...
    "RightHalfWidth", [4; 5; 6; 7]);
end

function removeFolderIfPresent(folderPath)
if isfolder(folderPath)
    rmdir(folderPath, "s");
end
end
