classdef AdaptiveAutocrossQualificationTest < matlab.unittest.TestCase
    %ADAPTIVEAUTOCROSSQUALIFICATIONTEST Tests adaptive full-lap hard gates.

    methods (TestClassSetup)
        function addSimulationScripts(testCase)
            projectRoot = fileparts(fileparts(fileparts( ...
                mfilename("fullpath"))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "scripts", "simulation")));
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testPassesAtMaximumGGVLapTimeRatio(testCase)
            result = AdaptiveAutocrossQualificationTest.makeResult(1.20);
            result.Meta.StoppedAtFinish = false;

            report = validateAdaptiveAutocrossResult( ...
                result, ThrowOnFailure = false);

            testCase.verifyTrue(report.Passed);
            testCase.verifyTrue(report.Checks.GGVLapTimeRatioWithinLimit);
        end

        function testFailsAboveMaximumGGVLapTimeRatio(testCase)
            result = AdaptiveAutocrossQualificationTest.makeResult(1.201);

            report = validateAdaptiveAutocrossResult( ...
                result, ThrowOnFailure = false);

            testCase.verifyFalse(report.Passed);
            testCase.verifyFalse(report.Checks.GGVLapTimeRatioWithinLimit);
            testCase.verifyTrue(any( ...
                report.FailedChecks == "GGVLapTimeRatioWithinLimit"));
        end

        function testOpenTrackDoesNotUseAutocrossRatioGate(testCase)
            result = AdaptiveAutocrossQualificationTest.makeResult(1.30);
            result.Meta.TrackIsClosed = false;

            report = validateAdaptiveAutocrossResult( ...
                result, ThrowOnFailure = false);

            testCase.verifyTrue(report.Passed);
            testCase.verifyTrue(report.Checks.GGVLapTimeRatioWithinLimit);
            testCase.verifyFalse(report.GGVLapTimeRatioRequired);
        end

        function testFailsWhenGGVSpeedCeilingWasNotUsed(testCase)
            result = AdaptiveAutocrossQualificationTest.makeResult(1.10);
            result.Meta.GGVSpeedCeilingUsed = false;

            report = validateAdaptiveAutocrossResult( ...
                result, ThrowOnFailure = false);

            testCase.verifyFalse(report.Passed);
            testCase.verifyFalse(report.Checks.GGVSpeedCeilingUsed);
        end
    end

    methods (Static, Access = private)
        function result = makeResult(lapTimeRatio)
            ggvLapTime = 60.0;
            result = struct( ...
                "Time", (0.0:0.005:1.0).', ...
                "Meta", struct( ...
                    "Valid", true, ...
                    "Completed", true, ...
                    "TrackIsClosed", true, ...
                    "StoppedAtFinish", true, ...
                    "GGVSpeedCeilingUsed", true, ...
                    "VehicleEnvelopeDataValid", true, ...
                    "VehicleEnvelopeWithinBoundary", true), ...
                "Config", struct("Simulation", struct( ...
                    "SolverProfile", "standard", ...
                    "OutputDecimation", 1)), ...
                "Metrics", struct( ...
                    "LapTime", lapTimeRatio * ggvLapTime, ...
                    "GGVLapTime", ggvLapTime, ...
                    "GGVLapTimeRatio", lapTimeRatio, ...
                    "MaximumAllowedGGVLapTimeRatio", 1.20, ...
                    "VehicleEnvelopeViolationCount", 0, ...
                    "MaximumVehicleEnvelopeViolation", 0.0, ...
                    "MaximumBoundaryViolation", 0.0));
        end
    end
end
