classdef AdaptiveRacingLineTest < matlab.unittest.TestCase
    %ADAPTIVERACINGLINETEST Tests width-constrained racing-line planning.

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts( ...
                mfilename("fullpath"))));
            folders = [ ...
                fullfile(projectRoot, "scripts", "simulation"), ...
                fullfile(projectRoot, "scripts", "track")];
            for folder = folders
                testCase.applyFixture( ...
                    matlab.unittest.fixtures.PathFixture(folder));
            end
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testLineIsFiniteShorterAndInsideBounds(testCase)
            track = AdaptiveRacingLineTest.makeCircularTrack();
            driver = AdaptiveRacingLineTest.makeDriver();

            [planned, report] = planAdaptiveRacingLine(track, driver);

            envelope = max(driver.FrontHalfEnvelope, ...
                driver.RearHalfEnvelope);
            leftBound = min(driver.RacingLineMaximumOffset, ...
                track.LeftHalfWidth - envelope - ...
                driver.RacingLineBoundaryReserve);
            rightBound = min(driver.RacingLineMaximumOffset, ...
                track.RightHalfWidth - envelope - ...
                driver.RacingLineBoundaryReserve);
            testCase.verifyTrue(all(isfinite([ ...
                planned.RacingLineX; planned.RacingLineY; ...
                planned.RacingLineHeading; ...
                planned.RacingLineCurvature; ...
                planned.RacingLinePlanningCurvature])));
            testCase.verifyLessThanOrEqual(planned.RacingLineOffset, ...
                leftBound + 1.0e-7);
            testCase.verifyGreaterThanOrEqual(planned.RacingLineOffset, ...
                -rightBound - 1.0e-7);
            offsetRate = abs(diff([planned.RacingLineOffset; ...
                planned.RacingLineOffset(1)])) / track.SampleDistance;
            testCase.verifyLessThanOrEqual(offsetRate, ...
                driver.RacingLineMaximumOffsetRate + 1.0e-7);
            testCase.verifyLessThan(planned.RacingLineLength, track.Length);
            testCase.verifyLessThanOrEqual(report.ConstraintViolation, ...
                1.0e-7);
            testCase.verifyGreaterThan(report.ExitFlag, 0);
        end

        function testPlannerPreservesPhysicalTrackGeometry(testCase)
            track = AdaptiveRacingLineTest.makeCircularTrack();
            driver = AdaptiveRacingLineTest.makeDriver();
            planned = planAdaptiveRacingLine(track, driver);

            testCase.verifyEqual(planned.X, track.X, AbsTol = 0.0);
            testCase.verifyEqual(planned.Y, track.Y, AbsTol = 0.0);
            testCase.verifyEqual(planned.Heading, track.Heading, AbsTol = 0.0);
            testCase.verifyEqual(planned.Curvature, track.Curvature, ...
                AbsTol = 0.0);
        end

        function testHighCurvatureRegionUsesSoftPenalty(testCase)
            track = AdaptiveRacingLineTest.makeCircularTrack();
            track.Curvature(80) = 0.40;
            driver = AdaptiveRacingLineTest.makeDriver();
            driver.RacingLineLockBufferDistance = ...
                2.0 * track.SampleDistance;
            unpenalizedDriver = driver;
            unpenalizedDriver.RacingLineCurvaturePenaltyWeight = 0.0;

            unpenalized = planAdaptiveRacingLine(track, ...
                unpenalizedDriver);
            [planned, report] = planAdaptiveRacingLine(track, driver);

            testCase.verifyLessThan( ...
                abs(planned.RacingLineOffset(80)), ...
                abs(unpenalized.RacingLineOffset(80)));
            testCase.verifyGreaterThan( ...
                abs(planned.RacingLineOffset(80)), 1.0e-10);
            testCase.verifyEqual(report.CurvatureLockedPointCount, 0);
            testCase.verifyGreaterThanOrEqual( ...
                report.PlanningCurvatureLockedPointCount, 1);
            testCase.verifyGreaterThanOrEqual( ...
                report.CurvatureSoftConstrainedPointCount, 5);
        end

        function testOpenTrackDoesNotWrapEndpoints(testCase)
            track = AdaptiveRacingLineTest.makeOpenTrack();
            driver = AdaptiveRacingLineTest.makeDriver();

            [planned, report] = planAdaptiveRacingLine(track, driver);

            sampleCount = numel(track.X);
            testCase.verifyFalse(planned.IsClosed);
            testCase.verifyEqual(planned.RacingLineX([1, end]), ...
                track.X([1, end]), AbsTol = 1.0e-12);
            testCase.verifyEqual(planned.RacingLineY([1, end]), ...
                track.Y([1, end]), AbsTol = 1.0e-12);
            testCase.verifyEqual(planned.RacingLineSampleDistance, ...
                planned.RacingLineLength / (sampleCount - 1), ...
                AbsTol = 1.0e-12);
            testCase.verifyEqual( ...
                planned.RacingLinePlanningSampleDistance, ...
                planned.RacingLinePlanningLength / (sampleCount - 1), ...
                AbsTol = 1.0e-12);
            testCase.verifyTrue(all(isfinite( ...
                planned.RacingLineCurvature)));
            testCase.verifyGreaterThan(report.ExitFlag, 0);
        end
    end

    methods (Static, Access = private)
        function track = makeCircularTrack()
            sampleCount = 160;
            radius = 20.0;
            angle = (0:sampleCount-1).' * 2.0 * pi / sampleCount;
            sampleDistance = 2.0 * pi * radius / sampleCount;
            track = struct( ...
                "X", radius * cos(angle), ...
                "Y", radius * sin(angle), ...
                "Heading", angle + 0.5 * pi, ...
                "Curvature", ones(sampleCount, 1) / radius, ...
                "ReferenceSpeed", zeros(sampleCount, 1), ...
                "LeftHalfWidth", 2.5 * ones(sampleCount, 1), ...
                "RightHalfWidth", 2.5 * ones(sampleCount, 1), ...
                "SampleDistance", sampleDistance, ...
                "Length", sampleCount * sampleDistance, ...
                "IsClosed", true);
        end

        function driver = makeDriver()
            driver = struct( ...
                "CGToFrontAxle", 0.85, ...
                "CGToRearAxle", 0.69, ...
                "FrontHalfEnvelope", 0.80, ...
                "RearHalfEnvelope", 0.80, ...
                "RacingLineBoundaryReserve", 0.15, ...
                "RacingLineMaximumOffset", 0.55, ...
                "RacingLineOffsetVariationWeight", 0.01, ...
                "RacingLineMaximumOffsetRate", 0.03, ...
                "RacingLineLockCurvatureThreshold", 0.20, ...
                "RacingLineLockBufferDistance", 0.0, ...
                "RacingLineCurvaturePenaltyWeight", 0.20, ...
                "RacingLineStartLockDistance", 2.0);
        end

        function track = makeOpenTrack()
            x = linspace(0.0, 60.0, 121).';
            y = 1.5 * sin(x / 8.0);
            track = makePathTrackingParametricTrack( ...
                x, y, 0.5, 4.0, "OpenS", false);
        end
    end
end
