classdef AdaptiveAutocrossDriverStepTest < matlab.unittest.TestCase
    %ADAPTIVEAUTOCROSSDRIVERSTEPTEST Tests dual-path adaptive control.

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts( ...
                mfilename("fullpath"))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "scripts", "path_tracking")));
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testReferencePathChangesSteeringWhenSafe(testCase)
            state = AdaptiveAutocrossDriverStepTest.makeState();
            sensor = AdaptiveAutocrossDriverStepTest.makeSensor(10.0);
            config = AdaptiveAutocrossDriverStepTest.makeConfig();
            physicalTrack = ...
                AdaptiveAutocrossDriverStepTest.makeTrack(false, 0.0);
            referenceTrack = ...
                AdaptiveAutocrossDriverStepTest.makeTrack(true, 0.0);

            physicalCommand = fsaeAdaptiveAutocrossDriverStep( ...
                physicalTrack, sensor, state, config);
            referenceCommand = fsaeAdaptiveAutocrossDriverStep( ...
                referenceTrack, sensor, state, config);

            testCase.verifyGreaterThan( ...
                referenceCommand.SteeringRackAngleRequest, ...
                physicalCommand.SteeringRackAngleRequest + 1.0e-3);
        end

        function testHighCurvatureBlendsBackToPhysicalPath(testCase)
            state = AdaptiveAutocrossDriverStepTest.makeState();
            sensor = AdaptiveAutocrossDriverStepTest.makeSensor(10.0);
            config = AdaptiveAutocrossDriverStepTest.makeConfig();
            physicalTrack = ...
                AdaptiveAutocrossDriverStepTest.makeTrack(false, 0.35);
            referenceTrack = ...
                AdaptiveAutocrossDriverStepTest.makeTrack(true, 0.35);

            physicalCommand = fsaeAdaptiveAutocrossDriverStep( ...
                physicalTrack, sensor, state, config);
            referenceCommand = fsaeAdaptiveAutocrossDriverStep( ...
                referenceTrack, sensor, state, config);

            testCase.verifyEqual( ...
                referenceCommand.SteeringRackAngleRequest, ...
                physicalCommand.SteeringRackAngleRequest, ...
                AbsTol = 1.0e-12);
        end

        function testExitFeedforwardGainRaisesAcceleration(testCase)
            state = AdaptiveAutocrossDriverStepTest.makeState();
            track = AdaptiveAutocrossDriverStepTest.makeTrack(true, 0.0);
            track.ReferenceY(:) = 0.0;
            distance = (0:double(track.SampleCount) - 1).';
            track.ReferenceSpeed = sqrt(100.0 + 8.0 * distance);
            sensor = AdaptiveAutocrossDriverStepTest.makeSensor( ...
                track.ReferenceSpeed(11) - 0.20);
            baseConfig = AdaptiveAutocrossDriverStepTest.makeConfig();
            baseConfig.ExitSpeedFeedforwardGain = ...
                baseConfig.SpeedFeedforwardGain;
            exitConfig = AdaptiveAutocrossDriverStepTest.makeConfig();

            baseCommand = fsaeAdaptiveAutocrossDriverStep( ...
                track, sensor, state, baseConfig);
            exitCommand = fsaeAdaptiveAutocrossDriverStep( ...
                track, sensor, state, exitConfig);

            testCase.verifyGreaterThan( ...
                exitCommand.LongitudinalAccelerationRequest, ...
                baseCommand.LongitudinalAccelerationRequest + 0.10);
        end

        function testOpenTrackPreviewDoesNotWrapToStart(testCase)
            track = AdaptiveAutocrossDriverStepTest.makeTrack(false, 0.0);
            track.Heading(1:10) = 0.5 * pi;
            state = AdaptiveAutocrossDriverStepTest.makeState();
            state.PreviousIndex = double(track.SampleCount);
            sensor = AdaptiveAutocrossDriverStepTest.makeSensor(8.0);
            sensor.PositionX = double(track.SampleCount) - 1.0;
            config = AdaptiveAutocrossDriverStepTest.makeConfig();

            command = fsaeAdaptiveAutocrossDriverStep( ...
                track, sensor, state, config);

            testCase.verifyEqual( ...
                command.SteeringRackAngleRequest, 0.0, ...
                AbsTol = 1.0e-12);
        end

        function testOpenTrackUsesTerminalReferenceSpeed(testCase)
            track = AdaptiveAutocrossDriverStepTest.makeTrack(false, 0.0);
            track.ReferenceSpeed(end) = 2.0;
            state = AdaptiveAutocrossDriverStepTest.makeState();
            state.PreviousIndex = double(track.SampleCount);
            sensor = AdaptiveAutocrossDriverStepTest.makeSensor(8.0);
            sensor.PositionX = double(track.SampleCount) - 1.0;
            config = AdaptiveAutocrossDriverStepTest.makeConfig();

            command = fsaeAdaptiveAutocrossDriverStep( ...
                track, sensor, state, config);

            testCase.verifyLessThan( ...
                command.LongitudinalAccelerationRequest, 0.0);
            testCase.verifyGreaterThan(command.BrakePressureRequest, 0.0);
        end
    end

    methods (Static, Access = private)
        function track = makeTrack(referencePathValid, curvature)
            sampleCount = 80;
            x = (0:sampleCount - 1).';
            zerosVector = zeros(sampleCount, 1);
            curvatureVector = curvature * ones(sampleCount, 1);
            referenceY = zerosVector;
            if referencePathValid
                referenceY = 0.40 * ones(sampleCount, 1);
            end
            track = struct( ...
                "SampleCount", uint32(sampleCount), ...
                "SampleDistance", 1.0, ...
                "TrackLength", double(sampleCount), ...
                "IsClosed", false, ...
                "ReferencePathValid", logical(referencePathValid), ...
                "ReferenceSampleDistance", 1.0, ...
                "X", x, ...
                "Y", zerosVector, ...
                "Heading", zerosVector, ...
                "Curvature", curvatureVector, ...
                "ReferenceX", x, ...
                "ReferenceY", referenceY, ...
                "ReferenceHeading", zerosVector, ...
                "ReferenceCurvature", curvatureVector, ...
                "ReferenceEnvelopeClearance", ...
                    2.0 * ones(sampleCount, 1), ...
                "ReferenceBoundaryCorrectionSign", zerosVector, ...
                "ReferenceSpeed", 15.0 * ones(sampleCount, 1), ...
                "LeftHalfWidth", 3.0 * ones(sampleCount, 1), ...
                "RightHalfWidth", 3.0 * ones(sampleCount, 1));
        end

        function sensor = makeSensor(speed)
            sensor = struct( ...
                "PositionX", 10.0, ...
                "PositionY", 0.0, ...
                "Heading", 0.0, ...
                "LongitudinalSpeed", speed, ...
                "PoseValid", true, ...
                "IMUValid", true, ...
                "AccelY", 0.0);
        end

        function state = makeState()
            state = struct( ...
                "PreviousIndex", 11.0, ...
                "PreviousReferenceIndex", 11.0, ...
                "PreviousSteering", 0.0, ...
                "SpeedIntegrator", 0.0);
        end

        function config = makeConfig()
            config = struct( ...
                "ControlSampleTime", 0.01, ...
                "Wheelbase", 1.54, ...
                "CGToFrontAxle", 0.847, ...
                "CGToRearAxle", 0.693, ...
                "FrontHalfEnvelope", 0.70, ...
                "RearHalfEnvelope", 0.68, ...
                "ProjectionSearchWindow", 15.0, ...
                "MinimumSteeringPreview", 1.0, ...
                "SteeringPreviewTime", 0.18, ...
                "MaximumSteeringPreview", 4.0, ...
                "HeadingGain", 1.8, ...
                "CrossTrackGain", 4.0, ...
                "BoundaryGain", 2.0, ...
                "MinimumSteeringSpeed", 1.0, ...
                "MaximumSteeringAngle", 0.50, ...
                "MaximumSteeringRate", 6.0, ...
                "SteeringWheelRatio", 1.0, ...
                "LateralAccelerationLimit", 13.5, ...
                "MaximumAcceleration", 16.0, ...
                "MaximumDeceleration", 8.0, ...
                "PlanningDeceleration", 6.0, ...
                "MaximumSpeed", 32.0, ...
                "SpeedPreviewDistance", 190.0, ...
                "SpeedPreviewStep", 0.75, ...
                "CurvatureFilterHalfWindow", 2.0, ...
                "CurvatureSafetyFactor", 1.0, ...
                "SpeedSafetyFactor", 1.0, ...
                "SpeedKp", 4.0, ...
                "SpeedKi", 0.20, ...
                "SpeedFeedforwardGain", 0.60, ...
                "ExitSpeedFeedforwardGain", 0.78, ...
                "AntiWindupGain", 1.0, ...
                "ReferencePathCurvatureBlendStart", 0.15, ...
                "ReferencePathCurvatureBlendEnd", 0.30, ...
                "ReferencePathMaximumBlend", 0.25, ...
                "BoundaryPreviewDistance", 6.0, ...
                "BoundaryReserve", 0.50, ...
                "EmergencyBoundaryMargin", 0.25, ...
                "EnableTV", true, ...
                "BrakePressurePerAcceleration", 1.0e4);
        end
    end
end
