function parameters = createQuasiStaticVerificationParameters()
%CREATEQuasiStaticVERIFICATIONPARAMETERS Return synthetic QuasiStatic verification data.
%   These values are for solver and conservation checks only. They are not
%   the vehicle data dictionary and must never be reported as FSAE vehicle
%   performance parameters.

parameters = struct( ...
    "Vehicle", struct( ...
        "Mass", record(250.0, "kg"), "Wheelbase", record(1.60, "m"), ...
        "TrackFront", record(1.20, "m"), "TrackRear", record(1.20, "m"), ...
        "CGHeight", record(0.25, "m"), "CGToFrontAxle", record(0.75, "m"), ...
        "InertiaYaw", record(300.0, "kg*m^2"), ...
        "InertiaPitch", record(300.0, "kg*m^2"), ...
        "InertiaRoll", record(300.0, "kg*m^2"), ...
        "RollStiffnessDistributionFront", record(0.50, "1")), ...
    "Tire", struct( ...
        "EffectiveRadius", record(0.23, "m"), ...
        "UnloadedRadius", record(0.24, "m"), ...
        "WheelInertia", record(1.0, "kg*m^2"), ...
        "LowSpeedEpsilon", record(0.1, "m/s"), ...
        "LongitudinalStiffness", record(10000.0, "N"), ...
        "LateralStiffness", record(12000.0, "N/rad"), ...
        "CamberStiffness", record(0.0, "N/rad"), ...
        "ForceEpsilon", record(1.0, "N")), ...
    "Aero", struct( ...
        "CdA", record(0.70, "m^2"), "ClAFront", record(0.0, "m^2"), ...
        "ClARear", record(0.0, "m^2"), "YawCorrection", record(0.0, "1"), ...
        "YawAngleGrid", record([0.0, 5.0, 10.0], "deg"), ...
        "YawDownforceScale", record([1.0, 1.0, 1.0], "1"), ...
        "SpeedEpsilon", record(0.1, "m/s")), ...
    "Powertrain", struct( ...
        "GearRatio", record(10.0, "1"), "GearEfficiency", record(0.95, "1"), ...
        "MotorTorqueLimit", record(40.0, "N*m"), ...
        "MotorSpeedLimit", record(1200.0, "rad/s"), ...
        "InverterEfficiency", record(0.95, "1")), ...
    "Battery", struct( ...
        "NominalVoltage", record(400.0, "V"), ...
        "Capacity", record(1.0e8, "J"), ...
        "PowerLimitDrive", record(80000.0, "W"), ...
        "PowerLimitRegen", record(20000.0, "W"), ...
        "InitialSOC", record(0.8, "1"), ...
        "SOCLowerLimit", record(0.05, "1"), ...
        "SOCUpperLimit", record(0.95, "1"), ...
        "PowerEpsilon", record(1.0, "W")), ...
    "Vehicle10DOFSuspension", struct( ...
        "WheelRate", [70000.0; 70000.0; 55000.0; 55000.0], ...
        "AdditionalRollStiffness", [1200.0; 900.0]), ...
    "Brake", struct( ...
        "MaxTotalForce", record(10000.0, "N"), ...
        "MaxTorquePerWheel", record([300.0; 300.0; 150.0; 150.0], "N*m")));
end

function output = record(value, unit)
output = struct( ...
    "Value", value, "LowerBound", NaN, "UpperBound", NaN, ...
    "Unit", unit, "Source", "SyntheticVerification", ...
    "Confidence", "Synthetic", "IsMeasured", false, ...
    "IsPlaceholder", false, "Notes", "QuasiStatic solver verification only");
end
