classdef LapReferenceSpeedTest < matlab.unittest.TestCase
    %LAPREFERENCESPEEDTEST Tests for GGV-derived time-domain references.

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
            folders = [ ...
                fullfile(projectRoot, "scripts", "simulation"), ...
                fullfile(projectRoot, "scripts", "lap_time"), ...
                fullfile(projectRoot, "scripts", "track"), ...
                fullfile(projectRoot, "scenarios", "Acceleration"), ...
                fullfile(projectRoot, "scenarios", "Skidpad"), ...
                fullfile(projectRoot, "scenarios", "Autocross"), ...
                fullfile(projectRoot, "scenarios", "Endurance")];
            for folder = folders
                testCase.applyFixture(matlab.unittest.fixtures.PathFixture(folder));
            end
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testScenarioGeometryDoesNotRequireTargetSpeed(testCase)
            cfg = LapReferenceSpeedTest.makeScenarioConfig();

            scenario = createLapScenario(cfg);

            testCase.verifyFalse(isfield(scenario.Track, "TargetSpeed"));
            testCase.verifyEqual(scenario.Track.ReferenceSpeed, ...
                zeros(size(scenario.Track.ReferenceSpeed)), AbsTol = 0.0);
            testCase.verifySubstring(scenario.ReferenceSpeedSource, ...
                "applyGGVReferenceSpeed");
        end

        function testOpenTrackStartsAtInitialSpeedAndAccelerates(testCase)
            scenario = LapReferenceSpeedTest.makeScenario(false, 1);
            scenario.Track.TargetSpeed = 8.0;
            cfg = LapReferenceSpeedTest.makePlannerConfig(0.90);
            ggv = LapReferenceSpeedTest.makeSyntheticGGV();

            [updated, plan] = applyGGVReferenceSpeed( ...
                scenario, struct(), cfg, GGV = ggv);

            testCase.verifyFalse(isfield(updated.Track, "TargetSpeed"));
            testCase.verifyEqual(updated.Track.ReferenceSpeed(1), ...
                scenario.InitialState.Ux, AbsTol = 1.0e-12);
            testCase.verifyGreaterThan(updated.Track.ReferenceSpeed(end), ...
                updated.Track.ReferenceSpeed(1));
            testCase.verifyEqual(plan.Metadata.BoundaryMode, "open_track");
        end

        function testOpenTrackRacingLineFeedsGGVPlanner(testCase)
            scenario = createPathTrackingAccelerationScenario( ...
                TargetSpeed = Inf, SampleDistance = 0.5);
            driver = LapReferenceSpeedTest.makeRacingLineDriver();
            plannedTrack = planAdaptiveRacingLine( ...
                scenario.Track, driver);
            scenario.Track = plannedTrack;
            cfg = LapReferenceSpeedTest.makePlannerConfig(0.90);
            ggv = LapReferenceSpeedTest.makeSyntheticGGV();

            [updated, plan] = applyGGVReferenceSpeed( ...
                scenario, struct(), cfg, GGV = ggv);

            testCase.verifyEqual(plan.Metadata.BoundaryMode, "open_track");
            testCase.verifyTrue(plan.Metadata.RacingLineUsed);
            testCase.verifyEqual(plan.Metadata.PlanningTrackLength, ...
                plannedTrack.RacingLinePlanningLength, ...
                AbsTol = 1.0e-12);
            testCase.verifyEqual(updated.Track.ReferenceSpeed(1), ...
                scenario.InitialState.Ux, AbsTol = 1.0e-12);
            testCase.verifyGreaterThan(updated.Track.ReferenceSpeed(end), ...
                updated.Track.ReferenceSpeed(1));
        end

        function testCurvatureProducesVaryingClosedTrackReference(testCase)
            scenario = LapReferenceSpeedTest.makeScenario(true, 2);
            scenario.Track.Curvature = [0.0; 0.02; 0.08; 0.16; ...
                0.08; 0.02; 0.0; 0.0];
            cfg = LapReferenceSpeedTest.makePlannerConfig(0.90);
            ggv = LapReferenceSpeedTest.makeSyntheticGGV();

            [updated, plan] = applyGGVReferenceSpeed( ...
                scenario, struct(), cfg, GGV = ggv);

            testCase.verifySize(updated.Track.ReferenceSpeed, [8, 1]);
            testCase.verifyGreaterThan( ...
                max(updated.Track.ReferenceSpeed) - ...
                min(updated.Track.ReferenceSpeed), 0.1);
            testCase.verifyLessThan( ...
                plan.Profile.CurvatureSpeedLimit(4), ...
                plan.Profile.CurvatureSpeedLimit(1));
            testCase.verifyEqual(plan.Metadata.BoundaryMode, ...
                "periodic_closed_track");
        end

        function testConstraintScaleReducesCurveSpeed(testCase)
            scenario = LapReferenceSpeedTest.makeScenario(true, 2);
            scenario.Track.Curvature(:) = 0.10;
            fullCfg = LapReferenceSpeedTest.makePlannerConfig(1.00);
            marginCfg = LapReferenceSpeedTest.makePlannerConfig(0.50);
            ggv = LapReferenceSpeedTest.makeSyntheticGGV();

            full = applyGGVReferenceSpeed( ...
                scenario, struct(), fullCfg, GGV = ggv);
            margin = applyGGVReferenceSpeed( ...
                scenario, struct(), marginCfg, GGV = ggv);

            testCase.verifyLessThan(max(margin.Track.ReferenceSpeed), ...
                max(full.Track.ReferenceSpeed));
            testCase.verifyEqual(max(margin.Track.ReferenceSpeed), ...
                sqrt(20.0), AbsTol = 1.0e-4);
        end

        function testDriverEnvelopeLimitsReferenceProfile(testCase)
            scenario = LapReferenceSpeedTest.makeScenario(false, 1);
            scenario.Track.Curvature = [0; 0; 0; 0; 0; 0.05; 0.15; 0.25];
            cfg = LapReferenceSpeedTest.makePlannerConfig(1.00);
            cfg.Driver = struct( ...
                "MaximumSpeed", 12.0, ...
                "MaximumAcceleration", 2.0, ...
                "MaximumDeceleration", 4.0, ...
                "PlanningDeceleration", 3.0, ...
                "LateralAccelerationLimit", 4.0, ...
                "SpeedSafetyFactor", 0.90);
            ggv = LapReferenceSpeedTest.makeAggressiveGGV();

            [updated, plan] = applyGGVReferenceSpeed( ...
                scenario, struct(), cfg, GGV = ggv);

            speedSquaredGradient = diff(updated.Track.ReferenceSpeed.^2) / ...
                (2 * scenario.Track.SampleDistance);
            testCase.verifyLessThanOrEqual( ...
                max(updated.Track.ReferenceSpeed), 10.8 + 1.0e-12);
            testCase.verifyLessThanOrEqual( ...
                max(speedSquaredGradient), 2.0 + 1.0e-10);
            testCase.verifyLessThanOrEqual( ...
                max(-speedSquaredGradient), 3.0 + 1.0e-10);
            testCase.verifyLessThanOrEqual( ...
                max(abs(plan.Profile.LateralAcceleration)), ...
                4.0 * 0.9^2 + 1.0e-4);
            testCase.verifyEqual( ...
                plan.Metadata.DriverPlanningDeceleration, 3.0, ...
                AbsTol = 1.0e-12);
            testCase.verifyEqual( ...
                plan.Metadata.DriverSpeedSafetyFactor, 0.9, ...
                AbsTol = 1.0e-12);
        end

        function testReferenceLimitsOverrideAdaptiveSafetyMargin(testCase)
            scenario = LapReferenceSpeedTest.makeScenario(false, 1);
            cfg = LapReferenceSpeedTest.makePlannerConfig(1.00);
            cfg.SpeedPlanner.ReferenceMaximumSpeed = 14.0;
            cfg.SpeedPlanner.ReferenceMaximumAcceleration = 3.0;
            cfg.SpeedPlanner.ReferencePlanningDeceleration = 3.5;
            cfg.SpeedPlanner.ReferenceLateralAccelerationLimit = 5.0;
            cfg.SpeedPlanner.ReferenceSpeedSafetyFactor = 1.0;
            cfg.Driver = struct( ...
                "MaximumSpeed", 12.0, ...
                "MaximumAcceleration", 2.0, ...
                "MaximumDeceleration", 4.0, ...
                "PlanningDeceleration", 2.0, ...
                "LateralAccelerationLimit", 4.0, ...
                "SpeedSafetyFactor", 0.90);
            ggv = LapReferenceSpeedTest.makeAggressiveGGV();

            [updated, plan] = applyGGVReferenceSpeed( ...
                scenario, struct(), cfg, GGV = ggv);

            testCase.verifyGreaterThan(max(updated.Track.ReferenceSpeed), 10.8);
            testCase.verifyLessThanOrEqual( ...
                max(updated.Track.ReferenceSpeed), 12.0 + 1.0e-12);
            testCase.verifyEqual(plan.Metadata.ReferenceLimitSource, ...
                "SpeedPlanner.Reference");
            testCase.verifyEqual( ...
                plan.Metadata.DriverPlanningDeceleration, 3.5, ...
                AbsTol = 1.0e-12);
            testCase.verifyEqual( ...
                plan.Metadata.DriverLateralAccelerationLimit, 5.0, ...
                AbsTol = 1.0e-12);
            testCase.verifyEqual( ...
                plan.Metadata.DriverSpeedSafetyFactor, 1.0, ...
                AbsTol = 1.0e-12);
        end

        function testRacingLineGeometryDrivesPlanningOnly(testCase)
            scenario = LapReferenceSpeedTest.makeScenario(true, 2);
            scenario.Track.Curvature(:) = 0.02;
            scenario.Track.RacingLineCurvature = ...
                0.08 * ones(size(scenario.Track.Curvature));
            scenario.Track.RacingLineSampleDistance = 4.5;
            scenario.Track.RacingLineLength = 36.0;
            cfg = LapReferenceSpeedTest.makePlannerConfig(1.00);
            ggv = LapReferenceSpeedTest.makeSyntheticGGV();

            [updated, plan] = applyGGVReferenceSpeed( ...
                scenario, struct(), cfg, GGV = ggv);

            testCase.verifyTrue(plan.Metadata.RacingLineUsed);
            testCase.verifyEqual(plan.Metadata.PlanningTrackLength, ...
                scenario.Track.RacingLineLength, AbsTol = 0.0);
            testCase.verifyEqual(updated.Track.Curvature, ...
                scenario.Track.Curvature, AbsTol = 0.0);
            testCase.verifyLessThan(max(updated.Track.ReferenceSpeed), 8.0);
        end
    end

    methods (Static, Access = private)
        function cfg = makeScenarioConfig()
            cfg = struct( ...
                "Track", struct( ...
                    "Name", "acceleration", ...
                    "SampleDistance", 1.0, ...
                    "NumberOfLaps", 1, ...
                    "ImagePath", ""), ...
                "Vehicle", struct("TireModel", "mf62"));
        end

        function cfg = makePlannerConfig(constraintScale)
            cfg = struct( ...
                "Vehicle", struct( ...
                    "TireModel", "mf62", "DynamicsModel", "7DOF"), ...
                "SpeedPlanner", struct( ...
                    "ConstraintScale", constraintScale, ...
                    "PassCount", 6));
        end

        function scenario = makeScenario(isClosed, numberOfLaps)
            sampleCount = 8;
            track = struct( ...
                "Curvature", zeros(sampleCount, 1), ...
                "ReferenceSpeed", 8.0 * ones(sampleCount, 1), ...
                "SampleDistance", 5.0, ...
                "IsClosed", logical(isClosed));
            scenario = struct( ...
                "Track", track, ...
                "InitialState", struct("Ux", 0.2), ...
                "NumberOfLaps", numberOfLaps, ...
                "ReferenceSpeedSource", "test input");
        end

        function ggv = makeSyntheticGGV()
            ggv = struct( ...
                "Speed", [0.0; 20.0], ...
                "AyPositive", [4.0; 4.0], ...
                "AyNegative", [4.0; 4.0], ...
                "LateralFraction", [-1.0; 0.0; 1.0], ...
                "AxMax", [0.0, 2.0, 0.0; 0.0, 2.0, 0.0], ...
                "AxMin", [0.0, -3.0, 0.0; 0.0, -3.0, 0.0], ...
                "Diagnostics", struct("InvalidSpeedCount", 0));
        end


        function driver = makeRacingLineDriver()
            driver = struct( ...
                "CGToFrontAxle", 0.85, ...
                "CGToRearAxle", 0.69, ...
                "FrontHalfEnvelope", 0.70, ...
                "RearHalfEnvelope", 0.68, ...
                "RacingLineBoundaryReserve", 0.60, ...
                "RacingLineMaximumOffset", 0.40, ...
                "RacingLineOffsetVariationWeight", 0.05, ...
                "RacingLineMaximumOffsetRate", 0.02, ...
                "RacingLineLockCurvatureThreshold", 0.25, ...
                "RacingLineLockBufferDistance", 15.0, ...
                "RacingLineCurvaturePenaltyWeight", 0.02, ...
                "RacingLineStartLockDistance", 15.0);
        end


        function ggv = makeAggressiveGGV()
            ggv = struct( ...
                "Speed", [0.0; 20.0], ...
                "AyPositive", [20.0; 20.0], ...
                "AyNegative", [20.0; 20.0], ...
                "LateralFraction", [-1.0; 0.0; 1.0], ...
                "AxMax", [10.0, 10.0, 10.0; 10.0, 10.0, 10.0], ...
                "AxMin", [-10.0, -10.0, -10.0; -10.0, -10.0, -10.0], ...
                "Diagnostics", struct("InvalidSpeedCount", 0));
        end
    end
end
