classdef ReferenceSpeedQualificationTest < matlab.unittest.TestCase
    %REFERENCESPEEDQUALIFICATIONTEST Tests full-lap qualification gates.

    methods (TestClassSetup)
        function addSimulationScripts(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "scripts", "simulation")));
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testBoundaryCompliantResultPasses(testCase)
            result = ReferenceSpeedQualificationTest.makeResult(0.0, 0);

            report = validateReferenceSpeedResult( ...
                result, ThrowOnFailure = false);

            testCase.verifyTrue(report.Passed);
            testCase.verifyEmpty(report.FailedChecks);
        end

        function testVehicleEnvelopeViolationFails(testCase)
            result = ReferenceSpeedQualificationTest.makeResult(0.05, 10);

            report = validateReferenceSpeedResult( ...
                result, ThrowOnFailure = false);

            testCase.verifyFalse(report.Passed);
            testCase.verifyTrue(any(report.FailedChecks == ...
                "EnvelopeWithinBoundary"));
            testCase.verifyTrue(any(report.FailedChecks == ...
                "ZeroEnvelopeViolation"));
        end
    end

    methods (Static, Access = private)
        function result = makeResult(maximumViolation, violationCount)
            result = struct( ...
                "Time", (0:0.005:1)', ...
                "Config", struct("Simulation", struct( ...
                    "SolverProfile", "standard", ...
                    "OutputDecimation", 1)), ...
                "Metrics", struct( ...
                    "LapTime", 1.0, ...
                    "VehicleEnvelopeViolationCount", violationCount, ...
                    "MaximumVehicleEnvelopeViolation", maximumViolation, ...
                    "MaximumBoundaryViolation", maximumViolation), ...
                "Meta", struct( ...
                    "Valid", true, ...
                    "Completed", true, ...
                    "StoppedAtFinish", true, ...
                    "ReferenceSpeedUsed", true, ...
                    "VehicleEnvelopeDataValid", true, ...
                    "VehicleEnvelopeWithinBoundary", ...
                        maximumViolation <= 1.0e-9));
        end
    end
end
