classdef ReferenceDriverConfigurationTest < matlab.unittest.TestCase
    %REFERENCEDRIVERCONFIGURATIONTEST Tests SimulationInput parameter wiring.

    methods (TestClassSetup)
        function addSimulationScripts(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "scripts", "simulation")));
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testPathTrackingParametersAreMapped(testCase)
            in = Simulink.SimulationInput("FSAE_TorqueVectoring_ClosedLoop");
            driver = ReferenceDriverConfigurationTest.makeDriver();
            scenario = struct("Track", struct("SampleDistance", 0.5));

            [in, applied] = applyReferenceDriverConfiguration( ...
                in, driver, scenario, "FSAE_TorqueVectoring_ClosedLoop");

            testCase.verifyEqual(applied.PathTrackingDriver.PathTrackingSpeedKp, 3.0);
            testCase.verifyEqual(applied.PathTrackingDriver.PathTrackingSpeedKi, 0.2);
            testCase.verifyEqual( ...
                applied.PathTrackingDriver.PathTrackingAntiWindupGain, 1.0);
            testCase.verifyEqual( ...
                ReferenceDriverConfigurationTest.variableValue( ...
                    in, "PathTrackingMaximumAcceleration", "PathTrackingDriver"), ...
                6.25);
        end

        function testTopModelPreviewAndProjectionAreMapped(testCase)
            in = Simulink.SimulationInput("FSAE_TorqueVectoring_ClosedLoop");
            driver = ReferenceDriverConfigurationTest.makeDriver();
            scenario = struct("Track", struct("SampleDistance", 0.5));

            [~, applied] = applyReferenceDriverConfiguration( ...
                in, driver, scenario, "FSAE_TorqueVectoring_ClosedLoop");

            testCase.verifyEqual( ...
                applied.TopModel.PathTrackingProjectionSearchWindow, 30);
            testCase.verifyEqual(applied.TopModel.PathTrackingMinLookahead, 1.0);
            testCase.verifyEqual( ...
                applied.TopModel.PathTrackingLookaheadTime, 4.0 / 22.5, ...
                AbsTol = 1.0e-12);
        end

        function testDriverAndControllerLimitsAgree(testCase)
            in = Simulink.SimulationInput("FSAE_TorqueVectoring_ClosedLoop");
            driver = ReferenceDriverConfigurationTest.makeDriver();
            scenario = struct("Track", struct("SampleDistance", 0.5));

            in = applyReferenceDriverConfiguration( ...
                in, driver, scenario, "FSAE_TorqueVectoring_ClosedLoop");

            testCase.verifyEqual( ...
                ReferenceDriverConfigurationTest.variableValue( ...
                    in, "PathTrackingMaximumDeceleration", "PathTrackingDriver"), ...
                ReferenceDriverConfigurationTest.variableValue( ...
                    in, "TorqueVectoringMaximumDeceleration", ""));
            testCase.verifyEqual( ...
                ReferenceDriverConfigurationTest.variableValue( ...
                    in, "PathTrackingMaximumAcceleration", "PathTrackingDriver"), ...
                ReferenceDriverConfigurationTest.variableValue( ...
                    in, "TorqueVectoringMaximumAcceleration", ""));
        end
    end

    methods (Static, Access = private)
        function driver = makeDriver()
            driver = struct( ...
                "HeadingGain", 1.8, "CrossTrackGain", 4.0, ...
                "BoundaryGain", 2.0, "MaximumSteeringRate", 6.0, ...
                "MaximumSteeringAngle", 0.5, ...
                "MinimumSteeringSpeed", 1.0, ...
                "ProjectionSearchDistance", 15.0, ...
                "MinimumSteeringPreview", 1.0, ...
                "SteeringPreviewTime", 0.18, ...
                "MaximumSteeringPreview", 4.0, ...
                "MaximumSpeed", 22.5, ...
                "MaximumAcceleration", 6.25, ...
                "MaximumDeceleration", 8.0, ...
                "SpeedKp", 3.0, "SpeedKi", 0.2, ...
                "AntiWindupGain", 1.0, "BoundaryReserve", 0.25, ...
                "EmergencyBoundaryMargin", 0.10);
        end

        function value = variableValue(in, name, workspace)
            if strlength(workspace) == 0
                workspace = "global-workspace";
            end
            names = string({in.Variables.Name});
            workspaces = string({in.Variables.Workspace});
            index = find(names == name & workspaces == workspace, 1, "last");
            assert(~isempty(index), "FSAE:Test:MissingSimulationVariable", ...
                "Missing SimulationInput variable %s in workspace %s.", ...
                name, workspace);
            value = in.Variables(index).Value;
        end
    end
end
