function report = runQuasiStaticVerification(options)
%RUNQuasiStaticVERIFICATION Execute the QuasiStatic solver-chain verification baseline.

arguments
    options.SaveSummary (1, 1) logical = true
end
%   This script uses synthetic vehicle parameters plus the selected TireModel TTC
%   tire profile. It verifies conservation, GGV generation, speed planning,
%   parameter-sweep bookkeeping and time-domain cross-check plumbing. It is
%   not a vehicle-performance report.

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "ggv"));
addpath(fullfile(projectRoot, "scripts", "lap_time"));
addpath(fullfile(projectRoot, "scripts", "tire"));
addpath(fullfile(projectRoot, "scripts", "track"));

parameters = createQuasiStaticVerificationParameters();
profile = getSelectedTireProfile();
config = createQuasiStaticConfiguration(parameters, TireProfile = profile, ...
    TireModel = "MF62", AllocationMode = "LP", EnvelopePointCount = 16, ...
    KappaGrid = linspace(-0.40, 0.40, 11), ...
    AlphaGrid = linspace(-0.35, 0.35, 11));

point = solveSteadyState(config, 10.0, [0.0, 2.0]);
assert(point.Feasible, "FSAE:QuasiStatic:VerificationPoint", ...
    "The LP steady-state verification point is infeasible: %s", point.FailureReason);
assert(max(abs(point.EquilibriumResidual)) < 1.0e-6, ...
    "FSAE:QuasiStatic:VerificationBalance", "Steady-state residual is too large.");
assert(abs(sum(point.NormalLoad) - ...
    (config.Vehicle.Mass * config.Solver.Gravity + point.Aero.DownforceFront + ...
    point.Aero.DownforceRear)) < 1.0e-6, ...
    "FSAE:QuasiStatic:NormalLoadConservation", "Normal-load conservation failed.");
expectedWheelX = [config.Vehicle.CGToFrontAxle; ...
    config.Vehicle.CGToFrontAxle; -config.Vehicle.CGToRearAxle; ...
    -config.Vehicle.CGToRearAxle];
assert(max(abs(point.WheelPosition(:, 1) - expectedWheelX)) < 1.0e-12, ...
    "FSAE:QuasiStatic:WheelPosition", ...
    "Front/rear axle longitudinal moment arms do not match the CG geometry.");

ggv = generateGGV(config, SpeedGrid = [0, 10], LateralPointCount = 3, ...
    MaxLateralAcceleration = 12.0, MaxLongitudinalAcceleration = 15.0, ...
    MaxBisectionIterations = 4, AllocationMode = "Fast");
assert(all(isfinite(ggv.AyPositive)) && all(isfinite(ggv.AyNegative)), ...
    "FSAE:QuasiStatic:GGVFinite", "GGV lateral limits contain non-finite values.");
assert(any(isfinite(ggv.AxMax), "all") && any(isfinite(ggv.AxMin), "all"), ...
    "FSAE:QuasiStatic:GGVBoundary", "GGV longitudinal boundaries were not found.");

angle = linspace(0.0, 2.0 * pi, 121)';
track = makePathTrackingParametricTrack(10.0 * cos(angle), 10.0 * sin(angle), ...
    0.5, 3.0, "QuasiStaticVerificationCircle", true);
speedProfile = calculateSpeedProfile(track, ggv, PassCount = 2);
lap = calculateLapTime(speedProfile, track);
assert(isfinite(lap.LapTime) && lap.LapTime > 0.0, ...
    "FSAE:QuasiStatic:LapTime", "Lap-time integration did not produce a positive finite result.");
openX = (0.0:1.0:20.0)';
openTrack = makePathTrackingParametricTrack(openX, zeros(size(openX)), ...
    1.0, 3.0, "QuasiStaticVerificationOpenTrack", false);
openProfile = calculateSpeedProfile(openTrack, ggv, ...
    InitialSpeed = 0.0, FinalSpeed = 0.0, PassCount = 2);
openLap = calculateLapTime(openProfile, openTrack);
assert(abs(openProfile.Speed(1)) < 1.0e-12 && ...
    abs(openProfile.Speed(end)) < 1.0e-12, ...
    "FSAE:QuasiStatic:OpenTrackBoundarySpeed", ...
    "Open-track initial/final speed constraints were not preserved.");
assert(abs(openProfile.TrackLength - openLap.Distance) < 1.0e-12, ...
    "FSAE:QuasiStatic:OpenTrackDistance", ...
    "Open-track profile length and integrated distance are inconsistent.");

timeDomain = struct( ...
    "Time", speedProfile.Time(1:numel(speedProfile.Speed)), ...
    "Vehicle", struct( ...
        "Ux", speedProfile.Speed, ...
        "Ax", zeros(size(speedProfile.Speed)), ...
        "Ay", speedProfile.LateralAcceleration));
crossCheck = crossValidateQuasiStaticWithTimeDomain(ggv, timeDomain, Tolerance = 0.5);
assert(crossCheck.Pass, "FSAE:QuasiStatic:CrossValidation", ...
    "Synthetic time-domain cross-check exceeded the diagnostic tolerance.");
lateralOutside = timeDomain;
lateralOutside.Vehicle.Ay(:) = 2.0 * max(ggv.AyPositive);
lateralViolationCheck = crossValidateQuasiStaticWithTimeDomain( ...
    ggv, lateralOutside, Tolerance = 0.5);
assert(~lateralViolationCheck.Pass && ...
    lateralViolationCheck.MaxLateralUpperViolation > 0.0, ...
    "FSAE:QuasiStatic:LateralCrossValidation", ...
    "A time-domain sample outside the lateral GGV boundary was not rejected.");

sweep = createQuasiStaticParameterSweep(CdA = [0.65, 0.70], ...
    ClAFront = 0.0, ClARear = 0.0, ...
    RollStiffnessDistributionFront = 0.50, GearEfficiency = 0.95);
sweepOptions = struct( ...
    "SpeedGrid", [0, 10], "LateralPointCount", 3, ...
    "MaxLateralAcceleration", 10.0, ...
    "MaxLongitudinalAcceleration", 12.0, ...
    "MaxBisectionIterations", 3);
sweepResults = runQuasiStaticParameterSweep(config, sweep, ...
    GenerateGGVOptions = sweepOptions);
assert(all([sweepResults.Success]), "FSAE:QuasiStatic:Sweep", ...
    "At least one QuasiStatic parameter-sweep combination failed.");
requiredMetadata = ["MATLABVersion", "MATLABRelease", "GitCommit", ...
    "GitDirty", "Scenario", "GeneratedAtUTC"];
assert(all(isfield(sweepResults(1).RunMetadata, requiredMetadata)), ...
    "FSAE:QuasiStatic:SweepMetadata", ...
    "QuasiStatic sweep results do not contain the required traceability metadata.");
assert(all(arrayfun(@(item) height(item.ParameterTrace) == height(sweep), ...
    sweepResults)), "FSAE:QuasiStatic:SweepParameterTrace", ...
    "QuasiStatic sweep results do not retain the parameter unit/source trace.");

report = struct( ...
    "SteadyStatePoint", point, "GGV", ggv, ...
    "SpeedProfile", speedProfile, "LapTime", lap, ...
    "OpenTrackProfile", openProfile, ...
    "CrossValidation", crossCheck, "Sweep", sweepResults, ...
    "LateralViolationCheck", lateralViolationCheck, ...
    "TireProfileName", profile.Name, ...
    "SyntheticOnly", true);
if options.SaveSummary
    resultFolder = fullfile(projectRoot, "tests", "quasi_static", "results");
    if ~isfolder(resultFolder)
        mkdir(resultFolder);
    end
    save(fullfile(resultFolder, "QuasiStaticVerificationSummary.mat"), ...
        "report", "-v7.3");
end
fprintf("QuasiStatic verification passed: geometry, LP point, GGV, open/closed lap-time, " + ...
    "cross-check boundaries and %d sweep cases.\n", numel(sweepResults));
end
