function report = runQuasiStaticTimeDomainCrossValidation(options)
%RUNQuasiStaticTIMEDOMAINCROSSVALIDATION Run the PathTracking-to-QuasiStatic integration comparison.
%   This slow integration entry runs an actual PathTracking closed-loop simulation,
%   normalizes its logged signals, and compares both longitudinal and
%   lateral accelerations with an QuasiStatic GGV surface. Default parameters remain
%   explicitly synthetic and do not represent vehicle performance.

arguments
    options.Parameters (1, 1) struct = struct()
    options.Scenario (1, 1) struct = struct()
    options.Tolerance (1, 1) double {mustBeNonnegative} = 0.5
    options.SpeedGrid (1, :) double = [0.0, 5.0, 10.0, 15.0]
    options.MaxBisectionIterations (1, 1) double ...
        {mustBeInteger, mustBePositive} = 8
    options.SaveSummary (1, 1) logical = true
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "ggv"));
addpath(fullfile(projectRoot, "scripts", "tire"));
addpath(fullfile(projectRoot, "scripts", "simulation"));
addpath(fullfile(projectRoot, "scripts", "track"));
addpath(fullfile(projectRoot, "scenarios", "Acceleration"));

if isempty(fieldnames(options.Parameters))
    parameters = createQuasiStaticVerificationParameters();
else
    parameters = options.Parameters;
end
if isempty(fieldnames(options.Scenario))
    scenario = createPathTrackingAccelerationScenario(TargetSpeed = 10.0);
else
    scenario = options.Scenario;
end

tireProfile = getSelectedTireProfile();
config = createQuasiStaticConfiguration(parameters, TireProfile = tireProfile, ...
    TireModel = "MF62", AllocationMode = "LP", EnvelopePointCount = 16, ...
    KappaGrid = linspace(-0.40, 0.40, 11), ...
    AlphaGrid = linspace(-0.35, 0.35, 11));
ggv = generateGGV(config, SpeedGrid = options.SpeedGrid, ...
    LateralPointCount = 3, MaxLateralAcceleration = 12.0, ...
    MaxLongitudinalAcceleration = 15.0, ...
    MaxBisectionIterations = options.MaxBisectionIterations, ...
    AllocationMode = "Fast");

in = createPathTrackingSimulationInput(scenario, parameters);
out = sim(in);
timeDomain = collectOpenLoopResults(out, struct("ScenarioID", scenario.ID));
comparison = crossValidateQuasiStaticWithTimeDomain( ...
    ggv, timeDomain, Tolerance = options.Tolerance);

report = struct( ...
    "Pass", comparison.Pass, ...
    "Comparison", comparison, ...
    "TimeDomain", timeDomain, ...
    "GGV", ggv, ...
    "Scenario", scenario, ...
    "TireProfileName", tireProfile.Name, ...
    "SyntheticOnly", true, ...
    "Metadata", struct( ...
        "Method", "Actual PathTracking SimulationOutput against QuasiStatic GGV", ...
        "SampleCount", numel(comparison.Time), ...
        "MissingSignalCount", numel(timeDomain.Meta.MissingSignals), ...
        "NonFiniteSignalCount", numel(timeDomain.Meta.NonFiniteSignals), ...
        "IsPerformanceClaim", false));

if options.SaveSummary
    resultFolder = fullfile(projectRoot, "tests", "quasi_static", "results");
    if ~isfolder(resultFolder)
        mkdir(resultFolder);
    end
    save(fullfile(resultFolder, ...
        "QuasiStaticTimeDomainCrossValidationSummary.mat"), "report", "-v7.3");
end

fprintf("PathTracking-to-QuasiStatic cross-validation: pass=%d, samples=%d, " + ...
    "max longitudinal/lateral violation=%.6g/%.6g m/s^2.\n", ...
    report.Pass, report.Metadata.SampleCount, ...
    max(comparison.MaxUpperViolation, comparison.MaxLowerViolation), ...
    max(comparison.MaxLateralUpperViolation, ...
    comparison.MaxLateralLowerViolation));
end
