function inventory = auditTTCData(ttcRoot)
%AUDITTTCDATA Inventory TTC MATLAB SI runs and audit required channels.

arguments
    ttcRoot (1, 1) string
end

assert(isfolder(ttcRoot), "FSAE:TireModel:MissingTTCRoot", ...
    "TTC root does not exist: %s", ttcRoot);
files = dir(fullfile(ttcRoot, "**", "B*run*.mat"));
assert(~isempty(files), "FSAE:TireModel:NoTTCRuns", ...
    "No TTC MATLAB SI run files were found below %s.", ttcRoot);

rows = repmat(emptyInventoryRow(), numel(files), 1);
for index = 1:numel(files)
    filePath = string(fullfile(files(index).folder, files(index).name));
    loaded = load(filePath, "tireid", "testid", "source", "RUN", ...
        "ET", "FZ", "P", "SA", "SL", "IA", "FX", "FY");
    fields = string({whos("-file", filePath).name});
    required = [ ...
        "ET", "V", "N", "SA", "IA", "RL", "RE", "P", "FX", "FY", ...
        "FZ", "MX", "MZ", "NFX", "NFY", "RST", "TSTI", "TSTC", ...
        "TSTO", "AMBTMP", "SR", "SL", "RUN", "channel", "source", ...
        "testid", "tireid"];
    missing = setdiff(required, fields);
    numeric = [loaded.ET(:); loaded.FZ(:); loaded.P(:); ...
        loaded.SA(:); loaded.SL(:); loaded.IA(:); loaded.FX(:); ...
        loaded.FY(:)];
    rows(index) = struct( ...
        FilePath = filePath, ...
        Round = inferRound(filePath), ...
        RunNumber = double(mode(loaded.RUN)), ...
        TireID = strtrim(string(loaded.tireid)), ...
        TestType = strtrim(string(loaded.testid)), ...
        RowCount = numel(loaded.ET), ...
        FileBytes = double(files(index).bytes), ...
        MissingChannels = strjoin(missing, ";"), ...
        NonfiniteRequired = nnz(~isfinite(numeric)), ...
        NormalLoadMinN = min(-loaded.FZ, [], "omitnan"), ...
        NormalLoadMaxN = max(-loaded.FZ, [], "omitnan"), ...
        PressureMinPa = min(loaded.P, [], "omitnan") * 1000.0, ...
        PressureMaxPa = max(loaded.P, [], "omitnan") * 1000.0, ...
        SlipAngleMinRad = deg2rad(min(loaded.SA, [], "omitnan")), ...
        SlipAngleMaxRad = deg2rad(max(loaded.SA, [], "omitnan")), ...
        SlipRatioMin = min(loaded.SL, [], "omitnan"), ...
        SlipRatioMax = max(loaded.SL, [], "omitnan"), ...
        CamberMinRad = deg2rad(min(loaded.IA, [], "omitnan")), ...
        CamberMaxRad = deg2rad(max(loaded.IA, [], "omitnan")), ...
        Source = strtrim(string(loaded.source)));
end
inventory = struct2table(rows);
inventory = sortrows(inventory, ["Round", "RunNumber"]);
end

function row = emptyInventoryRow()
row = struct( ...
    FilePath = "", Round = NaN, RunNumber = NaN, TireID = "", ...
    TestType = "", RowCount = 0, FileBytes = 0, ...
    MissingChannels = "", NonfiniteRequired = 0, ...
    NormalLoadMinN = NaN, NormalLoadMaxN = NaN, ...
    PressureMinPa = NaN, PressureMaxPa = NaN, ...
    SlipAngleMinRad = NaN, SlipAngleMaxRad = NaN, ...
    SlipRatioMin = NaN, SlipRatioMax = NaN, ...
    CamberMinRad = NaN, CamberMaxRad = NaN, Source = "");
end

function roundNumber = inferRound(filePath)
token = regexp(filePath, "round_(\d+)", "tokens", "once");
assert(~isempty(token), "FSAE:TireModel:RoundName", ...
    "Could not infer TTC round from %s.", filePath);
roundNumber = str2double(token{1});
end
