function map = buildTTCReferenceMap(data, options)
%BUILDTTCREFERENCEMAP Build a compact local-interpolation TTC reference map.

arguments
    data table
    options.MaximumPoints (1, 1) double {mustBeInteger, mustBePositive} = 3500
end

assert(height(data) > 100, "FSAE:TireModel:MapData", ...
    "At least 100 accepted TTC rows are required to build a map.");
data = augmentSymmetry(data);
quantized = [ ...
    round(data.SlipRatio / 0.005), ...
    round(data.SlipAngleRad / deg2rad(0.25)), ...
    round(data.CamberAngleRad / deg2rad(0.25)), ...
    round(data.NormalLoadN / 25.0), ...
    round(data.PressurePa / 2000.0)];
[group, ~, ~, ~, ~, ~] = findgroups( ...
    quantized(:, 1), quantized(:, 2), quantized(:, 3), ...
    quantized(:, 4), quantized(:, 5));
points = splitapply(@(a, b, c, d, e) ...
    [mean(a), mean(b), mean(c), mean(d), mean(e)], ...
    data.SlipRatio, data.SlipAngleRad, data.CamberAngleRad, ...
    data.NormalLoadN, data.PressurePa, group);
forces = splitapply(@(a, b) [mean(a), mean(b)], ...
    data.TireForceXN, data.TireForceYN, group);

if size(points, 1) > options.MaximumPoints
    keep = unique(round(linspace(1, size(points, 1), ...
        options.MaximumPoints)));
    points = points(keep, :);
    forces = forces(keep, :);
end

map = struct( ...
    Points = points, ...
    Forces = forces, ...
    Scale = max(max(points, [], 1) - min(points, [], 1), ...
        [0.05, deg2rad(2.0), deg2rad(1.0), 100.0, 5000.0]), ...
    LowerBound = min(points, [], 1), ...
    UpperBound = max(points, [], 1), ...
    NeighborCount = uint8(8), ...
    ExtrapolationPolicy = "ClipEachInputThenInverseDistance8", ...
    Source = "FSAE TTC accepted and condition-binned samples");
end

function augmented = augmentSymmetry(data)
mirror = data;
mirror.SlipAngleRad = -mirror.SlipAngleRad;
mirror.CamberAngleRad = -mirror.CamberAngleRad;
mirror.TireForceYN = -mirror.TireForceYN;
augmented = [data; mirror];
end
