function [cleaned, audit] = cleanTTCData(run)
%CLEANTTCDATA Apply explicit TireModel quality gates without silent rejection.
%   CLEANED contains accepted rows. AUDIT records every rejected raw row,
%   a bit-coded reason, and per-reason counts.

arguments
    run (1, 1) struct
end

data = run.Data;
requiredNames = [ ...
    "ElapsedTimeS", "SpeedMps", "SlipAngleRad", "SlipRatio", ...
    "CamberAngleRad", "NormalLoadN", "TireForceXN", "TireForceYN", ...
    "PressurePa", "LoadedRadiusM"];
required = data{:, requiredNames};

reason = zeros(height(data), 1, "uint16");
reason = addReason(reason, any(~isfinite(required), 2), 1);
reason = addReason(reason, data.NormalLoadN < 100.0, 2);
reason = addReason(reason, data.SpeedMps < 2.0, 4);
reason = addReason(reason, data.PressurePa < 40000.0 | ...
    data.PressurePa > 120000.0, 8);
reason = addReason(reason, abs(data.SlipAngleRad) > deg2rad(15.0), 16);
reason = addReason(reason, abs(data.SlipRatio) > 0.40, 32);
reason = addReason(reason, abs(data.CamberAngleRad) > deg2rad(8.0), 64);
reason = addReason(reason, data.LoadedRadiusM <= 0.0 | ...
    data.LoadedRadiusM > 0.5, 128);

accepted = reason == 0;
cleaned = data(accepted, :);
cleaned.RunNumber = repmat(run.Metadata.RunNumber, height(cleaned), 1);
cleaned.TireID = repmat(run.Metadata.TireID, height(cleaned), 1);
cleaned.TestType = repmat(run.Metadata.TestType, height(cleaned), 1);
cleaned.SourceFile = repmat(run.Metadata.FileName, height(cleaned), 1);

reasonDefinitions = table( ...
    uint16([1; 2; 4; 8; 16; 32; 64; 128]), ...
    ["NonfiniteRequired"; "NormalLoadBelow100N"; "SpeedBelow2Mps"; ...
     "PressureOutside40To120kPa"; "SlipAngleOutside15deg"; ...
     "SlipRatioOutside0p40"; "CamberOutside8deg"; ...
     "LoadedRadiusOutside0To0p5m"], ...
    'VariableNames', ["Code", "Reason"]);
counts = zeros(height(reasonDefinitions), 1);
for index = 1:height(reasonDefinitions)
    counts(index) = nnz(bitand(reason, reasonDefinitions.Code(index)));
end
reasonDefinitions.Count = counts;

audit = struct( ...
    Metadata = run.Metadata, ...
    InputRows = height(data), ...
    AcceptedRows = nnz(accepted), ...
    RejectedRows = nnz(~accepted), ...
    ReasonCounts = reasonDefinitions, ...
    WarningCounts = table( ...
        "EffectiveRadiusOutside0To0p5m", ...
        nnz(data.EffectiveRadiusM <= 0.0 | ...
            data.EffectiveRadiusM > 0.5 | ...
            ~isfinite(data.EffectiveRadiusM)), ...
        'VariableNames', ["Warning", "Count"]), ...
    RejectedRowDetail = table( ...
        data.RawRow(~accepted), reason(~accepted), ...
        'VariableNames', ["RawRow", "ReasonCode"]));
end

function reason = addReason(reason, mask, code)
reason(mask) = bitor(reason(mask), uint16(code));
end
