function stiffness = deriveTTCLinearStiffness(profile, normalLoadN)
%DERIVETTCLINEARSTIFFNESS Derive local linear tire stiffness from TireModel TTC fit.
%   STIFFNESS = DERIVETTCLINEARSTIFFNESS() evaluates the selected TireModel
%   TTC-derived tire profile at its reference load and pressure.
%
%   STIFFNESS = DERIVETTCLINEARSTIFFNESS(PROFILE, NORMALLOADN) evaluates
%   one or more positive normal loads. Longitudinal stiffness is dFx/dkappa,
%   lateral stiffness follows TireSimple's positive convention -dFy/dalpha,
%   and camber stiffness is dFy/dgamma.
%
%   The selected 43075 profile uses target-tire TTC data for lateral and
%   camber behavior. Its longitudinal behavior is the explicitly identified
%   43100 R20 proxy because no driven 43075 TTC runs are available.

if nargin < 1 || isempty(profile)
    profile = getSelectedTireProfile();
end
if nargin < 2 || isempty(normalLoadN)
    normalLoadN = profile.Reference.NormalLoadN;
end

validateattributes(profile, {'struct'}, {'scalar'}, mfilename, 'profile');
validateattributes(normalLoadN, {'double'}, ...
    {'real', 'finite', 'positive', 'vector'}, mfilename, 'normalLoadN');

normalLoadN = normalLoadN(:);
zeroInput = zeros(size(normalLoadN));
roadGripScale = ones(size(normalLoadN));
roadMuLimit = inf(size(normalLoadN));
slipStep = 1.0e-5;
angleStep = deg2rad(1.0e-3);

[forceXPlus, ~] = evaluateTireMF62( ...
    slipStep * ones(size(normalLoadN)), zeroInput, zeroInput, ...
    normalLoadN, roadGripScale, roadMuLimit, profile);
[forceXMinus, ~] = evaluateTireMF62( ...
    -slipStep * ones(size(normalLoadN)), zeroInput, zeroInput, ...
    normalLoadN, roadGripScale, roadMuLimit, profile);

[~, forceYAlphaPlus] = evaluateTireMF62( ...
    zeroInput, angleStep * ones(size(normalLoadN)), zeroInput, ...
    normalLoadN, roadGripScale, roadMuLimit, profile);
[~, forceYAlphaMinus] = evaluateTireMF62( ...
    zeroInput, -angleStep * ones(size(normalLoadN)), zeroInput, ...
    normalLoadN, roadGripScale, roadMuLimit, profile);

[~, forceYGammaPlus] = evaluateTireMF62( ...
    zeroInput, zeroInput, angleStep * ones(size(normalLoadN)), ...
    normalLoadN, roadGripScale, roadMuLimit, profile);
[~, forceYGammaMinus] = evaluateTireMF62( ...
    zeroInput, zeroInput, -angleStep * ones(size(normalLoadN)), ...
    normalLoadN, roadGripScale, roadMuLimit, profile);

longitudinalStiffness = ...
    (forceXPlus - forceXMinus) ./ (2.0 * slipStep);
lateralStiffness = ...
    -(forceYAlphaPlus - forceYAlphaMinus) ./ (2.0 * angleStep);
camberStiffness = ...
    (forceYGammaPlus - forceYGammaMinus) ./ (2.0 * angleStep);

assert(all(isfinite(longitudinalStiffness)) && ...
    all(longitudinalStiffness > 0.0), ...
    "FSAE:TireModel:LongitudinalStiffness", ...
    "Derived longitudinal stiffness must be positive and finite.");
assert(all(isfinite(lateralStiffness)) && ...
    all(lateralStiffness > 0.0), ...
    "FSAE:TireModel:LateralStiffness", ...
    "Derived lateral stiffness must be positive and finite.");
assert(all(isfinite(camberStiffness)), ...
    "FSAE:TireModel:CamberStiffness", ...
    "Derived camber stiffness must be finite.");

stiffness = struct( ...
    "ProfileName", string(profile.Name), ...
    "TargetTireID", string(profile.TireID), ...
    "LongitudinalSourceTireID", string(profile.ProxyTireID), ...
    "NormalLoadN", normalLoadN, ...
    "ReferencePressurePa", profile.Reference.PressurePa, ...
    "LongitudinalStiffnessN", longitudinalStiffness, ...
    "LateralStiffnessNPerRad", lateralStiffness, ...
    "CamberStiffnessNPerRad", camberStiffness, ...
    "SlipDerivativeStep", slipStep, ...
    "AngleDerivativeStepRad", angleStep, ...
    "Method", "Centered derivative of selected TTC-derived TireModel fit", ...
    "LongitudinalIsProxy", true);
end
