function [profile, metrics] = fitTTCProfile(target, surrogate, metadata)
%FITTTCPROFILE Fit one 43075 lateral profile and explicit proxy channels.
%   TARGET contains 43075 cornering train/validation tables. SURROGATE
%   contains a fully tested proxy tire used only for longitudinal and
%   combined-slip behavior because TTC collected no drive/brake data for
%   the 43075 tire.

arguments
    target (1, 1) struct
    surrogate (1, 1) struct
    metadata (1, 1) struct
end

targetTrain = aggregateData(target.Train);
targetValidation = aggregateData(target.Validation);
surrogateCornerTrain = aggregateData(surrogate.CornerTrain);
surrogateCornerValidation = aggregateData(surrogate.CornerValidation);
surrogateDriveTrain = aggregateData(surrogate.DriveTrain);
surrogateDriveValidation = aggregateData(surrogate.DriveValidation);

allReference = [targetTrain; targetValidation; surrogateDriveTrain];
reference = struct( ...
    NormalLoadN = median(allReference.NormalLoadN, "omitnan"), ...
    PressurePa = median(allReference.PressurePa, "omitnan"));

targetLateral = fitPureLateral(targetTrain, reference);
surrogateLateral = fitPureLateral(surrogateCornerTrain, reference);
surrogateLongitudinal = fitPureLongitudinal( ...
    surrogateDriveTrain, reference);
surrogateProfile = struct( ...
    Reference = reference, ...
    InputPressurePa = reference.PressurePa, ...
    Lateral = surrogateLateral, ...
    Longitudinal = surrogateLongitudinal);
surrogateCombined = fitCombined( ...
    surrogateDriveTrain, surrogateProfile);

profile = struct( ...
    Name = metadata.Name, ...
    TireID = metadata.TireID, ...
    TTCRound = metadata.TTCRound, ...
    Compound = metadata.Compound, ...
    RimWidthIn = metadata.RimWidthIn, ...
    ModelClass = "MF6.2-equivalent steady-state", ...
    TargetDataScope = "Pure lateral and camber only", ...
    LongitudinalDataScope = "Proxy; not Hoosier 43075 measurement", ...
    CombinedDataScope = "Proxy; not Hoosier 43075 measurement", ...
    ProxyTireID = surrogate.TireID, ...
    VehicleSelectionConfirmed = true, ...
    InputPressurePa = reference.PressurePa, ...
    UseRuntimePressure = false, ...
    Reference = reference, ...
    Lateral = targetLateral, ...
    Longitudinal = surrogateLongitudinal, ...
    Combined = surrogateCombined, ...
    Map = buildTTCReferenceMap([targetTrain; targetValidation]), ...
    Validity = struct( ...
        MapSlipRatio = "zero only", ...
        MapExtrapolation = ...
            "clip each input then 8-neighbor inverse-distance", ...
        MFPressure = "fixed per selected profile; no runtime pressure port", ...
        Longitudinal = "proxy from listed ProxyTireID", ...
        Combined = "proxy generalized-friction-ellipse parameters"));

metrics = [ ...
    metricRows(profile, targetTrain, "Train", "TargetLateral"); ...
    metricRows(profile, targetValidation, "Validation", "TargetLateral"); ...
    metricRows(surrogateProfileWithCombined(surrogateProfile, ...
        surrogateCombined), surrogateCornerTrain, "Train", ...
        "ProxyLateral"); ...
    metricRows(surrogateProfileWithCombined(surrogateProfile, ...
        surrogateCombined), surrogateCornerValidation, "Validation", ...
        "ProxyLateral"); ...
    metricRows(surrogateProfileWithCombined(surrogateProfile, ...
        surrogateCombined), surrogateDriveTrain, "Train", ...
        "ProxyDriveCombined"); ...
    metricRows(surrogateProfileWithCombined(surrogateProfile, ...
        surrogateCombined), surrogateDriveValidation, "Validation", ...
        "ProxyDriveCombined")];
metrics.Profile = repmat(profile.Name, height(metrics), 1);
metrics.TargetTireID = repmat(profile.TireID, height(metrics), 1);
metrics.ProxyTireID = repmat(profile.ProxyTireID, height(metrics), 1);
end

function lateral = fitPureLateral(data, reference)
selection = abs(data.SlipRatio) <= 0.005 & ...
    abs(data.SlipAngleRad) <= deg2rad(12.5);
fitData = data(selection, :);
assert(height(fitData) >= 100, "FSAE:TireModel:LateralFitData", ...
    "Insufficient pure-lateral TTC samples.");

initial = [14.0, 1.35, 0.0, 2.0, -0.2, 0.0, 0.0, ...
    0.0, 0.1, 0.0, 0.4];
lower = [0.1, 0.5, -2.0, 0.1, -2.0, -2.0, -20.0, ...
    -0.10, -2.0, -0.5, -5.0];
upper = [80.0, 2.5, 2.0, 5.0, 2.0, 2.0, 20.0, ...
    0.10, 2.0, 0.5, 5.0];
options = optimoptions("lsqnonlin", Display = "off", ...
    MaxIterations = 120, MaxFunctionEvaluations = 4000);
parameters = lsqnonlin(@residual, initial, lower, upper, options);
    function value = residual(candidate)
        prediction = predictLateral(candidate, fitData, reference);
        value = (prediction - fitData.TireForceYN) ./ ...
            max(fitData.NormalLoadN, 100.0);
    end

lateral = struct( ...
    B = parameters(1), C = parameters(2), E = parameters(3), ...
    Mu0 = parameters(4), MuLoad = parameters(5), ...
    MuPressure = parameters(6), MuCamber2 = parameters(7), ...
    HorizontalShift = parameters(8), CamberShift = parameters(9), ...
    VerticalShift = parameters(10), ...
    CamberVerticalShift = parameters(11));
end

function longitudinal = fitPureLongitudinal(data, reference)
selection = abs(data.SlipAngleRad) <= deg2rad(0.35) & ...
    abs(data.SlipRatio) <= 0.35;
fitData = data(selection, :);
assert(height(fitData) >= 100, "FSAE:TireModel:LongitudinalFitData", ...
    "Insufficient proxy pure-longitudinal TTC samples.");

initial = [14.0, 1.45, 0.0, 2.0, -0.2, 0.0, 0.0, ...
    0.0, 0.0, 0.0];
lower = [0.1, 0.5, -2.0, 0.1, -2.0, -2.0, -20.0, ...
    -2.0, -0.05, -0.5];
upper = [100.0, 2.5, 2.0, 5.0, 2.0, 2.0, 20.0, ...
    2.0, 0.05, 0.5];
options = optimoptions("lsqnonlin", Display = "off", ...
    MaxIterations = 120, MaxFunctionEvaluations = 4000);
parameters = lsqnonlin(@residual, initial, lower, upper, options);
    function value = residual(candidate)
        prediction = predictLongitudinal(candidate, fitData, reference);
        value = (prediction - fitData.TireForceXN) ./ ...
            max(fitData.NormalLoadN, 100.0);
    end

longitudinal = struct( ...
    B = parameters(1), C = parameters(2), E = parameters(3), ...
    Mu0 = parameters(4), MuLoad = parameters(5), ...
    MuPressure = parameters(6), MuCamber2 = parameters(7), ...
    MuAsymmetry = parameters(8), ...
    HorizontalShift = parameters(9), VerticalShift = parameters(10));
end

function combined = fitCombined(data, profile)
selection = abs(data.SlipAngleRad) >= deg2rad(0.35) & ...
    abs(data.SlipRatio) <= 0.35;
fitData = data(selection, :);
assert(height(fitData) >= 100, "FSAE:TireModel:CombinedFitData", ...
    "Insufficient proxy combined-slip TTC samples.");
initial = [deg2rad(5.0), 0.10, 2.0, 1.0, 1.0];
lower = [deg2rad(0.5), 0.005, 1.0, 0.1, 0.1];
upper = [deg2rad(30.0), 1.0, 8.0, 5.0, 5.0];
options = optimoptions("lsqnonlin", Display = "off", ...
    MaxIterations = 100, MaxFunctionEvaluations = 2500);
parameters = lsqnonlin(@residual, initial, lower, upper, options);
    function value = residual(candidate)
        predicted = predictCombined(candidate, fitData, profile);
        value = [ ...
            (predicted(:, 1) - fitData.TireForceXN) ./ ...
                max(fitData.NormalLoadN, 100.0); ...
            (predicted(:, 2) - fitData.TireForceYN) ./ ...
                max(fitData.NormalLoadN, 100.0)];
    end
combined = struct( ...
    AlphaScaleRad = parameters(1), KappaScale = parameters(2), ...
    Exponent = parameters(3), ...
    LongitudinalScaleExponent = parameters(4), ...
    LateralScaleExponent = parameters(5));
end

function force = predictLongitudinal(parameters, data, reference)
loadDelta = (data.NormalLoadN - reference.NormalLoadN) ./ ...
    reference.NormalLoadN;
pressureDelta = (data.PressurePa - reference.PressurePa) ./ ...
    reference.PressurePa;
mu = parameters(4) + parameters(5) .* loadDelta + ...
    parameters(6) .* pressureDelta + ...
    parameters(7) .* data.CamberAngleRad.^2 + ...
    parameters(8) .* tanh(50.0 .* data.SlipRatio);
mu = max(mu, 0.05);
x = data.SlipRatio + parameters(9);
bx = parameters(1) .* x;
force = data.NormalLoadN .* mu .* sin(parameters(2) .* atan( ...
    bx - parameters(3) .* (bx - atan(bx)))) + ...
    data.NormalLoadN .* parameters(10);
end

function force = predictLateral(parameters, data, reference)
loadDelta = (data.NormalLoadN - reference.NormalLoadN) ./ ...
    reference.NormalLoadN;
pressureDelta = (data.PressurePa - reference.PressurePa) ./ ...
    reference.PressurePa;
mu = parameters(4) + parameters(5) .* loadDelta + ...
    parameters(6) .* pressureDelta + ...
    parameters(7) .* data.CamberAngleRad.^2;
mu = max(mu, 0.05);
alpha = data.SlipAngleRad + parameters(8) + ...
    parameters(9) .* data.CamberAngleRad;
by = parameters(1) .* alpha;
force = -data.NormalLoadN .* mu .* sin(parameters(2) .* atan( ...
    by - parameters(3) .* (by - atan(by)))) + ...
    data.NormalLoadN .* (parameters(10) + ...
    parameters(11) .* data.CamberAngleRad);
end

function predicted = predictCombined(parameters, data, profile)
longitudinal = struct2array(profile.Longitudinal);
lateral = struct2array(profile.Lateral);
pureX = predictLongitudinal(longitudinal, data, profile.Reference);
pureY = predictLateral(lateral, data, profile.Reference);
scaleX = (1.0 + (abs(data.SlipAngleRad) ./ parameters(1)) .^ ...
    parameters(3)) .^ (-parameters(4) / parameters(3));
scaleY = (1.0 + (abs(data.SlipRatio) ./ parameters(2)) .^ ...
    parameters(3)) .^ (-parameters(5) / parameters(3));
predicted = [ ...
    pureX .* scaleX, pureY .* scaleY];
end

function output = surrogateProfileWithCombined(profile, combined)
output = profile;
output.Combined = combined;
end

function rows = metricRows(profile, data, partition, scope)
[predictedX, predictedY] = evaluateTireMF62( ...
    data.SlipRatio, data.SlipAngleRad, data.CamberAngleRad, ...
    data.NormalLoadN, ones(height(data), 1), ...
    inf(height(data), 1), profile);
rows = [ ...
    oneMetric("Fx", data.TireForceXN, predictedX); ...
    oneMetric("Fy", data.TireForceYN, predictedY)];
rows.Partition = repmat(string(partition), height(rows), 1);
rows.Scope = repmat(string(scope), height(rows), 1);
end

function row = oneMetric(channel, actual, predicted)
error = predicted - actual;
sumSquares = sum((actual - mean(actual)).^2);
row = table( ...
    string(channel), sqrt(mean(error.^2)), mean(abs(error)), ...
    1.0 - sum(error.^2) / max(sumSquares, eps), ...
    height(actual), ...
    'VariableNames', ["Channel", "RMSE_N", "MAE_N", "R2", "Samples"]);
end

function aggregated = aggregateData(data)
assert(~isempty(data), "FSAE:TireModel:EmptyFitData", ...
    "Cannot aggregate an empty TTC dataset.");
keys = [ ...
    round(data.SlipRatio / 0.005), ...
    round(data.SlipAngleRad / deg2rad(0.25)), ...
    round(data.CamberAngleRad / deg2rad(0.25)), ...
    round(data.NormalLoadN / 25.0), ...
    round(data.PressurePa / 2000.0), ...
    data.RunNumber];
[group, ~, ~, ~, ~, ~, ~] = findgroups( ...
    keys(:, 1), keys(:, 2), keys(:, 3), keys(:, 4), keys(:, 5), ...
    keys(:, 6));
aggregated = table;
variables = [ ...
    "SlipRatio", "SlipAngleRad", "CamberAngleRad", "NormalLoadN", ...
    "PressurePa", "TireForceXN", "TireForceYN", "SpeedMps", ...
    "EffectiveRadiusM"];
for variable = variables
    aggregated.(variable) = splitapply(@mean, data.(variable), group);
end
aggregated.RunNumber = splitapply(@(x) x(1), data.RunNumber, group);
end
