function run = importTTCData(filePath)
%IMPORTTTCDATA Import one FSAE TTC MATLAB SI run into project conventions.
%   RUN = IMPORTTTCDATA(FILEPATH) preserves provenance and converts the
%   Calspan SAE normal-load sign to the project-positive support load.
%   No quality filtering is performed by this function.

arguments
    filePath (1, 1) string
end

assert(isfile(filePath), "FSAE:TireModel:MissingTTCFile", ...
    "TTC file does not exist: %s", filePath);
[~, fileName, extension] = fileparts(filePath);
assert(strcmpi(extension, ".mat") && startsWith(fileName, "B"), ...
    "FSAE:TireModel:UnsupportedTTCFile", ...
    "Expected a TTC MATLAB SI run named B*.mat: %s", filePath);

requiredChannels = [ ...
    "ET", "V", "N", "SA", "IA", "RL", "RE", "P", "FX", "FY", ...
    "FZ", "MX", "MZ", "NFX", "NFY", "RST", "TSTI", "TSTC", ...
    "TSTO", "AMBTMP", "SR", "SL", "RUN"];
requiredMetadata = ["channel", "source", "testid", "tireid"];
available = string({whos("-file", filePath).name});
missing = setdiff([requiredChannels, requiredMetadata], available);
assert(isempty(missing), "FSAE:TireModel:MissingTTCChannel", ...
    "TTC file %s is missing: %s", filePath, strjoin(missing, ", "));

loaded = load(filePath, requiredChannels{:}, requiredMetadata{:});
validateChannelUnits(loaded.channel, filePath);
rowCount = numel(loaded.ET);
for channelName = requiredChannels
    assert(numel(loaded.(channelName)) == rowCount, ...
        "FSAE:TireModel:ChannelLength", ...
        "Channel %s in %s does not have %d rows.", ...
        channelName, filePath, rowCount);
end

runNumber = double(mode(loaded.RUN));
data = table( ...
    (1:rowCount)', loaded.ET(:), loaded.V(:) / 3.6, ...
    loaded.N(:) * (2.0 * pi / 60.0), deg2rad(loaded.SA(:)), ...
    loaded.SL(:), loaded.SR(:), deg2rad(loaded.IA(:)), ...
    -loaded.FZ(:), loaded.FX(:), loaded.FY(:), loaded.MX(:), ...
    loaded.MZ(:), loaded.P(:) * 1000.0, loaded.RE(:) / 100.0, ...
    loaded.RL(:) / 100.0, loaded.RST(:), loaded.TSTI(:), ...
    loaded.TSTC(:), loaded.TSTO(:), loaded.AMBTMP(:), ...
    'VariableNames', [ ...
    "RawRow", "ElapsedTimeS", "SpeedMps", "WheelSpeedRadps", ...
    "SlipAngleRad", "SlipRatio", "MachineSlipRatio", ...
    "CamberAngleRad", "NormalLoadN", "TireForceXN", ...
    "TireForceYN", "OverturningMomentNm", "AligningMomentNm", ...
    "PressurePa", "EffectiveRadiusM", "LoadedRadiusM", ...
    "RoadTemperatureDegC", "TireTemperatureInboardDegC", ...
    "TireTemperatureCenterDegC", "TireTemperatureOutboardDegC", ...
    "AmbientTemperatureDegC"]);

fileInfo = dir(filePath);
run = struct;
run.Data = data;
run.Metadata = struct( ...
    FilePath = string(filePath), ...
    FileName = string(fileName + extension), ...
    FileBytes = double(fileInfo.bytes), ...
    FileModified = string(datetime(fileInfo.datenum, ...
        ConvertFrom = "datenum", Format = "yyyy-MM-dd'T'HH:mm:ss")), ...
    RunNumber = runNumber, ...
    TireID = strtrim(string(loaded.tireid)), ...
    TestType = strtrim(string(loaded.testid)), ...
    Source = strtrim(string(loaded.source)), ...
    SampleRateHz = 100.0, ...
    SourceConvention = "SAE/Calspan", ...
    ProjectConversion = struct( ...
        NormalLoad = "NormalLoadN = -FZ", ...
        SlipRatio = "SlipRatio = SL", ...
        SlipAngle = "SlipAngleRad = deg2rad(SA)", ...
        Camber = "CamberAngleRad = deg2rad(IA)", ...
        LongitudinalForce = "TireForceXN = FX", ...
        LateralForce = "TireForceYN = FY"));
end

function validateChannelUnits(channel, filePath)
names = string(channel.name);
units = string(channel.units);
expected = dictionary( ...
    ["ET", "V", "N", "SA", "IA", "RL", "RE", "P", "FX", "FY", ...
     "FZ", "MX", "MZ", "SR", "SL"], ...
    ["sec", "kph", "rpm", "deg", "deg", "cm", "cm", "kPa", ...
     "N", "N", "N", "N-m", "N-m", "none", "none"]);
keys = string(expected.keys);
for index = 1:numel(keys)
    location = find(names == keys(index), 1);
    assert(~isempty(location) && units(location) == expected(keys(index)), ...
        "FSAE:TireModel:TTCUnitMismatch", ...
        "Unexpected unit for %s in %s.", keys(index), filePath);
end
end
