function result = runTirePipeline(options)
%RUNTireModelTIREPIPELINE Audit, fit, report and install the TireModel tire database.
%   Target: Hoosier 43075 16x7.5-10 R20 on a 7 inch rim.
%   Longitudinal/combined proxy: Hoosier 43100 18.0x6.0-10 R20
%   on the same 7 inch rim width.

arguments
    options.ProjectRoot (1, 1) string = defaultProjectRoot()
    options.GenerateFigures (1, 1) logical = true
    options.InstallDictionary (1, 1) logical = true
end

projectRoot = options.ProjectRoot;
ttcRoot = fullfile(projectRoot, "TTC");
dataOutput = fullfile(projectRoot, "data", "TireData");
resultOutput = fullfile(projectRoot, "results", "quasi_static", ...
    "ggv", "tire_model");
figureOutput = fullfile(resultOutput, "figures");
createFolder(dataOutput);
createFolder(resultOutput);
createFolder(figureOutput);

inventory = auditTTCData(ttcRoot);
inventoryPath = fullfile(dataOutput, "ttc_inventory.csv");
writetable(inventory, inventoryPath);

targetMask = inventory.Round == 9 & ...
    contains(inventory.TireID, "Hoosier 43075 16x7.5-10 R20") & ...
    contains(inventory.TireID, "7 inch rim") & ...
    inventory.TestType == "Cornering";
targetIDs = unique(inventory.TireID(targetMask), "stable");
assert(isscalar(targetIDs), "FSAE:TireModel:TargetProfiles", ...
    "Expected one Round 9 43075 R20 7-inch profile, found %d.", ...
    numel(targetIDs));

proxyMask = inventory.Round == 9 & ...
    contains(inventory.TireID, "Hoosier 43100 18.0x6.0-10 R20") & ...
    contains(inventory.TireID, "7 inch rim");
proxyIDs = unique(inventory.TireID(proxyMask), "stable");
assert(isscalar(proxyIDs), "FSAE:TireModel:ProxyProfiles", ...
    "Expected one Round 9 43100 R20 7-inch proxy profile.");

[proxy, proxyAudit] = loadProxyDataset(inventory, proxyIDs);
profiles = repmat(emptyProfile(), 0, 1);
allMetrics = table;
cleaningAudit = proxyAudit;
plotFiles = strings(0, 1);
for index = 1:numel(targetIDs)
    targetID = targetIDs(index);
    [target, targetAudit] = loadTargetDataset(inventory, targetID);
    cleaningAudit = [cleaningAudit; targetAudit]; %#ok<AGROW>
    metadata = profileMetadata(targetID);
    [profile, metrics] = fitTTCProfile(target, proxy, metadata);
    profiles(end + 1, 1) = profile; %#ok<AGROW>
    allMetrics = [allMetrics; metrics]; %#ok<AGROW>
    if options.GenerateFigures
        plotPath = fullfile(figureOutput, profile.Name + ".fig");
        comparisonPlotFiles = plotTTCFitComparison( ...
            profile, target.Validation, plotPath);
        plotFiles = [plotFiles; comparisonPlotFiles]; %#ok<AGROW>
    end
end

database = struct( ...
    Version = "TireModelBaseline", ...
    GeneratedAt = string(datetime("now", ...
        Format = "yyyy-MM-dd'T'HH:mm:ss")), ...
    TargetTire = "Hoosier 43075 16x7.5-10 R20", ...
    TargetData = "Round 9 cornering, pure lateral and camber", ...
    LongitudinalProxy = strjoin(proxyIDs, " | "), ...
    LongitudinalProxyRationale = ...
        "Same Hoosier R20 compound, different 18.0x6.0-10 size", ...
    Profiles = profiles, ...
    DefaultProfileIndex = uint16(1), ...
    Limitations = [ ...
        "No 43075 drive/brake TTC data because the offset adapter " + ...
            "cannot transmit drive torque"; ...
        "Longitudinal and combined-slip parameters are transferred " + ...
            "from 43100 R20 and are not target-size measurements"; ...
        "Runtime tire pressure is frozen to the selected profile value"; ...
        "TTC Map is a pure-lateral/camber reference for the target tire"; ...
        "The selected wheel is a 7 inch rim"]);

modelDataPath = fullfile(dataOutput, "TireModelData.mat");
metricsPath = fullfile(resultOutput, "tire_fit_metrics.csv");
auditPath = fullfile(resultOutput, "tire_cleaning_audit.csv");
writetable(allMetrics, metricsPath);
writetable(cleaningAudit, auditPath);
save(modelDataPath, "database", "allMetrics", "inventory", ...
    "cleaningAudit", "-v7.3");

selection = struct;
if options.InstallDictionary
    selection = installTireData(database, ...
        fullfile(projectRoot, "data", "VehicleData.sldd"));
end
reportPath = fullfile(projectRoot, "data", "TireData", ...
    "TTC_Tire_Model_Report.md");
generateTireReport(reportPath, database, inventory, allMetrics, ...
    cleaningAudit, plotFiles, projectRoot);

result = struct( ...
    Passed = true, ...
    DatabasePath = string(modelDataPath), ...
    InventoryPath = string(inventoryPath), ...
    MetricsPath = string(metricsPath), ...
    CleaningAuditPath = string(auditPath), ...
    ReportPath = string(reportPath), ...
    ProfileCount = numel(profiles), ...
    Selection = selection);
fprintf("TireModel tire pipeline completed: %d profiles.\n", numel(profiles));
end

function [target, audit] = loadTargetDataset(inventory, targetID)
rows = inventory(inventory.TireID == targetID & ...
    inventory.TestType == "Cornering", :);
[trainFiles, validationFiles] = splitMainRuns(rows);
[target.Train, trainAudit] = loadRuns(trainFiles, "TargetTrain");
[target.Validation, validationAudit] = loadRuns( ...
    validationFiles, "TargetValidation");
audit = [trainAudit; validationAudit];
end

function [proxy, audit] = loadProxyDataset(inventory, proxyIDs)
proxy.CornerTrain = table;
proxy.CornerValidation = table;
proxy.DriveTrain = table;
proxy.DriveValidation = table;
audit = table;
for index = 1:numel(proxyIDs)
    tireID = proxyIDs(index);
    cornerRows = inventory(inventory.TireID == tireID & ...
        inventory.TestType == "Cornering", :);
    driveRows = inventory(inventory.TireID == tireID & ...
        inventory.TestType == "Drive/Brake/Combined", :);
    [cornerTrainFiles, cornerValidationFiles] = splitMainRuns(cornerRows);
    [driveTrainFiles, driveValidationFiles] = splitMainRuns(driveRows);
    [cornerTrain, a1] = loadRuns(cornerTrainFiles, "ProxyCornerTrain");
    [cornerValidation, a2] = loadRuns( ...
        cornerValidationFiles, "ProxyCornerValidation");
    [driveTrain, a3] = loadRuns(driveTrainFiles, "ProxyDriveTrain");
    [driveValidation, a4] = loadRuns( ...
        driveValidationFiles, "ProxyDriveValidation");
    proxy.CornerTrain = [proxy.CornerTrain; cornerTrain];
    proxy.CornerValidation = [ ...
        proxy.CornerValidation; cornerValidation];
    proxy.DriveTrain = [proxy.DriveTrain; driveTrain];
    proxy.DriveValidation = [proxy.DriveValidation; driveValidation];
    audit = [audit; a1; a2; a3; a4]; %#ok<AGROW>
end
proxy.TireID = strjoin(proxyIDs, " | ");
end

function [trainFiles, validationFiles] = splitMainRuns(rows)
rows = sortrows(rows, "RunNumber");
assert(height(rows) >= 3, "FSAE:TireModel:RunSplit", ...
    "Expected transient/warmup plus at least two main runs for %s.", ...
    rows.TireID(1));
mainRows = rows(2:end, :);
trainFiles = mainRows.FilePath(1:end - 1);
validationFiles = mainRows.FilePath(end);
end

function [data, auditRows] = loadRuns(filePaths, partition)
data = table;
auditRows = table;
for index = 1:numel(filePaths)
    run = importTTCData(filePaths(index));
    [accepted, audit] = cleanTTCData(run);
    data = [data; accepted]; %#ok<AGROW>
    reasonSummary = strjoin( ...
        audit.ReasonCounts.Reason(audit.ReasonCounts.Count > 0) + "=" + ...
        string(audit.ReasonCounts.Count(audit.ReasonCounts.Count > 0)), ...
        ";");
    warningSummary = strjoin( ...
        audit.WarningCounts.Warning(audit.WarningCounts.Count > 0) + "=" + ...
        string(audit.WarningCounts.Count(audit.WarningCounts.Count > 0)), ...
        ";");
    row = table( ...
        string(partition), run.Metadata.FileName, ...
        run.Metadata.TireID, run.Metadata.TestType, ...
        run.Metadata.RunNumber, audit.InputRows, ...
        audit.AcceptedRows, audit.RejectedRows, reasonSummary, ...
        warningSummary, ...
        'VariableNames', [ ...
        "Partition", "FileName", "TireID", "TestType", "RunNumber", ...
        "InputRows", "AcceptedRows", "RejectedRows", "Reasons", ...
        "Warnings"]);
    auditRows = [auditRows; row]; %#ok<AGROW>
end
end

function metadata = profileMetadata(tireID)
rimToken = regexp(tireID, "(\d+) inch rim", "tokens", "once");
assert(~isempty(rimToken), "FSAE:TireModel:RimMetadata", ...
    "Could not parse rim width from '%s'.", tireID);
rimWidth = str2double(rimToken{1});
metadata = struct( ...
    Name = "Round9_43075_R20_Rim" + string(rimWidth), ...
    TireID = tireID, ...
    TTCRound = uint8(9), ...
    Compound = "R20", ...
    RimWidthIn = rimWidth);
end

function profile = emptyProfile()
profile = struct( ...
    Name = "", TireID = "", TTCRound = uint8(0), Compound = "", ...
    RimWidthIn = NaN, ModelClass = "", TargetDataScope = "", ...
    LongitudinalDataScope = "", CombinedDataScope = "", ...
    ProxyTireID = "", VehicleSelectionConfirmed = false, ...
    InputPressurePa = NaN, UseRuntimePressure = false, ...
    Reference = struct, Lateral = struct, Longitudinal = struct, ...
    Combined = struct, Map = struct, Validity = struct);
end

function createFolder(path)
if ~isfolder(path)
    mkdir(path);
end
end

function root = defaultProjectRoot()
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
end
