function parameters = serializeTireModelMFParameters(profile)
%SERIALIZETireModelMFPARAMETERS Flatten an TireModel tire profile for Simulink codegen.

parameters = [ ...
    profile.InputPressurePa; ...
    profile.Reference.NormalLoadN; ...
    profile.Reference.PressurePa; ...
    profile.Longitudinal.B; ...
    profile.Longitudinal.C; ...
    profile.Longitudinal.E; ...
    profile.Longitudinal.Mu0; ...
    profile.Longitudinal.MuLoad; ...
    profile.Longitudinal.MuPressure; ...
    profile.Longitudinal.MuCamber2; ...
    profile.Longitudinal.MuAsymmetry; ...
    profile.Longitudinal.HorizontalShift; ...
    profile.Longitudinal.VerticalShift; ...
    profile.Lateral.B; ...
    profile.Lateral.C; ...
    profile.Lateral.E; ...
    profile.Lateral.Mu0; ...
    profile.Lateral.MuLoad; ...
    profile.Lateral.MuPressure; ...
    profile.Lateral.MuCamber2; ...
    profile.Lateral.HorizontalShift; ...
    profile.Lateral.CamberShift; ...
    profile.Lateral.VerticalShift; ...
    profile.Lateral.CamberVerticalShift; ...
    profile.Combined.AlphaScaleRad; ...
    profile.Combined.KappaScale; ...
    profile.Combined.Exponent; ...
    profile.Combined.LongitudinalScaleExponent; ...
    profile.Combined.LateralScaleExponent];
end
