function report = runVehicle10DOFVerification(options)
%RUNVehicle10DOFVERIFICATION Verify the Vehicle10DOF 10DOF plant and 7DOF equivalence.

arguments
    options.RunClosedLoop (1, 1) logical = true
    options.SaveSummary (1, 1) logical = true
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "initialization"));
addpath(fullfile(projectRoot, "scripts", "path_tracking"));
addpath(fullfile(projectRoot, "scripts", "torque_vectoring"));
addpath(fullfile(projectRoot, "scripts", "vehicle_10dof"));
addpath(fullfile(projectRoot, "tests", "torque_vectoring"));
addpath(fullfile(projectRoot, "scripts", "simulation"));
addpath(fullfile(projectRoot, "scripts", "track"));
addpath(fullfile(projectRoot, "scenarios", "Skidpad"));

initProject();
installE41VehicleParameters();
parameters = installVehicle10DOFSuspensionData();

staticOutput = simulateVehicle("Vehicle10DOF", 0.2, 0.0, 0.0);
staticNormalLoad = finalValue(staticOutput, 19);
staticState = [finalValue(staticOutput, 17); ...
    finalValue(staticOutput, 15); finalValue(staticOutput, 16)];
staticLoadError = sum(staticNormalLoad) - ...
    parameters.Mass * parameters.Gravity;

assert(max(abs(staticState)) < 1.0e-10, "FSAE:Vehicle10DOF:StaticState", ...
    "The Vehicle10DOF sprung-body states drifted away from static equilibrium.");
assert(abs(staticLoadError) < 1.0e-8, "FSAE:Vehicle10DOF:StaticLoad", ...
    "Static normal loads do not sum to vehicle weight.");

dynamicOutput = simulateVehicle("Vehicle10DOF", 1.0, 600.0, 800.0);
dynamicNormalLoad = outputData(dynamicOutput, 19);
dynamicTime = dynamicOutput.getElement(19).Values.Time;
dynamicAz = outputData(dynamicOutput, 18);
dynamicRoll = outputData(dynamicOutput, 15);
dynamicPitch = outputData(dynamicOutput, 16);
dynamicLoadResidual = sum(dynamicNormalLoad, 2) - parameters.Mass .* ...
    (parameters.Gravity + dynamicAz);

assert(all(isfinite(dynamicNormalLoad), "all"), "FSAE:Vehicle10DOF:FiniteLoad", ...
    "The combined excitation produced nonfinite normal loads.");
assert(min(dynamicNormalLoad, [], "all") >= -1.0e-10, ...
    "FSAE:Vehicle10DOF:NegativeLoad", ...
    "The combined excitation produced a negative wheel normal load.");
assert(max(abs(dynamicLoadResidual)) < 1.0e-6, ...
    "FSAE:Vehicle10DOF:LoadConservation", ...
    "Dynamic normal loads violate vertical force conservation.");
assert(dynamicRoll(end) > 0, "FSAE:Vehicle10DOF:RollSign", ...
    "Positive lateral acceleration did not produce positive roll.");
assert(dynamicPitch(end) < 0, "FSAE:Vehicle10DOF:PitchSign", ...
    "Positive longitudinal acceleration did not produce nose-up pitch.");

quickSteer = assessDynamicScenario( ...
    simulateVehicle("Vehicle10DOF", 1.0, 0.0, 1200.0), parameters);
brakeInTurn = assessDynamicScenario( ...
    simulateVehicle("Vehicle10DOF", 1.0, -1600.0, 1000.0), parameters);
assert(quickSteer.Passed && brakeInTurn.Passed, ...
    "FSAE:Vehicle10DOF:DynamicScenario", ...
    "Quick-steer or brake-in-turn proxy produced invalid wheel loads.");

[modalFrequencies, modalShapes] = calculateModes(parameters);
assert(all(modalFrequencies > 0) && all(isfinite(modalFrequencies)), ...
    "FSAE:Vehicle10DOF:Modes", "The heave/roll/pitch modal frequencies are invalid.");

comparison = comparePlanarModels();
if comparison.MaximumAbsoluteDifference >= 1.0e-8
    disp(table(comparison.SignalNames.', ...
        comparison.MaximumAbsoluteDifferenceBySignal, ...
        VariableNames = ["Signal", "MaximumAbsoluteDifference"]));
end
assert(comparison.MaximumAbsoluteDifference < 1.0e-8, ...
    "FSAE:Vehicle10DOF:PlanarRegression", ...
    "The first 14 Vehicle10DOF outputs no longer match Vehicle7DOF under identical inputs.");

closedLoop = struct("Executed", false, "Passed", false, ...
    "MinimumNormalLoad", NaN, "MaximumAbsRollAngle", NaN, ...
    "MaximumAbsPitchAngle", NaN);
if options.RunClosedLoop
    closedLoop = runClosedLoopSmoke();
    assert(closedLoop.MinimumNormalLoad >= -1.0e-10, ...
        "FSAE:Vehicle10DOF:ClosedLoopNegativeLoad", ...
        "The Vehicle10DOF closed-loop smoke run produced a negative normal load.");
end

report = struct( ...
    "SchemaVersion", "1.0", ...
    "GeneratedAt", string(datetime("now", ...
        Format = "yyyy-MM-dd'T'HH:mm:ss")), ...
    "Model", "FSAE_Vehicle10DOF_ClosedLoop", ...
    "DamperValveSpecification", parameters.DamperValveSpecification, ...
    "DamperExternalSetting", parameters.DamperExternalSetting, ...
    "DamperSettingConfirmed", parameters.DamperSettingConfirmed, ...
    "StaticNormalLoad", staticNormalLoad, ...
    "StaticLoadError", staticLoadError, ...
    "ModalFrequenciesHz", modalFrequencies, ...
    "ModalShapes", modalShapes, ...
    "MinimumDynamicNormalLoad", min(dynamicNormalLoad, [], "all"), ...
    "MaximumDynamicLoadResidual", max(abs(dynamicLoadResidual)), ...
    "PeakRollAngle", max(abs(dynamicRoll)), ...
    "PeakPitchAngle", max(abs(dynamicPitch)), ...
    "ScenarioChecks", struct( ...
        "QuickSteer", quickSteer, "BrakeInTurn", brakeInTurn), ...
    "PlanarComparison", comparison, ...
    "ClosedLoopSmoke", closedLoop);

if options.SaveSummary
    resultFolder = fullfile(projectRoot, "tests", "vehicle_10dof", "results");
    if ~isfolder(resultFolder)
        mkdir(resultFolder);
    end
    save(fullfile(resultFolder, "Vehicle10DOFVerificationSummary.mat"), ...
        "report", "-v7.3");
    saveVerificationFigures(resultFolder, comparison, ...
        dynamicTime, dynamicNormalLoad);
end

fprintf("Vehicle10DOF static load error: %.3e N.\n", report.StaticLoadError);
fprintf("Vehicle10DOF modal frequencies [Hz]: %.3f %.3f %.3f.\n", ...
    report.ModalFrequenciesHz);
fprintf("Vehicle10DOF minimum dynamic wheel load: %.3f N.\n", ...
    report.MinimumDynamicNormalLoad);
fprintf("Vehicle10DOF 7DOF/10DOF maximum planar difference: %.3e.\n", ...
    report.PlanarComparison.MaximumAbsoluteDifference);
end

function assessment = assessDynamicScenario(output, parameters)
normalLoad = outputData(output, 19);
verticalAcceleration = outputData(output, 18);
roll = outputData(output, 15);
pitch = outputData(output, 16);
loadResidual = sum(normalLoad, 2) - parameters.Mass .* ...
    (parameters.Gravity + verticalAcceleration);
minimumNormalLoad = min(normalLoad, [], "all");
maximumResidual = max(abs(loadResidual));
assessment = struct( ...
    "Passed", all(isfinite(normalLoad), "all") && ...
        minimumNormalLoad >= -1.0e-10 && maximumResidual < 1.0e-6, ...
    "MinimumNormalLoad", minimumNormalLoad, ...
    "MaximumLoadResidual", maximumResidual, ...
    "MaximumAbsRollAngle", max(abs(roll), [], "all"), ...
    "MaximumAbsPitchAngle", max(abs(pitch), [], "all"));
end

function output = simulateVehicle(modelName, stopTime, externalFx, externalFy, fixedStep)
if nargin < 5
    fixedStep = false;
end
time = [0; 0.099; 0.100; stopTime];
forceX = [0; 0; externalFx; externalFx];
forceY = [0; 0; externalFy; externalFy];
dataset = createInputDataset(modelName, time, forceX, forceY);
input = Simulink.SimulationInput(modelName);
input = input.setExternalInput(dataset);
input = input.setModelParameter( ...
    "StopTime", string(stopTime), ...
    "SaveOutput", "on", ...
    "OutputSaveName", "yout", ...
    "SaveFormat", "Dataset", ...
    "ReturnWorkspaceOutputs", "on");
if fixedStep
    input = input.setModelParameter( ...
        "SolverType", "Fixed-step", "Solver", "ode4", ...
        "FixedStep", "0.001");
end
result = sim(input);
output = result.yout;
end

function dataset = createInputDataset(modelName, time, forceX, forceY)
names = ["TireForceXWheel", "TireForceYWheel", ...
    "TireAligningMoment", "WheelSteerAngle", "WheelAppliedTorque", ...
    "ExternalForceXBody", "ExternalForceYBody", "ExternalYawMoment"];
widths = [4, 4, 4, 4, 4, 1, 1, 1];
if modelName == "Vehicle10DOF"
    names = [names, "DownforceFront", "DownforceRear", ...
        "RoadHeight", "RoadVelocity"];
    widths = [widths, 1, 1, 4, 4];
end

dataset = Simulink.SimulationData.Dataset;
for index = 1:numel(names)
    values = zeros(numel(time), widths(index));
    if names(index) == "ExternalForceXBody"
        values = forceX;
    elseif names(index) == "ExternalForceYBody"
        values = forceY;
    end
    dataset = dataset.addElement(timeseries(values, time), names(index));
end
end

function comparison = comparePlanarModels()
% Use the same deterministic integration grid so Memory diagnostics do not
% inherit different variable-step schedules from the extra vertical states.
output7 = simulateVehicle("Vehicle7DOF", 1.0, 600.0, 800.0, true);
output10 = simulateVehicle("Vehicle10DOF", 1.0, 600.0, 800.0, true);
grid = (0:0.002:1.0)';
outputNames = ["X", "Y", "Psi", "Ux", "Uy", "YawRate", ...
    "UxDot", "UyDot", "Ax", "Ay", "YawAcceleration", ...
    "WheelSpeed", "WheelVelocityXWheel", "WheelVelocityYWheel"];
maximumBySignal = zeros(numel(outputNames), 1);
planarIndices = [1, 2, 4, 5];
referencePlanar = zeros(numel(grid), numel(planarIndices));
candidatePlanar = zeros(numel(grid), numel(planarIndices));
for index = 1:numel(outputNames)
    values7 = interpolateOutput(output7, index, grid);
    values10 = interpolateOutput(output10, index, grid);
    maximumBySignal(index) = max(abs(values10 - values7), [], "all");
    planarColumn = find(planarIndices == index, 1);
    if ~isempty(planarColumn)
        referencePlanar(:, planarColumn) = values7;
        candidatePlanar(:, planarColumn) = values10;
    end
end
comparison = struct( ...
    "SignalNames", outputNames, ...
    "MaximumAbsoluteDifferenceBySignal", maximumBySignal, ...
    "MaximumAbsoluteDifference", max(maximumBySignal), ...
    "Time", grid, ...
    "PlanarSignalNames", outputNames(planarIndices), ...
    "Vehicle7DOFPlanar", referencePlanar, ...
    "Vehicle10DOFPlanar", candidatePlanar);
end

function saveVerificationFigures(resultFolder, comparison, loadTime, normalLoad)
comparisonFigure = figure(Visible = "off", Color = "white", ...
    Name = "Vehicle10DOF 7DOF and 10DOF planar comparison");
layout = tiledlayout(comparisonFigure, 2, 2, ...
    TileSpacing = "compact", Padding = "compact");
for index = 1:numel(comparison.PlanarSignalNames)
    axisHandle = nexttile(layout);
    plot(axisHandle, comparison.Time, ...
        comparison.Vehicle7DOFPlanar(:, index), "LineWidth", 1.4);
    hold(axisHandle, "on");
    plot(axisHandle, comparison.Time, ...
        comparison.Vehicle10DOFPlanar(:, index), "--", "LineWidth", 1.1);
    set(axisHandle, Color = "white", XColor = "black", YColor = "black");
    grid(axisHandle, "on");
    xlabel(axisHandle, "Time (s)");
    ylabel(axisHandle, comparison.PlanarSignalNames(index));
    legendHandle = legend(axisHandle, ["7DOF", "10DOF"], ...
        Location = "best");
    set(legendHandle, Color = "white", TextColor = "black");
end
titleHandle = title(layout, ...
    "Identical-input planar regression (1 ms fixed step)");
titleHandle.Color = "black";
savefig(comparisonFigure, fullfile(resultFolder, ...
    "Vehicle_7DOF_10DOF_Planar_Comparison.fig"));
close(comparisonFigure);

loadFigure = figure(Visible = "off", Color = "white", ...
    Name = "Vehicle10DOF dynamic wheel loads");
loadAxis = axes(loadFigure);
plot(loadAxis, loadTime, normalLoad, LineWidth = 1.3);
set(loadAxis, Color = "white", XColor = "black", YColor = "black");
grid(loadAxis, "on");
xlabel(loadAxis, "Time (s)");
ylabel(loadAxis, "Normal load (N)");
title(loadAxis, "10DOF combined Fx/Fy-step wheel loads");
legendHandle = legend(loadAxis, ["FL", "FR", "RL", "RR"], ...
    Location = "best");
set(legendHandle, Color = "white", TextColor = "black");
savefig(loadFigure, fullfile(resultFolder, ...
    "Vehicle_10DOF_Dynamic_Wheel_Loads.fig"));
close(loadFigure);
end

function values = interpolateOutput(dataset, index, grid)
signal = dataset.getElement(index).Values;
data = squeeze(signal.Data);
if size(data, 1) ~= numel(signal.Time)
    data = data.';
end
values = interp1(signal.Time, data, grid, "linear");
end

function [frequency, shape] = calculateModes(parameters)
distanceRear = parameters.Wheelbase - parameters.CGToFrontAxle;
xCorner = [parameters.CGToFrontAxle; parameters.CGToFrontAxle; ...
    -distanceRear; -distanceRear];
yCorner = [parameters.TrackFront / 2; -parameters.TrackFront / 2; ...
    parameters.TrackRear / 2; -parameters.TrackRear / 2];
geometry = [ones(4, 1), yCorner, -xCorner];
stiffness = geometry.' * diag(parameters.WheelRate) * geometry;
stiffness(2, 2) = stiffness(2, 2) + ...
    sum(parameters.AdditionalRollStiffness);
mass = diag([parameters.Mass, parameters.InertiaRoll, ...
    parameters.InertiaPitch]);
[shape, eigenvalue] = eig(stiffness, mass);
[frequency, order] = sort(sqrt(diag(eigenvalue)) / (2 * pi));
shape = shape(:, order);
end

function closedLoop = runClosedLoopSmoke()
installTorqueVectoringControlData();
vehicleParameters = loadTorqueVectoringVehicleParameters();
scenario = createPathTrackingSkidpadScenario();
caseDefinition = struct( ...
    "ModelName", "FSAE_Vehicle10DOF_ClosedLoop", ...
    "Scenario", scenario, ...
    "TireModel", "MF62", ...
    "EnableTV", false);
input = createTorqueVectoringSimulationInput(caseDefinition, vehicleParameters);
input = input.setModelParameter( ...
    "StopTime", "1.0", ...
    "SaveOutput", "on", ...
    "OutputSaveName", "yout", ...
    "SaveFormat", "Dataset");
result = sim(input);
vehicleState = result.yout.getElement(1).Values;
normalLoad = squeeze(vehicleState.NormalLoad.Data);
roll = squeeze(vehicleState.RollAngle.Data);
pitch = squeeze(vehicleState.PitchAngle.Data);
closedLoop = struct( ...
    "Executed", true, ...
    "Passed", all(isfinite(normalLoad), "all"), ...
    "MinimumNormalLoad", min(normalLoad, [], "all"), ...
    "MaximumAbsRollAngle", max(abs(roll), [], "all"), ...
    "MaximumAbsPitchAngle", max(abs(pitch), [], "all"));
end

function value = finalValue(dataset, index)
data = outputData(dataset, index);
value = data(end, :).';
end

function data = outputData(dataset, index)
signal = dataset.getElement(index).Values;
data = squeeze(signal.Data);
if size(data, 1) ~= numel(signal.Time)
    data = data.';
end
end
