function [scenario, plan] = applyGGVReferenceSpeed( ...
        scenario, parameters, cfg, options)
%APPLYGGVREFERENCESPEED Build a track-varying reference-speed profile.
%   [SCENARIO, PLAN] = APPLYGGVREFERENCESPEED(SCENARIO, PARAMETERS, CFG)
%   generates or reuses a speed-dependent GGV surface, applies the configured
%   constraint margin, and runs curvature plus forward/backward speed planning.
%   The resulting profile replaces SCENARIO.Track.ReferenceSpeed. No manually
%   selected target speed is used.
%
%   OPTIONS.GGV supplies a precomputed GGV surface and bypasses generation and
%   caching. This is useful for deterministic unit tests and offline workflows.

arguments
    scenario (1, 1) struct
    parameters (1, 1) struct
    cfg (1, 1) struct
    options.GGV (1, 1) struct = struct()
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "ggv"), "-begin");
addpath(fullfile(projectRoot, "scripts", "lap_time"), "-begin");
addpath(fullfile(projectRoot, "scripts", "tire"), "-begin");

planner = cfg.SpeedPlanner;
if isempty(fieldnames(options.GGV))
    [ggv, ggvSource, cacheKey] = loadOrGenerateGGV( ...
        parameters, scenario, cfg, projectRoot);
else
    ggv = options.GGV;
    ggvSource = "provided";
    cacheKey = "";
end
validateGGVContract(ggv);

benchmarkMaximumSpeed = max(double(ggv.Speed(:)));
benchmarkProfile = calculateSpeedProfile(scenario.Track, ggv, ...
    InitialSpeed = 0.0, ...
    FinalSpeed = benchmarkMaximumSpeed, ...
    PassCount = planner.PassCount, ...
    MinimumSpeed = 0.0, ...
    MaximumSpeed = benchmarkMaximumSpeed, ...
    UseReferenceSpeed = false);
assert(benchmarkProfile.IsValid && isfinite(benchmarkProfile.LapTime), ...
    "FSAE:Lap:InvalidGGVBenchmark", ...
    "Raw GGV benchmark planning failed: %s", ...
    benchmarkProfile.FailureReason);

planningGGV = applyConstraintScale(ggv, planner.ConstraintScale);
[planningGGV, driverLimits] = applyDriverLimits(planningGGV, cfg);
planningTrack = scenario.Track;
usesRacingLine = all(isfield(planningTrack, ...
    ["RacingLineCurvature", "RacingLineSampleDistance", ...
    "RacingLineLength"]));
if usesRacingLine
    usesProtectedPlanningLine = all(isfield(planningTrack, ...
        ["RacingLinePlanningCurvature", ...
        "RacingLinePlanningSampleDistance", ...
        "RacingLinePlanningLength"]));
    if usesProtectedPlanningLine
        planningTrack.Curvature = ...
            planningTrack.RacingLinePlanningCurvature;
        planningTrack.SampleDistance = ...
            planningTrack.RacingLinePlanningSampleDistance;
        planningTrack.Length = planningTrack.RacingLinePlanningLength;
    else
        planningTrack.Curvature = planningTrack.RacingLineCurvature;
        planningTrack.SampleDistance = ...
            planningTrack.RacingLineSampleDistance;
        planningTrack.Length = planningTrack.RacingLineLength;
    end
end
[planningTrack, curvatureProtection] = applyHighCurvatureProtection( ...
    planningTrack, planner);
boundaryMode = "periodic_closed_track";
if ~scenario.Track.IsClosed
    boundaryMode = "open_track";
elseif double(scenario.NumberOfLaps) == 1
    % Autocross is geometrically closed but starts from rest and ends after
    % one lap. Treating the planning pass as open preserves that start bound.
    planningTrack.IsClosed = false;
    boundaryMode = "single_lap_standing_start";
end

maximumSpeed = min(max(double(planningGGV.Speed(:))), ...
    driverLimits.MaximumSpeed * driverLimits.SpeedSafetyFactor);
initialSpeed = max(0.0, double(scenario.InitialState.Ux));
profile = calculateSpeedProfile(planningTrack, planningGGV, ...
    InitialSpeed = initialSpeed, ...
    FinalSpeed = maximumSpeed, ...
    PassCount = planner.PassCount, ...
    MinimumSpeed = 0.0, ...
    MaximumSpeed = maximumSpeed, ...
    UseReferenceSpeed = false);
assert(profile.IsValid && all(isfinite(profile.Speed)), ...
    "FSAE:Lap:InvalidGGVSpeedProfile", ...
    "GGV speed planning failed: %s", profile.FailureReason);
assert(numel(profile.Speed) == numel(scenario.Track.Curvature), ...
    "FSAE:Lap:GGVSpeedProfileSize", ...
    "The GGV speed profile must match the time-domain track sample count.");

scenario.Track.ReferenceSpeed = double(profile.Speed(:));
if isfield(scenario.Track, "TargetSpeed")
    scenario.Track = rmfield(scenario.Track, "TargetSpeed");
end
scenario.ReferenceSpeedSource = ...
    "speed-dependent GGV, track curvature, and forward/backward planning";
scenario.Track.ReferenceSpeedSource = scenario.ReferenceSpeedSource;

if isfield(planningTrack, "Length")
    planningTrackLength = double(planningTrack.Length);
else
    segmentCount = numel(planningTrack.Curvature) - ...
        double(~logical(planningTrack.IsClosed));
    planningTrackLength = max(0, segmentCount) * ...
        double(planningTrack.SampleDistance);
end

metadata = struct( ...
    "Method", "GGV curvature limit with forward/backward propagation", ...
    "GGVSource", ggvSource, ...
    "GGVCacheKey", cacheKey, ...
    "BoundaryMode", boundaryMode, ...
    "RacingLineUsed", usesRacingLine, ...
    "PlanningTrackLength", planningTrackLength, ...
    "ConstraintScale", double(planner.ConstraintScale), ...
    "ReferenceLimitSource", driverLimits.Source, ...
    "DriverMaximumSpeed", driverLimits.MaximumSpeed, ...
    "DriverMaximumAcceleration", driverLimits.MaximumAcceleration, ...
    "DriverPlanningDeceleration", driverLimits.PlanningDeceleration, ...
    "DriverLateralAccelerationLimit", ...
        driverLimits.LateralAccelerationLimit, ...
    "DriverSpeedSafetyFactor", driverLimits.SpeedSafetyFactor, ...
    "DriverEffectiveLateralAccelerationLimit", ...
        driverLimits.LateralAccelerationLimit * ...
        driverLimits.SpeedSafetyFactor^2, ...
    "HighCurvatureThreshold", curvatureProtection.Threshold, ...
    "HighCurvatureTransitionStart", ...
        curvatureProtection.TransitionStart, ...
    "HighCurvatureSafetyFactor", curvatureProtection.SafetyFactor, ...
    "HighCurvatureProtectedPointCount", curvatureProtection.PointCount, ...
    "GGVMinimumSpeed", min(double(ggv.Speed(:))), ...
    "GGVMaximumSpeed", max(double(ggv.Speed(:))), ...
    "GGVSpeedPointCount", numel(ggv.Speed), ...
    "BenchmarkGGVLapTime", benchmarkProfile.LapTime, ...
    "BenchmarkGGVMaximumSpeed", max(benchmarkProfile.Speed), ...
    "MinimumReferenceSpeed", min(scenario.Track.ReferenceSpeed), ...
    "MaximumReferenceSpeed", max(scenario.Track.ReferenceSpeed), ...
    "PredictedLapTime", profile.LapTime, ...
    "IsPerformanceClaim", false);
scenario.SpeedPlannerMetadata = metadata;

plan = struct( ...
    "Profile", profile, ...
    "BenchmarkProfile", benchmarkProfile, ...
    "Metadata", metadata, ...
    "GGVDiagnostics", getFieldOrDefault(ggv, "Diagnostics", struct()));
end

function [track, protection] = applyHighCurvatureProtection(track, planner)
protection = struct("Threshold", Inf, "TransitionStart", Inf, ...
    "SafetyFactor", 1.0, "PointCount", 0);
if ~isfield(planner, "HighCurvatureThreshold") || ...
        ~isfield(planner, "HighCurvatureSafetyFactor")
    return
end
threshold = double(planner.HighCurvatureThreshold);
safetyFactor = double(planner.HighCurvatureSafetyFactor);
assert(isscalar(threshold) && isfinite(threshold) && threshold > 0, ...
    "FSAE:Lap:InvalidHighCurvatureThreshold", ...
    "SpeedPlanner.HighCurvatureThreshold must be positive and finite.");
assert(isscalar(safetyFactor) && isfinite(safetyFactor) && ...
    safetyFactor >= 1.0, ...
    "FSAE:Lap:InvalidHighCurvatureSafetyFactor", ...
    "SpeedPlanner.HighCurvatureSafetyFactor must be finite and >= 1.");
curvature = double(track.Curvature(:));
% Avoid a rigid speed-limit jump at one curvature sample. Protection ramps
% in over the final 10% below the threshold and reaches the configured
% factor at the threshold. This protects near-threshold bends without
% slowing the medium-curvature portions of the full lap.
transitionStart = 0.9 * threshold;
transitionWidth = max(threshold - transitionStart, eps);
blend = (abs(curvature) - transitionStart) / transitionWidth;
blend = min(1.0, max(0.0, blend));
blend = blend.^2 .* (3.0 - 2.0 * blend);
curvatureScale = 1.0 + (safetyFactor - 1.0) * blend;
protected = curvatureScale > 1.0 + eps;
curvature = curvatureScale .* curvature;
track.Curvature = curvature;
protection = struct("Threshold", threshold, ...
    "TransitionStart", transitionStart, ...
    "SafetyFactor", safetyFactor, "PointCount", nnz(protected));
end

function [ggv, source, cacheKey] = loadOrGenerateGGV( ...
        parameters, scenario, cfg, projectRoot)
planner = cfg.SpeedPlanner;
tireModel = normalizeGGVTireModel(cfg.Vehicle.TireModel);
config = createQuasiStaticConfiguration(parameters, ...
    TireModel = tireModel, ...
    DynamicsModel = cfg.Vehicle.DynamicsModel, ...
    AllocationMode = planner.AllocationMode, ...
    Environment = scenario.Environment, ...
    EnvelopePointCount = planner.EnvelopePointCount);

motorLimitedSpeed = config.Powertrain.MotorSpeedLimit * ...
    config.Tire.EffectiveRadius / config.Powertrain.GearRatio;
maximumSpeed = motorLimitedSpeed * planner.MotorSpeedUtilization;
assert(isfinite(maximumSpeed) && maximumSpeed > 0, ...
    "FSAE:Lap:InvalidGGVMaximumSpeed", ...
    "The motor-speed-derived GGV maximum speed must be positive and finite.");
speedGrid = makeSpeedGrid(maximumSpeed, planner.SpeedStep);

generation = struct( ...
    "SpeedGrid", speedGrid, ...
    "LateralPointCount", planner.LateralPointCount, ...
    "AllocationMode", upper(string(planner.AllocationMode)), ...
    "MaxLateralAcceleration", planner.MaxLateralAcceleration, ...
    "MaxLongitudinalAcceleration", planner.MaxLongitudinalAcceleration, ...
    "MaxBisectionIterations", planner.MaxBisectionIterations, ...
    "LongitudinalBracketPointCount", ...
        planner.LongitudinalBracketPointCount, ...
    "MaxSearchExpansionCount", planner.MaxSearchExpansionCount);
signature = struct( ...
    "SchemaVersion", "FSAE_GGV_SPEED_PLANNER_V1", ...
    "Configuration", config, ...
    "Generation", generation);
signatureJson = jsonencode(signature);
cacheKey = sha256Text(signatureJson);
cacheFolder = fullfile(projectRoot, "cache", "speed_planner");
cacheFile = fullfile(cacheFolder, "ggv_" + cacheKey + ".mat");

if planner.UseCache && isfile(cacheFile)
    cached = load(cacheFile, "ggv", "signatureJson");
    assert(isfield(cached, "ggv") && isfield(cached, "signatureJson") && ...
        string(cached.signatureJson) == string(signatureJson), ...
        "FSAE:Lap:InvalidGGVCache", ...
        "The GGV cache entry does not match its configuration signature: %s", ...
        cacheFile);
    ggv = cached.ggv;
    source = "cache";
    return
end

ggv = generateGGV(config, ...
    SpeedGrid = speedGrid, ...
    LateralPointCount = planner.LateralPointCount, ...
    AllocationMode = planner.AllocationMode, ...
    MaxLateralAcceleration = planner.MaxLateralAcceleration, ...
    MaxLongitudinalAcceleration = planner.MaxLongitudinalAcceleration, ...
    MaxBisectionIterations = planner.MaxBisectionIterations, ...
    LongitudinalBracketPointCount = ...
        planner.LongitudinalBracketPointCount, ...
    MaxSearchExpansionCount = planner.MaxSearchExpansionCount);
source = "generated";

if planner.UseCache
    if ~isfolder(cacheFolder)
        mkdir(cacheFolder);
    end
    save(cacheFile, "ggv", "signatureJson", "-v7.3");
end
end

function model = normalizeGGVTireModel(value)
switch lower(string(value))
    case "mf62"
        model = "MF62";
    case "ttc_map"
        model = "TTCMap";
    otherwise
        error("FSAE:Lap:GGVTireModel", ...
            "GGV speed planning requires Vehicle.TireModel mf62 or ttc_map; received '%s'.", ...
            value);
end
end

function speedGrid = makeSpeedGrid(maximumSpeed, step)
speedGrid = 0.0:double(step):double(maximumSpeed);
if isempty(speedGrid) || speedGrid(end) < maximumSpeed - 1.0e-9
    speedGrid(end + 1) = maximumSpeed;
else
    speedGrid(end) = maximumSpeed;
end
speedGrid = unique(speedGrid);
assert(numel(speedGrid) >= 2, "FSAE:Lap:GGVSpeedGrid", ...
    "The derived GGV speed grid must contain at least two points.");
end

function scaled = applyConstraintScale(ggv, scale)
scaled = ggv;
scaled.AyPositive = double(ggv.AyPositive) * scale;
scaled.AyNegative = double(ggv.AyNegative) * scale;
scaled.AxMax = double(ggv.AxMax) * scale;
scaled.AxMin = double(ggv.AxMin) * scale;
if isfield(ggv, "LateralAcceleration")
    scaled.LateralAcceleration = double(ggv.LateralAcceleration) * scale;
end
end

function [limited, limits] = applyDriverLimits(ggv, cfg)
% Keep the reference profile inside the closed-loop driver's command envelope.

limited = ggv;
limits = struct( ...
    "MaximumSpeed", Inf, ...
    "MaximumAcceleration", Inf, ...
    "PlanningDeceleration", Inf, ...
    "LateralAccelerationLimit", Inf, ...
    "SpeedSafetyFactor", 1.0, ...
    "Source", "unbounded");
maximumDriverSpeed = Inf;
maximumDriverAcceleration = Inf;
maximumDriverDeceleration = Inf;
if isfield(cfg, "Driver")
    driver = cfg.Driver;
    maximumDriverSpeed = positiveFieldOrInf(driver, "MaximumSpeed", "Driver");
    maximumDriverAcceleration = positiveFieldOrInf( ...
        driver, "MaximumAcceleration", "Driver");
    maximumDriverDeceleration = positiveFieldOrInf( ...
        driver, "MaximumDeceleration", "Driver");
end

referenceFields = ["ReferenceMaximumSpeed", ...
    "ReferenceMaximumAcceleration", "ReferencePlanningDeceleration", ...
    "ReferenceLateralAccelerationLimit", "ReferenceSpeedSafetyFactor"];
hasReferenceField = false(size(referenceFields));
if isfield(cfg, "SpeedPlanner")
    hasReferenceField = isfield(cfg.SpeedPlanner, cellstr(referenceFields));
end
assert(~any(hasReferenceField) || all(hasReferenceField), ...
    "FSAE:Lap:IncompleteReferenceDriverLimits", ...
    "SpeedPlanner reference-driver limits must be configured as a complete set.");

if all(hasReferenceField)
    planner = cfg.SpeedPlanner;
    limits.MaximumSpeed = min(maximumDriverSpeed, positiveFieldOrInf( ...
        planner, "ReferenceMaximumSpeed", "SpeedPlanner"));
    limits.MaximumAcceleration = min(maximumDriverAcceleration, ...
        positiveFieldOrInf(planner, ...
            "ReferenceMaximumAcceleration", "SpeedPlanner"));
    limits.PlanningDeceleration = min(maximumDriverDeceleration, ...
        positiveFieldOrInf(planner, ...
            "ReferencePlanningDeceleration", "SpeedPlanner"));
    limits.LateralAccelerationLimit = positiveFieldOrInf( ...
        planner, "ReferenceLateralAccelerationLimit", "SpeedPlanner");
    limits.SpeedSafetyFactor = double( ...
        planner.ReferenceSpeedSafetyFactor);
    limits.Source = "SpeedPlanner.Reference";
elseif isfield(cfg, "Driver")
    driver = cfg.Driver;
    limits.MaximumSpeed = maximumDriverSpeed;
    limits.MaximumAcceleration = maximumDriverAcceleration;
    planningDeceleration = positiveFieldOrInf( ...
        driver, "PlanningDeceleration", "Driver");
    limits.PlanningDeceleration = min( ...
        maximumDriverDeceleration, planningDeceleration);
    limits.LateralAccelerationLimit = positiveFieldOrInf( ...
        driver, "LateralAccelerationLimit", "Driver");
    if isfield(driver, "SpeedSafetyFactor")
        limits.SpeedSafetyFactor = double(driver.SpeedSafetyFactor);
    end
    limits.Source = "Driver";
end
if limits.Source ~= "unbounded"
    assert(isscalar(limits.SpeedSafetyFactor) && ...
        isfinite(limits.SpeedSafetyFactor) && ...
        limits.SpeedSafetyFactor > 0 && limits.SpeedSafetyFactor <= 1, ...
        "FSAE:Lap:InvalidSpeedSafetyFactor", ...
        "%s speed safety factor must be in (0, 1].", limits.Source);
end

effectiveLateralLimit = limits.LateralAccelerationLimit * ...
    limits.SpeedSafetyFactor^2;
limited.AyPositive = min(double(limited.AyPositive), ...
    effectiveLateralLimit);
limited.AyNegative = min(double(limited.AyNegative), ...
    effectiveLateralLimit);
limited.AxMax = min(double(limited.AxMax), ...
    limits.MaximumAcceleration);
limited.AxMin = max(double(limited.AxMin), ...
    -limits.PlanningDeceleration);
if isfield(limited, "LateralAcceleration")
    limited.LateralAcceleration = min( ...
        max(double(limited.LateralAcceleration), ...
            -effectiveLateralLimit), ...
        effectiveLateralLimit);
end
end

function value = positiveFieldOrInf(data, fieldName, groupName)
value = Inf;
if ~isfield(data, fieldName)
    return
end
candidate = double(data.(fieldName));
assert(isscalar(candidate) && isfinite(candidate) && candidate > 0, ...
    "FSAE:Lap:InvalidDriverLimit", ...
    "%s.%s must be a positive finite scalar.", groupName, fieldName);
value = candidate;
end

function validateGGVContract(ggv)
required = ["Speed", "AyPositive", "AyNegative", ...
    "LateralFraction", "AxMax", "AxMin"];
assert(all(isfield(ggv, cellstr(required))), "FSAE:Lap:GGVContract", ...
    "GGV is missing required fields: %s", ...
    strjoin(required(~isfield(ggv, cellstr(required))), ", "));
speed = double(ggv.Speed(:));
assert(numel(speed) >= 2 && all(isfinite(speed)) && ...
    all(speed >= 0) && all(diff(speed) > 0), ...
    "FSAE:Lap:GGVSpeedGrid", ...
    "GGV.Speed must be a finite, nonnegative, strictly increasing vector.");
assert(numel(ggv.AyPositive) == numel(speed) && ...
    numel(ggv.AyNegative) == numel(speed), ...
    "FSAE:Lap:GGVLateralSize", ...
    "GGV lateral limits must match the speed-grid length.");
assert(size(ggv.AxMax, 1) == numel(speed) && ...
    size(ggv.AxMin, 1) == numel(speed) && ...
    size(ggv.AxMax, 2) == numel(ggv.LateralFraction) && ...
    isequal(size(ggv.AxMax), size(ggv.AxMin)), ...
    "FSAE:Lap:GGVLongitudinalSize", ...
    "GGV longitudinal bounds must match Speed and LateralFraction.");
end

function key = sha256Text(value)
bytes = unicode2native(char(value), "UTF-8");
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(bytes);
raw = typecast(int8(digest.digest()), "uint8");
key = lower(string(reshape(dec2hex(raw, 2).', 1, [])));
end

function value = getFieldOrDefault(data, fieldName, defaultValue)
if isfield(data, fieldName)
    value = data.(fieldName);
else
    value = defaultValue;
end
end
