function [in, applied] = applyReferenceDriverConfiguration( ...
        in, driver, scenario, modelName)
%APPLYREFERENCEDRIVERCONFIGURATION Configure the reference-speed driver.
%   Keeps the PathTrackingDriver, top-model track projection, and downstream
%   TorqueVectoring controller limits on one consistent configuration contract.

arguments
    in (1, 1) Simulink.SimulationInput
    driver (1, 1) struct
    scenario (1, 1) struct
    modelName (1, 1) string
end

requiredDriverFields = [ ...
    "HeadingGain", "CrossTrackGain", ...
    "MaximumSteeringRate", "MaximumSteeringAngle", ...
    "MinimumSteeringSpeed", "ProjectionSearchDistance", ...
    "MinimumSteeringPreview", "SteeringPreviewTime", ...
    "MaximumSteeringPreview", "MaximumSpeed", ...
    "MaximumAcceleration", ...
    "MaximumDeceleration", "SpeedKp", "SpeedKi", ...
    "AntiWindupGain"];
missing = requiredDriverFields( ...
    ~isfield(driver, cellstr(requiredDriverFields)));
assert(isempty(missing), "FSAE:ReferenceDriver:MissingConfig", ...
    "Reference-speed driver configuration is missing: %s.", ...
    strjoin(missing, ", "));

sampleDistance = double(scenario.Track.SampleDistance);
assert(isscalar(sampleDistance) && isfinite(sampleDistance) && ...
    sampleDistance > 0, "FSAE:ReferenceDriver:SampleDistance", ...
    "Track.SampleDistance must be a positive finite scalar.");
projectionWindow = max(5, ...
    ceil(double(driver.ProjectionSearchDistance) / sampleDistance));
maximumPreviewTime = double(driver.MaximumSteeringPreview) / ...
    max(double(driver.MaximumSpeed), double(driver.MinimumSteeringSpeed));
effectivePreviewTime = min( ...
    double(driver.SteeringPreviewTime), maximumPreviewTime);

pathTrackingVariables = struct( ...
    "PathTrackingHeadingGain", double(driver.HeadingGain), ...
    "PathTrackingCrossTrackGain", double(driver.CrossTrackGain), ...
    "PathTrackingMaximumSteeringRate", double(driver.MaximumSteeringRate), ...
    "PathTrackingMaximumSteeringAngle", double(driver.MaximumSteeringAngle), ...
    "PathTrackingMinimumSteeringSpeed", double(driver.MinimumSteeringSpeed), ...
    "PathTrackingMaximumAcceleration", double(driver.MaximumAcceleration), ...
    "PathTrackingMaximumDeceleration", double(driver.MaximumDeceleration), ...
    "PathTrackingSpeedKp", double(driver.SpeedKp), ...
    "PathTrackingSpeedKi", double(driver.SpeedKi), ...
    "PathTrackingAntiWindupGain", double(driver.AntiWindupGain));
topModelVariables = struct( ...
    "PathTrackingProjectionSearchWindow", projectionWindow, ...
    "PathTrackingMinLookahead", double(driver.MinimumSteeringPreview), ...
    "PathTrackingLookaheadTime", effectivePreviewTime);
baseVariables = struct( ...
    "TorqueVectoringEnableTV", false, ...
    "TorqueVectoringMaximumAcceleration", double(driver.MaximumAcceleration), ...
    "TorqueVectoringMaximumDeceleration", double(driver.MaximumDeceleration));

in = setWorkspaceVariables(in, pathTrackingVariables, ...
    "PathTrackingDriver");
in = setWorkspaceVariables(in, topModelVariables, modelName);
in = setWorkspaceVariables(in, baseVariables, "");
applied = struct( ...
    "PathTrackingDriver", pathTrackingVariables, ...
    "TopModel", topModelVariables, ...
    "BaseWorkspace", baseVariables);
end

function in = setWorkspaceVariables(in, variables, workspace)
variableNames = string(fieldnames(variables));
for variableName = variableNames.'
    if strlength(workspace) == 0
        in = in.setVariable(variableName, variables.(variableName));
    else
        in = in.setVariable(variableName, variables.(variableName), ...
            Workspace = workspace);
    end
end
end
