function [in, selection] = createLapSimulationInput(scenario, parameters, cfg)
%CREATELAPSIMULATIONINPUT 创建可选择 7DOF/10DOF 的闭环仿真输入。
%   IN = CREATELAPSIMULATIONINPUT(SCENARIO, PARAMETERS, CFG) 在现有
%   createPathTrackingSimulationInput 的基础上设置成对的控制器/车辆顶层模型、赛道、
%   环境、车辆参数、轮胎模型和停止时间。
%   adaptive_autocross 使用 UnifiedControlVehicleController，同时保持
%   7DOF/10DOF Plant 的控制接口一致。长度单位 m，时间单位 s，速度单位 m/s。
%
%   该函数只配置 Simulink.SimulationInput，不启动仿真；仿真由
%   runLapSimulation.m 通过 simulation(IN) 或 sim(IN) 启动。
%   四轮轮胎选择和执行器向量顺序固定为 [FL, FR, RL, RR]。

arguments
    scenario (1, 1) struct
    parameters (1, 1) struct
    cfg (1, 1) struct
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
selection = resolveVehicleDynamicsModel(cfg.Vehicle.DynamicsModel);
driverModel = "reference_speed";
if isfield(cfg.Driver, "Model")
    driverModel = lower(string(cfg.Driver.Model));
end
if driverModel == "adaptive_autocross"
    selection.TopModel = "FSAE_AdaptiveAutocross_" + selection.Name;
    selection.DriverModel = "AdaptiveAutocrossDriver";
    selection.ControllerModel = "UnifiedControlVehicleController";
else
    selection.DriverModel = "TorqueVectoringPathTrackingDriver";
    selection.ControllerModel = "TorqueVectoringVehicleController";
end
modelName = selection.TopModel;
modelPath = fullfile(projectRoot, "models", "top", modelName + ".slx");
assert(isfile(modelPath), "FSAE:Lap:MissingTopModel", ...
    "所选顶层闭环模型不存在：%s。", modelPath);
assertTopModelReferences(modelName, modelPath, selection.DriverModel, ...
    selection.ControllerModel);

modelMode = mapTireModel(cfg.Vehicle.TireModel);
tireSelection = struct( ...
    "ModelMode", uint8(modelMode), ...
    "ModelModeMeaning", "0=TireSimple, 1=TireMF62, 2=TireTTCMap");

in = createPathTrackingSimulationInput(scenario, parameters, ...
    ModelName = modelName, TireSelection = tireSelection);
if driverModel == "adaptive_autocross"
    in = setAdaptiveDriverVariables(in, scenario, parameters, cfg.Driver);
    in = setAdaptiveUnifiedControlVariables(in, parameters, cfg.Driver);
else
    in = applyReferenceDriverConfiguration( ...
        in, cfg.Driver, scenario, modelName);
end
if cfg.Simulation.SignalLogging
    signalLogging = "on";
else
    signalLogging = "off";
end
in = in.setModelParameter( ...
    SignalLogging = signalLogging, ...
    Decimation = string(cfg.Simulation.OutputDecimation));
if cfg.Simulation.SolverProfile == "fast"
    in = in.setModelParameter(RelTol = "1e-2");
else
    in = in.setModelParameter(RelTol = "1e-3");
end
if isfinite(cfg.Simulation.StopTime)
    in = in.setModelParameter(StopTime = string(cfg.Simulation.StopTime));
end
in = in.setModelParameter(EnablePacing = "off");
end

function assertTopModelReferences(modelName, modelPath, expectedDriver, ...
        expectedController)
load_system(modelPath);
modelReferences = find_system(modelName, ...
    "SearchDepth", 1, "BlockType", "ModelReference");
referencedModels = strings(size(modelReferences));
for index = 1:numel(modelReferences)
    referencedModels(index) = string(get_param( ...
        modelReferences{index}, "ModelName"));
end
assert(any(referencedModels == expectedDriver), ...
    "FSAE:Lap:WrongTopDriver", ...
    "Top model %s does not reference required driver %s.", ...
    modelName, expectedDriver);
assert(any(referencedModels == expectedController), ...
    "FSAE:Lap:WrongTopController", ...
    "Top model %s does not reference required controller %s.", ...
    modelName, expectedController);
end

function in = setAdaptiveDriverVariables(in, scenario, parameters, driver)
wheelbase = requiredNumericValue(parameters, "Vehicle", "Wheelbase");
frontAxleDistance = requiredNumericValue( ...
    parameters, "Vehicle", "CGToFrontAxle");
rearAxleDistance = wheelbase - frontAxleDistance;
assert(frontAxleDistance > 0 && rearAxleDistance > 0, ...
    "FSAE:AAD:InvalidAxleGeometry", ...
    "CG-to-axle distances must be positive and sum to the wheelbase.");
frontHalfEnvelope = 0.5 * requiredNumericValue( ...
    parameters, "Vehicle", "TrackFront") + ...
    0.5 * driver.TireSectionWidth;
rearHalfEnvelope = 0.5 * requiredNumericValue( ...
    parameters, "Vehicle", "TrackRear") + ...
    0.5 * driver.TireSectionWidth;
projectionWindow = max(5, ceil(driver.ProjectionSearchDistance / ...
    double(scenario.Track.SampleDistance)));
curvatureCoverage = (2 * driver.CurvatureFilterHalfWindow + 1) * ...
    double(scenario.Track.SampleDistance);
assert(driver.SpeedPreviewStep <= curvatureCoverage, ...
    "FSAE:AAD:CurvaturePreviewGap", ...
    ["SpeedPreviewStep exceeds the curvature-envelope coverage; " ...
    "narrow curvature peaks could be skipped."]);
variables = struct( ...
    "AADControlSampleTime", 0.01, ...
    "AADWheelbase", wheelbase, ...
    "AADCGToFrontAxle", frontAxleDistance, ...
    "AADCGToRearAxle", rearAxleDistance, ...
    "AADFrontHalfEnvelope", frontHalfEnvelope, ...
    "AADRearHalfEnvelope", rearHalfEnvelope, ...
    "AADProjectionSearchWindow", projectionWindow, ...
    "AADMinimumSteeringPreview", driver.MinimumSteeringPreview, ...
    "AADSteeringPreviewTime", driver.SteeringPreviewTime, ...
    "AADMaximumSteeringPreview", driver.MaximumSteeringPreview, ...
    "AADHeadingGain", driver.HeadingGain, ...
    "AADCrossTrackGain", driver.CrossTrackGain, ...
    "AADBoundaryGain", driver.BoundaryGain, ...
    "AADMinimumSteeringSpeed", driver.MinimumSteeringSpeed, ...
    "AADMaximumSteeringAngle", driver.MaximumSteeringAngle, ...
    "AADMaximumSteeringRate", driver.MaximumSteeringRate, ...
    "AADSteeringWheelRatio", 1.0, ...
    "AADLateralAccelerationLimit", driver.LateralAccelerationLimit, ...
    "AADMaximumAcceleration", driver.MaximumAcceleration, ...
    "AADMaximumDeceleration", driver.MaximumDeceleration, ...
    "AADPlanningDeceleration", driver.PlanningDeceleration, ...
    "AADMaximumSpeed", driver.MaximumSpeed, ...
    "AADSpeedPreviewDistance", driver.SpeedPreviewDistance, ...
    "AADSpeedPreviewStep", driver.SpeedPreviewStep, ...
    "AADCurvatureFilterHalfWindow", driver.CurvatureFilterHalfWindow, ...
    "AADCurvatureSafetyFactor", driver.CurvatureSafetyFactor, ...
    "AADSpeedSafetyFactor", driver.SpeedSafetyFactor, ...
    "AADSpeedKp", driver.SpeedKp, ...
    "AADSpeedKi", driver.SpeedKi, ...
    "AADSpeedFeedforwardGain", driver.SpeedFeedforwardGain, ...
    "AADExitSpeedFeedforwardGain", ...
        driver.ExitSpeedFeedforwardGain, ...
    "AADPreviewBrakingEnabled", driver.PreviewBrakingEnabled, ...
    "AADPreviewBrakingActivationDistance", ...
        driver.PreviewBrakingActivationDistance, ...
    "AADPreviewBrakeFeedforwardGain", ...
        driver.PreviewBrakeFeedforwardGain, ...
    "AADPreviewBrakingDecelerationScale", ...
        driver.PreviewBrakingDecelerationScale, ...
    "AADAntiWindupGain", driver.AntiWindupGain, ...
    "AADReferencePathCurvatureBlendStart", ...
        driver.ReferencePathCurvatureBlendStart, ...
    "AADReferencePathCurvatureBlendEnd", ...
        driver.ReferencePathCurvatureBlendEnd, ...
    "AADReferencePathMaximumBlend", ...
        driver.ReferencePathMaximumBlend, ...
    "AADBoundaryPreviewDistance", driver.BoundaryPreviewDistance, ...
    "AADBoundaryReserve", driver.BoundaryReserve, ...
    "AADEmergencyBoundaryMargin", driver.EmergencyBoundaryMargin, ...
    "AADEnableTV", driver.EnableTV, ...
    "AADEnableTC", driver.EnableTC, ...
    "AADBrakePressurePerAcceleration", 1.0e4);
variableNames = string(fieldnames(variables));
for variableName = variableNames.'
    in = in.setVariable(variableName, variables.(variableName), ...
        Workspace = "AdaptiveAutocrossDriver");
end
end

function in = setAdaptiveUnifiedControlVariables(in, parameters, driver)
controlSampleTime = 0.005;
motorTorqueLimit = requiredNumericValue( ...
    parameters, "Powertrain", "MotorTorqueLimit");
motorResponseTime = requiredNumericValue( ...
    parameters, "Powertrain", "MotorResponseTime");
variables = struct( ...
    "UnifiedControlSampleTime", controlSampleTime, ...
    "UnifiedControlVehicleMass", requiredNumericValue( ...
        parameters, "Vehicle", "Mass"), ...
    "UnifiedControlGravity", 9.80665, ...
    "UnifiedControlWheelbase", requiredNumericValue( ...
        parameters, "Vehicle", "Wheelbase"), ...
    "UnifiedControlCGHeight", requiredNumericValue( ...
        parameters, "Vehicle", "CGHeight"), ...
    "UnifiedControlStaticLoadDistributionFront", requiredNumericValue( ...
        parameters, "Vehicle", "StaticLoadDistributionFront"), ...
    "UnifiedControlRollStiffnessDistributionFront", requiredNumericValue( ...
        parameters, "Vehicle", "RollStiffnessDistributionFront"), ...
    "UnifiedControlTrackFront", requiredNumericValue( ...
        parameters, "Vehicle", "TrackFront"), ...
    "UnifiedControlTrackRear", requiredNumericValue( ...
        parameters, "Vehicle", "TrackRear"), ...
    "UnifiedControlTireEffectiveRadius", requiredNumericValue( ...
        parameters, "Tire", "EffectiveRadius"), ...
    "UnifiedControlLowSpeedEpsilon", requiredNumericValue( ...
        parameters, "Tire", "LowSpeedEpsilon"), ...
    "UnifiedControlGearRatio", requiredNumericValue( ...
        parameters, "Powertrain", "GearRatio"), ...
    "UnifiedControlGearEfficiency", requiredNumericValue( ...
        parameters, "Powertrain", "GearEfficiency"), ...
    "UnifiedControlMotorTorqueLimit", motorTorqueLimit, ...
    "UnifiedControlMotorSpeedLimit", requiredNumericValue( ...
        parameters, "Powertrain", "MotorSpeedLimit"), ...
    "UnifiedControlInverterEfficiency", requiredNumericValue( ...
        parameters, "Powertrain", "InverterEfficiency"), ...
    "UnifiedControlDrivePowerLimit", requiredNumericValue( ...
        parameters, "Battery", "PowerLimitDrive"), ...
    "UnifiedControlRegenPowerLimit", requiredNumericValue( ...
        parameters, "Battery", "PowerLimitRegen"), ...
    "UnifiedControlBrakeMaxTorque", requiredNumericVector4( ...
        parameters, "Brake", "MaxTorquePerWheel"), ...
    "UnifiedControlBatterySOCUpperLimit", requiredNumericValue( ...
        parameters, "Battery", "SOCUpperLimit"), ...
    "UnifiedControlPowerEpsilon", requiredNumericValue( ...
        parameters, "Battery", "PowerEpsilon"), ...
    "UnifiedControlMotorTorqueRateLimit", motorTorqueLimit / ...
        max(motorResponseTime, controlSampleTime), ...
    "UnifiedControlFrictionEstimate", 1.0, ...
    "UnifiedControlTCSlipOn", 0.12, ...
    "UnifiedControlTCSlipOff", 0.08, ...
    "UnifiedControlTCSlipFullCut", 0.25, ...
    "UnifiedControlMinimumNormalLoad", 50.0, ...
    "UnifiedControlEnergyDriveFraction", 0.90, ...
    "UnifiedControlForcePriorityWeight", 1.0, ...
    "UnifiedControlYawPriorityWeight", 4.0, ...
    "UnifiedControlRegularizationWeight", 1.0e-4, ...
    "UnifiedControlAllocatorIterations", uint8(24), ...
    "UnifiedControlMaximumAcceleration", driver.MaximumAcceleration, ...
    "UnifiedControlMaximumDeceleration", driver.MaximumDeceleration, ...
    "TorqueVectoringControlSampleTime", controlSampleTime);
variableNames = string(fieldnames(variables));
for variableName = variableNames.'
    in = in.setVariable(variableName, variables.(variableName));
end
end

function value = requiredNumericValue(parameters, groupName, fieldName)
assert(isfield(parameters, groupName) && ...
    isfield(parameters.(groupName), fieldName), ...
    "FSAE:AAD:MissingParameter", ...
    "Missing adaptive-driver parameter %s.%s.", groupName, fieldName);
value = parameters.(groupName).(fieldName);
if isa(value, "Simulink.Parameter")
    value = value.Value;
elseif isstruct(value) && isfield(value, "Value")
    value = value.Value;
end
assert(isnumeric(value) && isscalar(value) && isfinite(value), ...
    "FSAE:AAD:InvalidParameter", ...
    "Adaptive-driver parameter %s.%s must be finite and scalar.", ...
    groupName, fieldName);
value = double(value);
end

function value = requiredNumericVector4(parameters, groupName, fieldName)
assert(isfield(parameters, groupName) && ...
    isfield(parameters.(groupName), fieldName), ...
    "FSAE:AAD:MissingParameter", ...
    "Missing adaptive-controller parameter %s.%s.", ...
    groupName, fieldName);
value = parameters.(groupName).(fieldName);
if isa(value, "Simulink.Parameter")
    value = value.Value;
elseif isstruct(value) && isfield(value, "Value")
    value = value.Value;
end
assert(isnumeric(value) && numel(value) == 4 && ...
    all(isfinite(value(:))), ...
    "FSAE:AAD:InvalidParameter", ...
    "Adaptive-controller parameter %s.%s must have four finite values.", ...
    groupName, fieldName);
value = reshape(double(value), 4, 1);
end

function modelMode = mapTireModel(tireModel)
tireModel = lower(string(tireModel));
validModels = ["simple", "mf62", "ttc_map"];
index = find(tireModel == validModels, 1);
if isempty(index)
    error("FSAE:Lap:InvalidTireModel", ...
        "Vehicle.TireModel 收到 '%s'，允许值为：simple、mf62、ttc_map。", ...
        tireModel);
end
modelMode = index - 1;
end
