function in = createPathTrackingSimulationInput(scenario, parameters, options)
%CREATEPathTrackingSIMULATIONINPUT Configure a repeatable PathTracking closed-loop simulation.
%   The track and environment are written explicitly to the top-model
%   workspace because those variables are owned there and would otherwise
%   shadow variables placed in the base workspace.

arguments
    scenario (1, 1) struct
    parameters (1, 1) struct
    options.ModelName (1, 1) string = "FSAE_PathTracking_ClosedLoop"
    options.TireSelection (1, 1) struct = struct("ModelMode", uint8(0))
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "track"));

in = Simulink.SimulationInput(options.ModelName);
parameterGroups = fieldnames(parameters);
for index = 1:numel(parameterGroups)
    groupName = parameterGroups{index};
    in = in.setVariable(groupName, parameters.(groupName));
end

in = in.setVariable("TireSelection", options.TireSelection);
in = in.setVariable("Vehicle7DOFInitialState", scenario.InitialState);
in = in.setVariable("PathTrackingWheelbase", ...
    requiredNumericValue(parameters, "Vehicle", "Wheelbase"), ...
    Workspace = "PathTrackingDriver");
in = in.setVariable("PathTrackingVehicleMass", ...
    requiredNumericValue(parameters, "Vehicle", "Mass"), ...
    Workspace = "PathTrackingVehicleController");
in = in.setVariable("PathTrackingTireEffectiveRadius", ...
    requiredNumericValue(parameters, "Tire", "EffectiveRadius"), ...
    Workspace = "PathTrackingVehicleController");
in = in.setVariable("PathTrackingGearRatio", ...
    requiredNumericValue(parameters, "Powertrain", "GearRatio"), ...
    Workspace = "PathTrackingVehicleController");
in = in.setVariable("PathTrackingGearEfficiency", ...
    requiredNumericValue(parameters, "Powertrain", "GearEfficiency"), ...
    Workspace = "PathTrackingVehicleController");
in = in.setVariable("PathTrackingMotorTorqueLimit", ...
    requiredNumericValue(parameters, "Powertrain", "MotorTorqueLimit"), ...
    Workspace = "PathTrackingVehicleController");
in = in.setVariable("PathTrackingTrackData", makePathTrackingTrackData(scenario.Track), ...
    Workspace=options.ModelName);
in = in.setVariable("PathTrackingEnvironment", scenario.Environment, ...
    Workspace=options.ModelName);
projectionSearchWindow = max(5, ...
    ceil(10.0 / double(scenario.Track.SampleDistance)));
in = in.setVariable("PathTrackingProjectionSearchWindow", ...
    projectionSearchWindow, Workspace=options.ModelName);
in = in.setModelParameter( ...
    StopTime=string(scenario.StopTime), ...
    ReturnWorkspaceOutputs="on", ...
    SaveOutput="on", ...
    OutputSaveName="yout", ...
    SignalLogging="on", ...
    SignalLoggingName="logsout", ...
    AlgebraicLoopMsg="error", ...
    BusObjectLabelMismatch="error", ...
    ZeroCrossAlgorithm="Adaptive", ...
    IgnoredZcDiagnostic="none");
end

function value = requiredNumericValue(parameters, groupName, fieldName)
assert(isfield(parameters, groupName) && ...
    isfield(parameters.(groupName), fieldName), ...
    "FSAE:PathTrackingMissingControllerParameter", ...
    "Missing PathTracking controller parameter %s.%s.", groupName, fieldName);
value = parameters.(groupName).(fieldName);
if isstruct(value) && isfield(value, "Value")
    value = value.Value;
end
assert(isnumeric(value) && isscalar(value) && isfinite(value), ...
    "FSAE:PathTrackingInvalidControllerParameter", ...
    "PathTracking controller parameter %s.%s must be a finite numeric scalar.", ...
    groupName, fieldName);
value = double(value);
end
