function [track, report] = planAdaptiveRacingLine(track, driver)
%PLANADAPTIVERACINGLINE Compute a width-constrained minimum-curvature line.
%   The physical centerline and widths remain unchanged. Additional
%   RacingLine* fields provide a smooth GGV speed-planning path inside the
%   original boundaries; online steering continues to track the physical
%   centerline. Positive offset is left of the centerline.

requiredTrackFields = ["X", "Y", "Heading", "Curvature", ...
    "LeftHalfWidth", "RightHalfWidth", "SampleDistance", ...
    "Length", "IsClosed"];
assert(all(isfield(track, cellstr(requiredTrackFields))), ...
    "FSAE:AAD:RacingLineTrackContract", ...
    "Track is missing fields required by the racing-line planner.");
requiredDriverFields = ["CGToFrontAxle", "CGToRearAxle", ...
    "FrontHalfEnvelope", "RearHalfEnvelope", ...
    "RacingLineBoundaryReserve", "RacingLineMaximumOffset", ...
    "RacingLineOffsetVariationWeight", ...
    "RacingLineMaximumOffsetRate", ...
    "RacingLineLockCurvatureThreshold", ...
    "RacingLineLockBufferDistance", ...
    "RacingLineCurvaturePenaltyWeight", ...
    "RacingLineStartLockDistance"];
assert(all(isfield(driver, cellstr(requiredDriverFields))), ...
    "FSAE:AAD:RacingLineConfig", ...
    "Driver is missing racing-line planner configuration.");
isClosed = logical(track.IsClosed);

x = double(track.X(:));
y = double(track.Y(:));
heading = double(track.Heading(:));
leftWidth = double(track.LeftHalfWidth(:));
rightWidth = double(track.RightHalfWidth(:));
sampleCount = numel(x);
assert(sampleCount >= 20 && numel(y) == sampleCount && ...
    numel(heading) == sampleCount && numel(leftWidth) == sampleCount && ...
    numel(rightWidth) == sampleCount, ...
    "FSAE:AAD:RacingLineTrackSize", ...
    "Racing-line track vectors must have the same length and at least 20 samples.");

maximumEnvelope = max(double(driver.FrontHalfEnvelope), ...
    double(driver.RearHalfEnvelope));
cgToFrontAxle = double(driver.CGToFrontAxle);
cgToRearAxle = double(driver.CGToRearAxle);
reserve = double(driver.RacingLineBoundaryReserve);
maximumOffset = double(driver.RacingLineMaximumOffset);
variationWeight = double(driver.RacingLineOffsetVariationWeight);
maximumOffsetRate = double(driver.RacingLineMaximumOffsetRate);
lockCurvatureThreshold = ...
    double(driver.RacingLineLockCurvatureThreshold);
lockBufferDistance = double(driver.RacingLineLockBufferDistance);
curvaturePenaltyWeight = ...
    double(driver.RacingLineCurvaturePenaltyWeight);
lockDistance = double(driver.RacingLineStartLockDistance);
assert(all(isfinite([maximumEnvelope, cgToFrontAxle, cgToRearAxle, ...
    reserve, maximumOffset, ...
    variationWeight, maximumOffsetRate, lockCurvatureThreshold, ...
    lockBufferDistance, curvaturePenaltyWeight, lockDistance])) && ...
    maximumEnvelope > 0.0 && cgToFrontAxle > 0.0 && ...
    cgToRearAxle > 0.0 && ...
    reserve >= 0.0 && maximumOffset > 0.0 && variationWeight >= 0.0 && ...
    maximumOffsetRate > 0.0 && lockCurvatureThreshold > 0.0 && ...
    lockBufferDistance >= 0.0 && curvaturePenaltyWeight >= 0.0 && ...
    lockDistance >= 0.0, ...
    "FSAE:AAD:RacingLineConfigValue", ...
    "Racing-line configuration values are invalid.");

leftBound = min(maximumOffset, max(0.0, ...
    leftWidth - maximumEnvelope - reserve));
rightBound = min(maximumOffset, max(0.0, ...
    rightWidth - maximumEnvelope - reserve));
lowerBound = -rightBound;
upperBound = leftBound;

sampleDistance = double(track.SampleDistance);
lockCount = min(floor(sampleCount / 4), ...
    ceil(lockDistance / max(sampleDistance, eps)));
if lockCount > 0
    lowerBound([1:lockCount, sampleCount-lockCount+1:sampleCount]) = 0.0;
    upperBound([1:lockCount, sampleCount-lockCount+1:sampleCount]) = 0.0;
end
absoluteCurvature = abs(double(track.Curvature(:)));
lockBufferCount = min(sampleCount - 1, ...
    ceil(lockBufferDistance / max(sampleDistance, eps)));
thresholdLocked = absoluteCurvature >= lockCurvatureThreshold;
planningLocked = expandBooleanNeighborhood( ...
    thresholdLocked, lockBufferCount, isClosed);
planningLowerBound = lowerBound;
planningUpperBound = upperBound;
planningLowerBound(planningLocked) = 0.0;
planningUpperBound(planningLocked) = 0.0;
transitionStart = 0.95 * lockCurvatureThreshold;
curvatureActivation = (absoluteCurvature - transitionStart) / ...
    max(lockCurvatureThreshold - transitionStart, eps);
curvatureActivation = min(1.0, max(0.0, curvatureActivation));
softCurvatureActivation = expandWeightedNeighborhood( ...
    curvatureActivation, lockBufferCount, isClosed);

identity = speye(sampleCount);
[firstDifference, secondDifference] = ...
    pathDifferenceMatrices(sampleCount, isClosed);
maximumOffsetStep = maximumOffsetRate * sampleDistance;
inequalityMatrix = [firstDifference; -firstDifference];
inequalityBound = maximumOffsetStep * ...
    ones(2 * size(firstDifference, 1), 1);

normalX = -sin(heading);
normalY = cos(heading);
pathXMatrix = secondDifference * spdiags(normalX, 0, ...
    sampleCount, sampleCount);
pathYMatrix = secondDifference * spdiags(normalY, 0, ...
    sampleCount, sampleCount);
pathXConstant = secondDifference * x;
pathYConstant = secondDifference * y;
regularization = 1.0e-8;
baseHessian = 2.0 * (pathXMatrix.' * pathXMatrix + ...
    pathYMatrix.' * pathYMatrix + ...
    variationWeight * (firstDifference.' * firstDifference) + ...
    regularization * identity);
curvaturePenalty = curvaturePenaltyWeight * ...
    softCurvatureActivation.^2;
hessian = baseHessian + 2.0 * ...
    spdiags(curvaturePenalty, 0, sampleCount, sampleCount);
hessian = 0.5 * (hessian + hessian.');
baseHessian = 0.5 * (baseHessian + baseHessian.');
linearTerm = 2.0 * (pathXMatrix.' * pathXConstant + ...
    pathYMatrix.' * pathYConstant);

initialOffset = zeros(sampleCount, 1);
initialObjective = 0.5 * initialOffset.' * hessian * initialOffset + ...
    linearTerm.' * initialOffset;
assert(isfinite(initialObjective) && ...
    all(initialOffset >= lowerBound) && all(initialOffset <= upperBound), ...
    "FSAE:AAD:RacingLineInitialPoint", ...
    "The racing-line initial point must be finite and feasible.");
options = optimoptions("quadprog", ...
    "Algorithm", "interior-point-convex", ...
    "Display", "off", ...
    "MaxIterations", 200, ...
    "OptimalityTolerance", 1.0e-8, ...
    "ConstraintTolerance", 1.0e-8);
[offset, objective, exitFlag, output] = quadprog(hessian, linearTerm, ...
    inequalityMatrix, inequalityBound, [], [], lowerBound, upperBound, ...
    initialOffset, options);
assert(exitFlag > 0 && all(isfinite(offset)), ...
    "FSAE:AAD:RacingLineOptimization", ...
    "Racing-line QP failed (exit flag %d): %s", ...
    exitFlag, string(output.message));
constraintViolation = max([0.0; lowerBound - offset; ...
    offset - upperBound; inequalityMatrix * offset - inequalityBound]);
assert(constraintViolation <= 1.0e-7, ...
    "FSAE:AAD:RacingLineConstraintViolation", ...
    "Racing-line bound violation %.3g exceeds tolerance.", ...
    constraintViolation);

[planningOffset, ~, planningExitFlag, planningOutput] = quadprog( ...
    baseHessian, linearTerm, inequalityMatrix, inequalityBound, [], [], ...
    planningLowerBound, planningUpperBound, initialOffset, options);
assert(planningExitFlag > 0 && all(isfinite(planningOffset)), ...
    "FSAE:AAD:RacingLinePlanningOptimization", ...
    "Protected speed-planning line failed (exit flag %d): %s", ...
    planningExitFlag, string(planningOutput.message));

racingX = x + offset .* normalX;
racingY = y + offset .* normalY;
[racingHeading, racingCurvature, racingLength] = ...
    pathGeometry(racingX, racingY, sampleDistance, isClosed);
planningX = x + planningOffset .* normalX;
planningY = y + planningOffset .* normalY;
[~, planningCurvature, planningLength] = ...
    pathGeometry(planningX, planningY, sampleDistance, isClosed);
[racingEnvelopeClearance, racingBoundaryCorrectionSign] = ...
    referenceEnvelopeClearance(x, y, heading, leftWidth, rightWidth, ...
    racingX, racingY, racingHeading, cgToFrontAxle, cgToRearAxle, ...
    double(driver.FrontHalfEnvelope), ...
    double(driver.RearHalfEnvelope));

track.RacingLineOffset = offset;
track.RacingLineX = racingX;
track.RacingLineY = racingY;
track.RacingLineHeading = racingHeading;
track.RacingLineCurvature = racingCurvature;
track.RacingLineEnvelopeClearance = racingEnvelopeClearance;
track.RacingLineBoundaryCorrectionSign = ...
    racingBoundaryCorrectionSign;
track.RacingLineLength = racingLength;
segmentCount = sampleCount - double(~isClosed);
track.RacingLineSampleDistance = racingLength / segmentCount;
track.RacingLinePlanningCurvature = planningCurvature;
track.RacingLinePlanningLength = planningLength;
track.RacingLinePlanningSampleDistance = planningLength / segmentCount;

report = struct( ...
    "Method", "width-constrained minimum second-difference QP", ...
    "ExitFlag", exitFlag, ...
    "Iterations", output.iterations, ...
    "InitialObjective", initialObjective, ...
    "Objective", objective, ...
    "ConstraintViolation", constraintViolation, ...
    "MaximumAbsOffset", max(abs(offset)), ...
    "MaximumAbsOffsetRate", max(abs(firstDifference * offset)) / ...
        sampleDistance, ...
    "CurvatureLockedPointCount", 0, ...
    "CurvatureSoftConstrainedPointCount", ...
        nnz(softCurvatureActivation > 0.0), ...
    "MaximumCurvaturePenaltyActivation", ...
        max(softCurvatureActivation), ...
    "CurvaturePenaltyWeight", curvaturePenaltyWeight, ...
    "PlanningCurvatureLockedPointCount", nnz(planningLocked), ...
    "PlanningLineLength", planningLength, ...
    "PlanningLineMaximumAbsCurvature", ...
        max(abs(planningCurvature)), ...
    "CenterlineLength", double(track.Length), ...
    "RacingLineLength", racingLength, ...
    "LengthReduction", double(track.Length) - racingLength, ...
    "MaximumAbsCurvature", max(abs(racingCurvature)), ...
    "MinimumReferenceEnvelopeClearance", ...
        min(racingEnvelopeClearance), ...
    "IsPerformanceClaim", false);
end

function [heading, curvature, pathLength] = ...
        pathGeometry(pathX, pathY, sampleDistance, isClosed)
if isClosed
    dx = (circshift(pathX, -1) - circshift(pathX, 1)) / ...
        (2.0 * sampleDistance);
    dy = (circshift(pathY, -1) - circshift(pathY, 1)) / ...
        (2.0 * sampleDistance);
    ddx = (circshift(pathX, -1) - 2.0 * pathX + ...
        circshift(pathX, 1)) / sampleDistance^2;
    ddy = (circshift(pathY, -1) - 2.0 * pathY + ...
        circshift(pathY, 1)) / sampleDistance^2;
    pathLength = sum(hypot(circshift(pathX, -1) - pathX, ...
        circshift(pathY, -1) - pathY));
else
    dx = gradient(pathX, sampleDistance);
    dy = gradient(pathY, sampleDistance);
    ddx = gradient(dx, sampleDistance);
    ddy = gradient(dy, sampleDistance);
    pathLength = sum(hypot(diff(pathX), diff(pathY)));
end
heading = unwrap(atan2(dy, dx));
curvature = (dx .* ddy - dy .* ddx) ./ ...
    max((dx.^2 + dy.^2).^(3.0 / 2.0), eps);
end

function [firstDifference, secondDifference] = ...
        pathDifferenceMatrices(sampleCount, isClosed)
if isClosed
    secondDifference = spdiags([ones(sampleCount, 1), ...
        -2.0 * ones(sampleCount, 1), ones(sampleCount, 1)], ...
        -1:1, sampleCount, sampleCount);
    secondDifference(1, sampleCount) = 1.0;
    secondDifference(sampleCount, 1) = 1.0;
    firstDifference = spdiags([-ones(sampleCount, 1), ...
        ones(sampleCount, 1)], [0, 1], sampleCount, sampleCount);
    firstDifference(sampleCount, 1) = 1.0;
else
    firstRows = (1:sampleCount - 1).';
    firstDifference = sparse([firstRows; firstRows], ...
        [firstRows; firstRows + 1], ...
        [-ones(sampleCount - 1, 1); ones(sampleCount - 1, 1)], ...
        sampleCount - 1, sampleCount);
    secondRows = (1:sampleCount - 2).';
    secondDifference = sparse( ...
        [secondRows; secondRows; secondRows], ...
        [secondRows; secondRows + 1; secondRows + 2], ...
        [ones(sampleCount - 2, 1); ...
        -2.0 * ones(sampleCount - 2, 1); ...
        ones(sampleCount - 2, 1)], sampleCount - 2, sampleCount);
end
end

function expanded = expandBooleanNeighborhood(seed, radius, isClosed)
expanded = logical(seed);
for shift = 1:radius
    expanded = expanded | logical(shiftPath(seed, shift, isClosed)) | ...
        logical(shiftPath(seed, -shift, isClosed));
end
end

function expanded = expandWeightedNeighborhood(seed, radius, isClosed)
expanded = seed;
for shift = 1:radius
    decay = 1.0 - double(shift) / double(radius + 1);
    expanded = max(expanded, ...
        decay * shiftPath(seed, shift, isClosed));
    expanded = max(expanded, ...
        decay * shiftPath(seed, -shift, isClosed));
end
end

function shifted = shiftPath(values, shift, isClosed)
if isClosed
    shifted = circshift(values, shift);
elseif shift > 0
    shifted = zeros(size(values));
    shifted(shift + 1:end) = values(1:end - shift);
elseif shift < 0
    distance = -shift;
    shifted = zeros(size(values));
    shifted(1:end - distance) = values(distance + 1:end);
else
    shifted = values;
end
end

function [clearance, correctionSign] = referenceEnvelopeClearance( ...
        centerX, centerY, centerHeading, leftWidth, rightWidth, ...
        referenceX, referenceY, referenceHeading, cgToFrontAxle, ...
        cgToRearAxle, frontHalfEnvelope, rearHalfEnvelope)
localPoints = [ ...
    cgToFrontAxle, frontHalfEnvelope; ...
    cgToFrontAxle, -frontHalfEnvelope; ...
    -cgToRearAxle, rearHalfEnvelope; ...
    -cgToRearAxle, -rearHalfEnvelope];
minimumLeftClearance = realmax * ones(size(centerX));
minimumRightClearance = realmax * ones(size(centerX));
cosineHeading = cos(referenceHeading);
sineHeading = sin(referenceHeading);
for pointIndex = 1:4
    localX = localPoints(pointIndex, 1);
    localY = localPoints(pointIndex, 2);
    pointX = referenceX + localX * cosineHeading - ...
        localY * sineHeading;
    pointY = referenceY + localX * sineHeading + ...
        localY * cosineHeading;
    deltaX = pointX - centerX;
    deltaY = pointY - centerY;
    lateralPosition = -deltaX .* sin(centerHeading) + ...
        deltaY .* cos(centerHeading);
    minimumLeftClearance = min(minimumLeftClearance, ...
        leftWidth - lateralPosition);
    minimumRightClearance = min(minimumRightClearance, ...
        rightWidth + lateralPosition);
end
clearance = min(minimumLeftClearance, minimumRightClearance);
correctionSign = zeros(size(clearance));
sideTolerance = 1.0e-9;
correctionSign(minimumLeftClearance < ...
    minimumRightClearance - sideTolerance) = -1.0;
correctionSign(minimumRightClearance < ...
    minimumLeftClearance - sideTolerance) = 1.0;
end
