function selection = resolveVehicleDynamicsModel(value)
%RESOLVEVEHICLEDYNAMICSMODEL Normalize the selectable whole-vehicle plant.
%   The paired TorqueVectoring/Vehicle10DOF top models share the same driver, controller, sensors,
%   and external interfaces. Their only plant-level distinction is the
%   7DOF versus 10DOF vehicle implementation.

arguments
    value (1, 1) string
end

token = regexprep(upper(strip(value)), "[^A-Z0-9]", "");
switch token
    case {"7", "7DOF"}
        selection = struct( ...
            "Name", "7DOF", ...
            "DegreesOfFreedom", 7, ...
            "TopModel", "FSAE_TorqueVectoring_ClosedLoop", ...
            "PlantModel", "VehiclePlant", ...
            "CoreModel", "Vehicle7DOF", ...
            "QuasiStaticMethod", "AlgebraicLoadTransfer");
    case {"10", "10DOF"}
        selection = struct( ...
            "Name", "10DOF", ...
            "DegreesOfFreedom", 10, ...
            "TopModel", "FSAE_Vehicle10DOF_ClosedLoop", ...
            "PlantModel", "VehiclePlant10DOF", ...
            "CoreModel", "Vehicle10DOF", ...
            "QuasiStaticMethod", "Vehicle10DOFStaticSuspensionEquilibrium");
    otherwise
        error("FSAE:Simulation:InvalidDynamicsModel", ...
            "Vehicle dynamics model '%s' is invalid; use 7DOF or 10DOF.", ...
            value);
end
end
