function report = validateReferenceSpeedResult(result, options)
%VALIDATEREFERENCESPEEDRESULT Apply closed-loop reference-driver gates.

arguments
    result (1, 1) struct
    options.BoundaryTolerance (1, 1) double ...
        {mustBeNonnegative} = 1.0e-9
    options.MaximumOutputStep (1, 1) double ...
        {mustBePositive} = 0.0100001
    options.ThrowOnFailure (1, 1) logical = true
end

maximumOutputStep = NaN;
if numel(result.Time) >= 2
    maximumOutputStep = max(diff(double(result.Time(:))));
end
checks = struct( ...
    "ResultValid", logicalValue(result.Meta, "Valid"), ...
    "Completed", logicalValue(result.Meta, "Completed"), ...
    "StoppedAtFinish", logicalValue(result.Meta, "StoppedAtFinish"), ...
    "ReferenceSpeedUsed", ...
        logicalValue(result.Meta, "ReferenceSpeedUsed"), ...
    "FiniteLapTime", finiteMetric(result, "LapTime"), ...
    "EnvelopeDataValid", ...
        logicalValue(result.Meta, "VehicleEnvelopeDataValid"), ...
    "EnvelopeWithinBoundary", ...
        logicalValue(result.Meta, "VehicleEnvelopeWithinBoundary"), ...
    "ZeroEnvelopeViolationCount", ...
        metricAtMost(result, "VehicleEnvelopeViolationCount", 0), ...
    "ZeroEnvelopeViolation", metricAtMost(result, ...
        "MaximumVehicleEnvelopeViolation", options.BoundaryTolerance), ...
    "ZeroCGBoundaryViolation", metricAtMost(result, ...
        "MaximumBoundaryViolation", options.BoundaryTolerance), ...
    "StandardSolverProfile", configEquals(result, ...
        "Simulation", "SolverProfile", "standard"), ...
    "OutputDecimationOne", configEquals(result, ...
        "Simulation", "OutputDecimation", 1), ...
    "OutputStepWithinLimit", isfinite(maximumOutputStep) && ...
        maximumOutputStep <= options.MaximumOutputStep);

checkNames = string(fieldnames(checks));
passed = true;
failed = strings(0, 1);
for checkName = checkNames.'
    checkPassed = logical(checks.(checkName));
    passed = passed && checkPassed;
    if ~checkPassed
        failed(end + 1, 1) = checkName; %#ok<AGROW>
    end
end
report = struct( ...
    "Passed", passed, ...
    "Checks", checks, ...
    "FailedChecks", failed, ...
    "BoundaryTolerance", options.BoundaryTolerance, ...
    "MaximumOutputStep", maximumOutputStep, ...
    "MaximumAllowedOutputStep", options.MaximumOutputStep);

if options.ThrowOnFailure
    assert(report.Passed, "FSAE:ReferenceDriver:QualificationFailed", ...
        "Reference-speed driver qualification failed: %s.", ...
        strjoin(report.FailedChecks, ", "));
end
end

function value = logicalValue(data, fieldName)
value = false;
if isfield(data, fieldName) && isscalar(data.(fieldName))
    value = logical(data.(fieldName));
end
end

function valid = finiteMetric(result, fieldName)
valid = isfield(result, "Metrics") && ...
    isfield(result.Metrics, fieldName) && ...
    isscalar(result.Metrics.(fieldName)) && ...
    isfinite(result.Metrics.(fieldName));
end

function valid = metricAtMost(result, fieldName, limit)
valid = finiteMetric(result, fieldName) && ...
    double(result.Metrics.(fieldName)) <= limit;
end

function equal = configEquals(result, groupName, fieldName, expected)
equal = false;
if isfield(result, "Config") && isfield(result.Config, groupName) && ...
        isfield(result.Config.(groupName), fieldName)
    actual = result.Config.(groupName).(fieldName);
    if isnumeric(expected)
        equal = isscalar(actual) && double(actual) == double(expected);
    else
        equal = isscalar(string(actual)) && ...
            string(actual) == string(expected);
    end
end
end
