function scenario = createPathTrackingAutocrossScenario(options)
%CREATEPathTrackingAUTOCROSSSCENARIO Build the shared image-derived 1 km proxy track.
%   The default geometry is extracted from the 2024 FSEC endurance handbook
%   diagram. It is reused here as an Autocross simulation proxy; it is not
%   represented as an official Autocross layout.

arguments
    options.SampleDistance (1, 1) double {mustBePositive} = 0.5
    options.TargetSpeed (1, 1) double {mustBeNonnegative} = 12.0
    options.LateralAccelerationLimit (1, 1) double {mustBePositive} = 4.0
    options.ReferenceAccelerationLimit (1, 1) double {mustBePositive} = 3.0
    options.ReferenceDecelerationLimit (1, 1) double {mustBePositive} = 4.0
    options.ImagePath (1, 1) string = ""
    options.UseSavedData (1, 1) logical = true
    options.DataFolder (1, 1) string = ""
    options.TrackDataName (1, 1) string {mustBeMember( ...
        options.TrackDataName, ["autocross", "endurance"])} = "autocross"
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "track"));
if strlength(options.ImagePath) == 0
    options.ImagePath = fullfile(projectRoot, "scenarios", "Endurance", ...
        "assets", "2024_fsec_endurance_track.png");
    extractionProfile = "fsec_endurance";
else
    extractionProfile = "generic";
end
[track, dataInfo] = loadOrCreatePathTrackingImageTrack( ...
        options.TrackDataName, options.ImagePath, ...
        SampleDistance = options.SampleDistance, ...
        ExtractionProfile = extractionProfile, ...
        UseSavedData = options.UseSavedData, DataFolder = options.DataFolder);
track.TrackData = dataInfo;
curvatureMagnitude = max(abs(track.Curvature), 1.0e-4);
curvatureLimitedSpeed = sqrt(options.LateralAccelerationLimit ./ curvatureMagnitude);
track.ReferenceSpeed(:) = applyClosedSpeedEnvelope( ...
    min(options.TargetSpeed, curvatureLimitedSpeed), ...
    track.SampleDistance, options.ReferenceAccelerationLimit, ...
    options.ReferenceDecelerationLimit);
track.EventUsage = ...
    "Autocross simulation proxy reusing the FSEC endurance schematic; " + ...
    "not an official Autocross layout";

scenario = struct( ...
    "ID", "PathTracking-AUTOCROSS-FSEC-ENDURANCE-PROXY-1KM", ...
    "Event", "Autocross", ...
    "Track", track, ...
    "Environment", makeEnvironment(), ...
    "InitialState", makeInitialState(track), ...
    "StopTime", max(150, track.Length / max(options.TargetSpeed, 1.0) * 1.8), ...
    "NumberOfLaps", 1, ...
    "EventDescription", ...
    "Counterclockwise 1,000 m Autocross proxy extracted from the " + ...
    "2024 FSEC endurance handbook diagram.", ...
    "ReferenceSpeedSource", ...
    "temporary curvature-limited closed-loop target; not a performance claim");
end

function speed = applyClosedSpeedEnvelope( ...
    speed, sampleDistance, accelerationLimit, decelerationLimit)
sampleCount = numel(speed);
for pass = 1:3
    for index = sampleCount:-1:1
        nextIndex = mod(index, sampleCount) + 1;
        brakingSpeed = sqrt(speed(nextIndex)^2 + ...
            2 * decelerationLimit * sampleDistance);
        speed(index) = min(speed(index), brakingSpeed);
    end
    for index = 1:sampleCount
        previousIndex = mod(index - 2, sampleCount) + 1;
        accelerationSpeed = sqrt(speed(previousIndex)^2 + ...
            2 * accelerationLimit * sampleDistance);
        speed(index) = min(speed(index), accelerationSpeed);
    end
end
end

function environment = makeEnvironment()
environment = struct( ...
    "RoadGripScale", ones(4, 1), "RoadMuLimit", inf(4, 1), ...
    "RoadGrade", 0, "RoadBank", 0, ...
    "RoadHeight", zeros(4, 1), "AirDensity", 1.225, ...
    "WindVelocityGlobal", zeros(3, 1), "AmbientTemperature", 25, ...
    "Gravity", 9.80665, "EnableRoadDisturbance", false, ...
    "EnvironmentValid", true);
end

function initialState = makeInitialState(track)
initialState = struct( ...
    "X", track.X(1), "Y", track.Y(1), "Psi", track.Heading(1), ...
    "Ux", 0.2, "Uy", 0, "YawRate", 0, "WheelSpeed", 0.8 * ones(4, 1));
end
