function comparison = compareTorqueVectoringPair(metrics)
%COMPARETorqueVectoringPAIR Compare paired TV0 and TV1 TorqueVectoring verification metrics.

arguments
    metrics (2, 1) struct
end

baselineIndex = find(~[metrics.EnableTV], 1);
tvIndex = find([metrics.EnableTV], 1);
assert(~isempty(baselineIndex) && ~isempty(tvIndex), ...
    "FSAE:TorqueVectoring:ComparisonPair", ...
    "Comparison requires one TV0 and one TV1 metric record.");
baseline = metrics(baselineIndex);
tv = metrics(tvIndex);
assert(baseline.PairID == tv.PairID, "FSAE:TorqueVectoring:ComparisonID", ...
    "TorqueVectoring comparison records must have the same PairID.");

comparison = struct( ...
    "PairID", baseline.PairID, ...
    "Event", baseline.Event, ...
    "TireModel", baseline.TireModel, ...
    "TV0", baseline, ...
    "TV1", tv, ...
    "YawRateRMSEImprovementPercent", improvementPercent( ...
        baseline.YawRateRMSE, tv.YawRateRMSE), ...
    "LateralErrorImprovementPercent", improvementPercent( ...
        baseline.LateralErrorRMSE, tv.LateralErrorRMSE), ...
    "DriveEnergyChangePercent", changePercent( ...
        baseline.DriveEnergyJ, tv.DriveEnergyJ), ...
    "NetEnergyChangePercent", changePercent( ...
        baseline.NetBatteryEnergyJ, tv.NetBatteryEnergyJ), ...
    "PeakTireUtilizationChange", ...
        tv.PeakTireUtilization - baseline.PeakTireUtilization, ...
    "SaturationFractionChange", ...
        tv.ControllerSaturationFraction - ...
        baseline.ControllerSaturationFraction, ...
    "BoundaryViolationFractionChange", ...
        tv.BoundaryViolationFraction - baseline.BoundaryViolationFraction);
end

function value = improvementPercent(baseline, candidate)
if ~isfinite(baseline) || ~isfinite(candidate) || abs(baseline) < eps
    value = NaN;
else
    value = 100.0 * (baseline - candidate) / abs(baseline);
end
end

function value = changePercent(baseline, candidate)
if ~isfinite(baseline) || ~isfinite(candidate) || abs(baseline) < eps
    value = NaN;
else
    value = 100.0 * (candidate - baseline) / abs(baseline);
end
end
