function track = extractFsecEnduranceTrack(imagePath, options)
%EXTRACTFSECENDURANCETRACK Vectorize the 2024 FSEC endurance diagram.
%   The source is an annotated schematic rather than a surveyed map. The
%   extracted centerline is therefore normalized to TotalLength, while lane
%   width remains an explicit simulation assumption.

arguments
    imagePath (1, 1) string
    options.SampleDistance (1, 1) double {mustBePositive} = 0.5
    options.TotalLength (1, 1) double {mustBePositive} = 1000.0
    options.LaneWidth (1, 1) double {mustBePositive} = 3.0
end

track = extractTrackFromImage(imagePath, ...
    SampleDistance = options.SampleDistance, ...
    TotalLength = options.TotalLength, ...
    LaneWidth = options.LaneWidth, ...
    SmoothingDistance = 8.0, ...
    StartPoint = [124, 278], ...
    TravelDirection = "down", ...
    RegionOfInterest = [85, 165, 1140, 205], ...
    GrayIntensityRange = [90, 210], ...
    GrayChromaTolerance = 15, ...
    IncludeBlueTrackAreas = true, ...
    BlueTrackRegions = [ ...
        220, 188, 100, 25; ...
        1045, 188, 95, 25; ...
        350, 335, 75, 30], ...
    UseRedStartBridge = false, ...
    SupplementalPathWaypoints = [ ...
        202, 352; 216, 352; 231, 344; 244, 337; ...
        258, 348; 272, 359; 287, 352; 301, 339; ...
        315, 343; 329, 355; 344, 356; 360, 352], ...
    SupplementalPathRadius = 4, ...
    MaskClosingRadius = 3, ...
    MinimumComponentArea = 80, ...
    PruneSkeletonSpurs = true, ...
    MinimumTraceCoverage = 0.95);
track = regularizeFsecGeometry(track);

track.Name = "FSEC2024EnduranceDiagram";
track.SourceType = "annotated competition-handbook schematic";
track.SourceDocument = "2024 FSEC竞赛手册Handbook";
track.SourceDocumentURL = ...
    "https://img.sae-china.org/web/2024/10/" + ...
    "2024FSEC%E7%AB%9E%E8%B5%9B%E6%89%8B%E5%86%8CHandbook.pdf";
track.SourceImageSHA256 = ...
    "C769CEBF8EAE4CAA92D0BE26629C7665D393E9EADDB17C0314140CC57E7A0531";
track.ScaleSource = ...
    "normalized to 1,000 m; the schematic contains no metric scale";
track.WidthSource = ...
    "3 m minimum-width simulation assumption; not measured from the schematic";
track.ExtractionProfile = ...
    "ROI=[85 165 1140 205] px; start=[124 278] px; grey track, " + ...
    "three blue passing zones, and image-derived slalom waypoints";
end

function track = regularizeFsecGeometry(track)
% Smooth the marked connection regions, round the late-lap pixel corner,
% and make the timing-line neighborhood locally straight without applying
% more smoothing to the complete lap.
x = double(track.X(:));
y = double(track.Y(:));
sampleDistance = double(track.SampleDistance);
trackLength = double(track.Length);
sampleCount = numel(x);
s = (0:sampleCount - 1)' * sampleDistance;

markedRegionTargets = [52.0, 26.0; ...
                       94.0, -27.0; ...
                       344.0, 25.0];
markedSmoothingDistance = [32.0; 28.0; 40.0];
markedCoreHalfWidth = [18.0; 20.0; 18.0];
markedOuterHalfWidth = [30.0; 30.0; 32.0];
markedRegionS = zeros(size(markedRegionTargets, 1), 1);
markedPeakBefore = zeros(size(markedRegionS));
markedPeakBeforeS = zeros(size(markedRegionS));
for regionIndex = 1:numel(markedRegionS)
    distanceToTarget = hypot(x - markedRegionTargets(regionIndex, 1), ...
        y - markedRegionTargets(regionIndex, 2));
    [~, targetIndex] = min(distanceToTarget);
    markedRegionS(regionIndex) = s(targetIndex);
    regionMask = abs(s - markedRegionS(regionIndex)) <= ...
        markedCoreHalfWidth(regionIndex);
    regionIndices = find(regionMask);
    [markedPeakBefore(regionIndex), localPeakIndex] = max(abs( ...
        track.Curvature(regionMask)));
    markedPeakBeforeS(regionIndex) = s( ...
        regionIndices(localPeakIndex));
    smoothedX = smoothCircular(x, ...
        markedSmoothingDistance(regionIndex), sampleDistance);
    smoothedY = smoothCircular(y, ...
        markedSmoothingDistance(regionIndex), sampleDistance);
    regionWeight = smootherstepWeight( ...
        abs(s - markedRegionS(regionIndex)), ...
        markedCoreHalfWidth(regionIndex), ...
        markedOuterHalfWidth(regionIndex));
    x = x + regionWeight .* (smoothedX - x);
    y = y + regionWeight .* (smoothedY - y);
end

lateTurnMask = s >= trackLength - 80 & s <= trackLength - 30;
lateTurnIndices = find(lateTurnMask);
[latePeakBefore, localPeakIndex] = max(abs(track.Curvature(lateTurnMask)));
lateTurnIndex = lateTurnIndices(localPeakIndex);
lateTurnS = s(lateTurnIndex);

lateTurnSmoothingDistance = 32.0;
lateTurnInnerDistance = 16.0;
lateTurnOuterDistance = 40.0;
smoothedX = smoothCircular(x, lateTurnSmoothingDistance, sampleDistance);
smoothedY = smoothCircular(y, lateTurnSmoothingDistance, sampleDistance);
lateTurnWeight = smootherstepWeight(abs(s - lateTurnS), ...
    lateTurnInnerDistance, lateTurnOuterDistance);
x = x + lateTurnWeight .* (smoothedX - x);
y = y + lateTurnWeight .* (smoothedY - y);

straightInnerDistance = 16.0;
straightOuterDistance = 42.0;
signedStartDistance = s;
signedStartDistance(s > trackLength / 2) = ...
    signedStartDistance(s > trackLength / 2) - trackLength;
startTangent = [0.0, -1.0];
straightTargetX = signedStartDistance * startTangent(1);
straightTargetY = signedStartDistance * startTangent(2);
startWeight = smootherstepWeight(abs(signedStartDistance), ...
    straightInnerDistance, straightOuterDistance);
x = x + startWeight .* (straightTargetX - x);
y = y + startWeight .* (straightTargetY - y);

[x, y] = resampleClosedGeometry(x, y, trackLength, sampleCount);
[heading, curvature] = calculateClosedGeometry(x, y, sampleDistance);
markedPeakAfter = zeros(size(markedRegionS));
for regionIndex = 1:numel(markedRegionS)
    regionMask = abs(s - markedRegionS(regionIndex)) <= ...
        markedCoreHalfWidth(regionIndex);
    markedPeakAfter(regionIndex) = max(abs(curvature(regionMask)));
end

track.X = x;
track.Y = y;
track.Heading = heading;
track.Curvature = curvature;
track.GeometryRegularization = struct( ...
    "MarkedRegionTargets", markedRegionTargets, ...
    "MarkedRegionCenterSBeforeResampling", markedRegionS, ...
    "MarkedRegionPeakCurvatureBefore", markedPeakBefore, ...
    "MarkedRegionPeakCurvatureBeforeS", markedPeakBeforeS, ...
    "MarkedRegionPeakCurvatureAfter", markedPeakAfter, ...
    "MarkedRegionSmoothingDistance", markedSmoothingDistance, ...
    "MarkedRegionCoreHalfWidth", markedCoreHalfWidth, ...
    "MarkedRegionOuterHalfWidth", markedOuterHalfWidth, ...
    "LateTurnCenterSBeforeResampling", lateTurnS, ...
    "LateTurnPeakCurvatureBefore", latePeakBefore, ...
    "LateTurnPeakCurvatureAfter", max(abs(curvature( ...
        s >= trackLength - 80 & s <= trackLength - 30))), ...
    "LateTurnSmoothingDistance", lateTurnSmoothingDistance, ...
    "LateTurnInnerDistance", lateTurnInnerDistance, ...
    "LateTurnOuterDistance", lateTurnOuterDistance, ...
    "StraightDirection", startTangent, ...
    "StraightInnerDistance", straightInnerDistance, ...
    "StraightOuterDistance", straightOuterDistance);
end

function smoothed = smoothCircular(values, smoothingDistance, sampleDistance)
windowLength = max(5, 2 * floor(smoothingDistance / ...
    sampleDistance / 2) + 1);
halfWindow = floor(windowLength / 2);
kernelIndex = (-halfWindow:halfWindow)';
sigma = max(windowLength / 6, 1);
kernel = exp(-0.5 * (kernelIndex / sigma).^2);
kernel = kernel / sum(kernel);
sampleCount = numel(values);
wrappedIndex = mod((-halfWindow:sampleCount + halfWindow - 1)', ...
    sampleCount) + 1;
filtered = conv(values(wrappedIndex), kernel, "same");
smoothed = filtered(halfWindow + (1:sampleCount));
end

function weight = smootherstepWeight(distance, innerDistance, outerDistance)
weight = zeros(size(distance));
weight(distance <= innerDistance) = 1.0;
taper = distance > innerDistance & distance < outerDistance;
t = (distance(taper) - innerDistance) / ...
    (outerDistance - innerDistance);
weight(taper) = 1.0 - (6*t.^5 - 15*t.^4 + 10*t.^3);
end

function [x, y] = resampleClosedGeometry(x, y, trackLength, sampleCount)
closedX = [x; x(1)];
closedY = [y; y(1)];
arc = [0; cumsum(hypot(diff(closedX), diff(closedY)))];
queryArc = (0:sampleCount - 1)' * arc(end) / sampleCount;
x = interp1(arc, closedX, queryArc, "pchip");
y = interp1(arc, closedY, queryArc, "pchip");
discreteLength = sum(hypot(circshift(x, -1) - x, ...
    circshift(y, -1) - y));
scale = trackLength / discreteLength;
x = (x - x(1)) * scale;
y = (y - y(1)) * scale;
end

function [heading, curvature] = calculateClosedGeometry(x, y, sampleDistance)
dx = (circshift(x, -1) - circshift(x, 1)) / (2 * sampleDistance);
dy = (circshift(y, -1) - circshift(y, 1)) / (2 * sampleDistance);
ddx = (circshift(x, -1) - 2 * x + circshift(x, 1)) / ...
    sampleDistance^2;
ddy = (circshift(y, -1) - 2 * y + circshift(y, 1)) / ...
    sampleDistance^2;
heading = unwrap(atan2(dy, dx));
curvature = (dx .* ddy - dy .* ddx) ./ ...
    max((dx.^2 + dy.^2).^(3/2), eps);
end
