function track = loadPathTrackingAutocrossCsv(csvPath, targetSpeed)
%LOADPathTrackingAUTOCROSSCSV Load the reproducible centerline extracted from the map.

arguments
    csvPath (1, 1) string
    targetSpeed (1, 1) double {mustBeNonnegative} = 12.0
end

assert(isfile(csvPath), "FSAE:TrackCsvMissing", "Track CSV does not exist: %s", csvPath);
tableData = readtable(csvPath, TextType = "string");
requiredNames = ["s_m", "x_m", "y_m", "heading_rad", "curvature_1pm", ...
    "left_half_width_m", "right_half_width_m"];
assert(all(ismember(requiredNames, string(tableData.Properties.VariableNames))), ...
    "FSAE:TrackCsvColumns", "Track CSV does not match the PathTracking data contract.");

s = tableData.s_m(:);
track = struct( ...
    "Name", "AutocrossTrackMap", ...
    "SourceImage", "track_map.png", ...
    "SourceCsv", csvPath, ...
    "SourcePixelLength", NaN, ...
    "StartPixelRowColumn", [NaN, NaN], ...
    "IsClosed", true, ...
    "Length", s(end) + mean(diff(s)), ...
    "SampleDistance", mean(diff(s)), ...
    "X", tableData.x_m(:), ...
    "Y", tableData.y_m(:), ...
    "Heading", tableData.heading_rad(:), ...
    "Curvature", tableData.curvature_1pm(:), ...
    "ReferenceSpeed", targetSpeed * ones(height(tableData), 1), ...
    "LeftHalfWidth", tableData.left_half_width_m(:), ...
    "RightHalfWidth", tableData.right_half_width_m(:), ...
    "WidthSource", "temporary 3 m lane placeholder; width is not encoded in track_map.png", ...
    "CoordinateConvention", ...
    "normalized map frame; image y is inverted; left turn curvature is positive");
end
