function data = makePathTrackingTrackData(track, maxSamples)
%MAKEPathTrackingTRACKDATA Pack a variable-length track into the fixed-size PathTracking bus.

arguments
    track (1, 1) struct
    maxSamples (1, 1) double {mustBeInteger, mustBePositive} = 4096
end

sampleCount = numel(track.X);
assert(sampleCount <= maxSamples, "FSAE:PathTrackingTrackTooLong", ...
    "Track has %d samples but the PathTracking track bus supports %d.", sampleCount, maxSamples);
[referencePathValid, referenceSampleDistance, referenceX, ...
    referenceY, referenceHeading, referenceCurvature, ...
    referenceEnvelopeClearance, referenceBoundaryCorrectionSign] = ...
    resolveReferencePath(track, sampleCount);

data = struct( ...
    "SampleCount", uint32(sampleCount), ...
    "SampleDistance", double(track.SampleDistance), ...
    "TrackLength", double(track.Length), ...
    "IsClosed", logical(track.IsClosed), ...
    "ReferencePathValid", referencePathValid, ...
    "ReferenceSampleDistance", referenceSampleDistance, ...
    "X", zeros(maxSamples, 1), ...
    "Y", zeros(maxSamples, 1), ...
    "Heading", zeros(maxSamples, 1), ...
    "Curvature", zeros(maxSamples, 1), ...
    "ReferenceX", zeros(maxSamples, 1), ...
    "ReferenceY", zeros(maxSamples, 1), ...
    "ReferenceHeading", zeros(maxSamples, 1), ...
    "ReferenceCurvature", zeros(maxSamples, 1), ...
    "ReferenceEnvelopeClearance", realmax * ones(maxSamples, 1), ...
    "ReferenceBoundaryCorrectionSign", zeros(maxSamples, 1), ...
    "ReferenceSpeed", zeros(maxSamples, 1), ...
    "LeftHalfWidth", zeros(maxSamples, 1), ...
    "RightHalfWidth", zeros(maxSamples, 1));

data.X(1:sampleCount) = reshape(track.X, [], 1);
data.Y(1:sampleCount) = reshape(track.Y, [], 1);
data.Heading(1:sampleCount) = reshape(track.Heading, [], 1);
data.Curvature(1:sampleCount) = reshape(track.Curvature, [], 1);
data.ReferenceX(1:sampleCount) = referenceX;
data.ReferenceY(1:sampleCount) = referenceY;
data.ReferenceHeading(1:sampleCount) = referenceHeading;
data.ReferenceCurvature(1:sampleCount) = referenceCurvature;
data.ReferenceEnvelopeClearance(1:sampleCount) = ...
    referenceEnvelopeClearance;
data.ReferenceBoundaryCorrectionSign(1:sampleCount) = ...
    referenceBoundaryCorrectionSign;
data.ReferenceSpeed(1:sampleCount) = reshape(track.ReferenceSpeed, [], 1);
data.LeftHalfWidth(1:sampleCount) = reshape(track.LeftHalfWidth, [], 1);
data.RightHalfWidth(1:sampleCount) = reshape(track.RightHalfWidth, [], 1);
end

function [valid, sampleDistance, x, y, heading, curvature, ...
        envelopeClearance, boundaryCorrectionSign] = ...
        resolveReferencePath(track, sampleCount)
fields = ["RacingLineX", "RacingLineY", "RacingLineHeading", ...
    "RacingLineCurvature", "RacingLineSampleDistance", ...
    "RacingLineEnvelopeClearance", ...
    "RacingLineBoundaryCorrectionSign"];
available = isfield(track, cellstr(fields));
assert(~any(available) || all(available), ...
    "FSAE:PathTrackingIncompleteReferencePath", ...
    "Racing-line reference-path fields must be supplied as a complete set.");
if all(available)
    x = reshape(double(track.RacingLineX), [], 1);
    y = reshape(double(track.RacingLineY), [], 1);
    heading = reshape(double(track.RacingLineHeading), [], 1);
    curvature = reshape(double(track.RacingLineCurvature), [], 1);
    envelopeClearance = reshape( ...
        double(track.RacingLineEnvelopeClearance), [], 1);
    boundaryCorrectionSign = reshape( ...
        double(track.RacingLineBoundaryCorrectionSign), [], 1);
    sampleDistance = double(track.RacingLineSampleDistance);
    assert(all([numel(x), numel(y), numel(heading), ...
        numel(curvature), numel(envelopeClearance), ...
        numel(boundaryCorrectionSign)] == sampleCount) && ...
        all(isfinite([x; y; heading; curvature; ...
        envelopeClearance; boundaryCorrectionSign])) && ...
        isfinite(sampleDistance) && sampleDistance > 0.0, ...
        "FSAE:PathTrackingInvalidReferencePath", ...
        "Racing-line reference-path data must be finite and match the physical track size.");
    valid = true;
else
    x = reshape(double(track.X), [], 1);
    y = reshape(double(track.Y), [], 1);
    heading = reshape(double(track.Heading), [], 1);
    curvature = reshape(double(track.Curvature), [], 1);
    envelopeClearance = realmax * ones(sampleCount, 1);
    boundaryCorrectionSign = zeros(sampleCount, 1);
    sampleDistance = double(track.SampleDistance);
    valid = false;
end
valid = logical(valid);
end
