function scenario = createPathTrackingAccelerationScenario(options)
%CREATEPathTrackingACCELERATIONSCENARIO Create the 75 m straight acceleration case.

arguments
    options.TargetSpeed (1, 1) double {mustBeNonnegative} = 30.0
    options.SampleDistance (1, 1) double {mustBePositive} = 0.5
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "track"));

x = (0:options.SampleDistance:75)';
y = zeros(size(x));
track = makePathTrackingParametricTrack(x, y, options.SampleDistance, 3.0, ...
    "Acceleration75m", false);
track.ReferenceSpeed(:) = options.TargetSpeed;
track.LeftHalfWidth(:) = 1.5;
track.RightHalfWidth(:) = 1.5;
track.WidthSource = "temporary 3 m lane placeholder; acceleration width is not supplied";

scenario = makeScenario("PathTracking-ACCELERATION-75M", track, 6.0, 1);
scenario.EventDescription = "75 m straight acceleration through the timing line.";
scenario.ReferenceSpeedSource = "temporary constant target; not a performance claim";
end

function scenario = makeScenario(id, track, stopTime, laps)
scenario = struct( ...
    "ID", id, ...
    "Event", "Acceleration", ...
    "Track", track, ...
    "Environment", makeEnvironment(), ...
    "InitialState", makeInitialState(), ...
    "StopTime", stopTime, ...
    "NumberOfLaps", laps, ...
    "EventDescription", "", ...
    "ReferenceSpeedSource", "");
end

function environment = makeEnvironment()
environment = struct( ...
    "RoadGripScale", ones(4, 1), "RoadMuLimit", inf(4, 1), ...
    "RoadGrade", 0, "RoadBank", 0, ...
    "RoadHeight", zeros(4, 1), "AirDensity", 1.225, ...
    "WindVelocityGlobal", zeros(3, 1), "AmbientTemperature", 25, ...
    "Gravity", 9.80665, "EnableRoadDisturbance", false, ...
    "EnvironmentValid", true);
end

function initialState = makeInitialState()
initialState = struct( ...
    "X", 0, "Y", 0, "Psi", 0, "Ux", 0.01, "Uy", 0, ...
    "YawRate", 0, "WheelSpeed", 0.04 * ones(4, 1));
end
