function controlDesign = installUnifiedControlData(options)
%INSTALLUnifiedControlCONTROLDATA Install traceable UnifiedControl allocation parameters.
%   Physical aliases are copied from the shared vehicle records. New UnifiedControl
%   thresholds and weights are explicit tentative design values; none are
%   presented as measured vehicle calibration.

arguments
    options.DictionaryPath (1, 1) string = defaultDictionaryPath()
end

dictionary = Simulink.data.dictionary.open(options.DictionaryPath);
cleanup = onCleanup(@() close(dictionary));
designData = getSection(dictionary, "Design Data");

vehicle = getValue(getEntry(designData, "Vehicle"));
tire = getValue(getEntry(designData, "Tire"));
powertrain = getValue(getEntry(designData, "Powertrain"));
battery = getValue(getEntry(designData, "Battery"));
brake = getValue(getEntry(designData, "Brake"));
simulation = getValue(getEntry(designData, "Simulation"));

sampleTime = valueOf(simulation.TsController);
motorTorqueLimit = valueOf(powertrain.MotorTorqueLimit);
motorResponseTime = valueOf(powertrain.MotorResponseTime);
rateLimit = motorTorqueLimit / max(motorResponseTime, sampleTime);

controlDesign = struct( ...
    "SchemaVersion", "1.0", ...
    "Status", "TENTATIVE_UnifiedControl_CONTROL_DESIGN", ...
    "ObjectivePriority", ...
        "constraint satisfaction, yaw authority, longitudinal force", ...
    "FrictionEstimate", record(1.0, "1", ...
        "TorqueVectoringConservativeControlDesignReference", "Low"), ...
    "TCSlipOn", record(0.12, "1", ...
        "ControlDesignPlaceholder", "Low"), ...
    "TCSlipOff", record(0.08, "1", ...
        "ControlDesignPlaceholder", "Low"), ...
    "TCSlipFullCut", record(0.25, "1", ...
        "ControlDesignPlaceholder", "Low"), ...
    "MinimumNormalLoad", record(50.0, "N", ...
        "NumericalProtectionDesign", "Design"), ...
    "EnergyDriveFraction", record(0.90, "1", ...
        "EnergyManagementPlaceholder", "Low"), ...
    "MotorTorqueRateLimit", record(rateLimit, "N*m/s", ...
        "DerivedFromPowertrainMotorResponseTime", "Low"), ...
    "ForcePriorityWeight", record(1.0, "1", ...
        "AllocatorDesign", "Design"), ...
    "YawPriorityWeight", record(4.0, "1", ...
        "AllocatorDesign", "Design"), ...
    "RegularizationWeight", record(1.0e-4, "1", ...
        "AllocatorNumericalDesign", "Design"), ...
    "AllocatorIterations", record(uint8(24), "1", ...
        "FixedExecutionDesign", "Design"), ...
    "MaximumAcceleration", record(8.0, "m/s^2", ...
        "PathTrackingControlEnvelopePlaceholder", "Low"), ...
    "MaximumDeceleration", record(8.0, "m/s^2", ...
        "PathTrackingControlEnvelopePlaceholder", "Low"), ...
    "Notes", ...
        "TC, friction, rate, and energy calibrations require vehicle data.");

runtime = {
    "UnifiedControlSampleTime", sampleTime, "s", "Shared Simulation.TsController";
    "UnifiedControlVehicleMass", valueOf(vehicle.Mass), "kg", "Shared Vehicle.Mass";
    "UnifiedControlWheelbase", valueOf(vehicle.Wheelbase), "m", "Shared Vehicle.Wheelbase";
    "UnifiedControlCGHeight", valueOf(vehicle.CGHeight), "m", "Shared Vehicle.CGHeight";
    "UnifiedControlStaticLoadDistributionFront", ...
        valueOf(vehicle.StaticLoadDistributionFront), "1", ...
        "Shared Vehicle.StaticLoadDistributionFront";
    "UnifiedControlRollStiffnessDistributionFront", ...
        valueOf(vehicle.RollStiffnessDistributionFront), "1", ...
        "Shared Vehicle.RollStiffnessDistributionFront";
    "UnifiedControlTrackFront", valueOf(vehicle.TrackFront), "m", ...
        "Shared Vehicle.TrackFront";
    "UnifiedControlTrackRear", valueOf(vehicle.TrackRear), "m", ...
        "Shared Vehicle.TrackRear";
    "UnifiedControlTireEffectiveRadius", valueOf(tire.EffectiveRadius), "m", ...
        "Shared Tire.EffectiveRadius";
    "UnifiedControlLowSpeedEpsilon", valueOf(tire.LowSpeedEpsilon), "m/s", ...
        "Shared Tire.LowSpeedEpsilon";
    "UnifiedControlGearRatio", valueOf(powertrain.GearRatio), "1", ...
        "Shared Powertrain.GearRatio";
    "UnifiedControlGearEfficiency", valueOf(powertrain.GearEfficiency), "1", ...
        "Shared Powertrain.GearEfficiency";
    "UnifiedControlMotorTorqueLimit", motorTorqueLimit, "N*m", ...
        "Shared Powertrain.MotorTorqueLimit";
    "UnifiedControlMotorSpeedLimit", valueOf(powertrain.MotorSpeedLimit), "rad/s", ...
        "Shared Powertrain.MotorSpeedLimit";
    "UnifiedControlInverterEfficiency", valueOf(powertrain.InverterEfficiency), "1", ...
        "Shared Powertrain.InverterEfficiency";
    "UnifiedControlDrivePowerLimit", valueOf(battery.PowerLimitDrive), "W", ...
        "Shared Battery.PowerLimitDrive";
    "UnifiedControlRegenPowerLimit", valueOf(battery.PowerLimitRegen), "W", ...
        "Shared Battery.PowerLimitRegen";
    "UnifiedControlBrakeMaxTorque", valueOf(brake.MaxTorquePerWheel), "N*m", ...
        "Shared Brake.MaxTorquePerWheel";
    "UnifiedControlBatterySOCUpperLimit", valueOf(battery.SOCUpperLimit), "1", ...
        "Shared Battery.SOCUpperLimit";
    "UnifiedControlPowerEpsilon", valueOf(battery.PowerEpsilon), "W", ...
        "Shared Battery.PowerEpsilon";
    "UnifiedControlGravity", valueOf(simulation.Gravity), "m/s^2", ...
        "Shared Simulation.Gravity";
    "UnifiedControlMotorTorqueRateLimit", rateLimit, "N*m/s", ...
        "Derived Powertrain.MotorTorqueLimit/MotorResponseTime";
    "UnifiedControlFrictionEstimate", controlDesign.FrictionEstimate.Value, "1", ...
        controlDesign.FrictionEstimate.Source;
    "UnifiedControlTCSlipOn", controlDesign.TCSlipOn.Value, "1", ...
        controlDesign.TCSlipOn.Source;
    "UnifiedControlTCSlipOff", controlDesign.TCSlipOff.Value, "1", ...
        controlDesign.TCSlipOff.Source;
    "UnifiedControlTCSlipFullCut", controlDesign.TCSlipFullCut.Value, "1", ...
        controlDesign.TCSlipFullCut.Source;
    "UnifiedControlMinimumNormalLoad", controlDesign.MinimumNormalLoad.Value, "N", ...
        controlDesign.MinimumNormalLoad.Source;
    "UnifiedControlEnergyDriveFraction", controlDesign.EnergyDriveFraction.Value, "1", ...
        controlDesign.EnergyDriveFraction.Source;
    "UnifiedControlForcePriorityWeight", controlDesign.ForcePriorityWeight.Value, "1", ...
        controlDesign.ForcePriorityWeight.Source;
    "UnifiedControlYawPriorityWeight", controlDesign.YawPriorityWeight.Value, "1", ...
        controlDesign.YawPriorityWeight.Source;
    "UnifiedControlRegularizationWeight", controlDesign.RegularizationWeight.Value, "1", ...
        controlDesign.RegularizationWeight.Source;
    "UnifiedControlAllocatorIterations", controlDesign.AllocatorIterations.Value, "1", ...
        controlDesign.AllocatorIterations.Source;
    "UnifiedControlMaximumAcceleration", controlDesign.MaximumAcceleration.Value, ...
        "m/s^2", controlDesign.MaximumAcceleration.Source;
    "UnifiedControlMaximumDeceleration", controlDesign.MaximumDeceleration.Value, ...
        "m/s^2", controlDesign.MaximumDeceleration.Source;
    "UnifiedControlEnableTV", false, "1", "Scenario configuration switch";
    "UnifiedControlEnableTC", false, "1", "Scenario configuration switch";
    "UnifiedControlEnableRegen", true, "1", "Scenario configuration switch";
    "UnifiedControlEnableEnergyManagement", false, "1", ...
        "Scenario configuration switch"
    };

for row = 1:size(runtime, 1)
    parameter = Simulink.Parameter(runtime{row, 2});
    parameter.Unit = runtime{row, 3};
    parameter.Description = "UnifiedControl runtime parameter; source=" + ...
        string(runtime{row, 4});
    setEntry(designData, runtime{row, 1}, parameter);
end
setEntry(designData, "UnifiedControlDesign", controlDesign);
saveChanges(dictionary);
end

function value = valueOf(recordValue)
if isa(recordValue, "Simulink.Parameter")
    value = recordValue.Value;
elseif isstruct(recordValue) && isfield(recordValue, "Value")
    value = recordValue.Value;
else
    value = recordValue;
end
end

function output = record(value, unit, source, confidence)
output = struct( ...
    "Value", value, "LowerBound", NaN, "UpperBound", NaN, ...
    "Unit", unit, "Source", source, "Confidence", confidence, ...
    "LastUpdated", "2026-08-02", "IsMeasured", false, ...
    "IsPlaceholder", confidence == "Low");
end

function setEntry(section, name, value)
try
    entry = getEntry(section, name);
    setValue(entry, value);
catch exception
    if contains(exception.identifier, "EntryNotFound") || ...
            contains(exception.message, "does not exist", IgnoreCase = true)
        addEntry(section, name, value);
    else
        rethrow(exception);
    end
end
end

function path = defaultDictionaryPath()
projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
path = fullfile(projectRoot, "data", "VehicleData.sldd");
end
