function lookup = buildTireEnvelopeLookup(config, options)
%BUILDTIREENVELOPELOOKUP Precompute MF62 support versus normal load.

arguments
    config (1, 1) struct
    options.SpeedGrid (1, :) double = 0.0
    options.RoadGripScale (1, :) double = []
    options.RoadMuLimit (1, :) double = []
    options.CamberAngle (4, 1) double = zeros(4, 1)
    options.LoadPointCount (1, 1) double ...
        {mustBeInteger, mustBeGreaterThanOrEqual(options.LoadPointCount, 17)} = 81
    options.NormalLoadUpper (1, 1) double = NaN
    options.UseParallel (1, 1) logical = false
end

roadGripScale = resolveFour(options.RoadGripScale, ...
    config.Environment.RoadGripScale);
roadMuLimit = resolveFour(options.RoadMuLimit, ...
    config.Environment.RoadMuLimit);
camber = options.CamberAngle;
assert(all(isfinite(roadGripScale)) && all(roadGripScale >= 0.0), ...
    "FSAE:QuasiStatic:EnvelopeLookupRoadGripScale", ...
    "RoadGripScale must be finite and nonnegative.");
assert(all((isfinite(roadMuLimit) & roadMuLimit >= 0.0) | ...
    (isinf(roadMuLimit) & roadMuLimit > 0.0)), ...
    "FSAE:QuasiStatic:EnvelopeLookupRoadMuLimit", ...
    "RoadMuLimit must contain nonnegative finite values or Inf.");
assert(all(isfinite(camber)), "FSAE:QuasiStatic:EnvelopeLookupCamber", ...
    "CamberAngle must be finite.");
if isnan(options.NormalLoadUpper)
    normalLoadUpper = automaticNormalLoadUpper(config, options.SpeedGrid);
else
    validateattributes(options.NormalLoadUpper, {'double'}, ...
        {'scalar', 'positive', 'finite'});
    normalLoadUpper = options.NormalLoadUpper;
end

loadCoordinate = linspace(0.0, 1.0, options.LoadPointCount)';
normalLoadGrid = normalLoadUpper .* loadCoordinate.^2;
directionCount = config.Solver.EnvelopePointCount;
support = zeros(options.LoadPointCount, directionCount, 4);
fxMax = zeros(options.LoadPointCount, 4);
fyMax = zeros(options.LoadPointCount, 4);
if options.UseParallel
    parfor loadIndex = 1:options.LoadPointCount
        [supportRow, fxRow, fyRow] = evaluateLookupNode(config, ...
            normalLoadGrid(loadIndex), roadGripScale, roadMuLimit, camber);
        support(loadIndex, :, :) = reshape(supportRow, 1, directionCount, 4);
        fxMax(loadIndex, :) = fxRow;
        fyMax(loadIndex, :) = fyRow;
    end
else
    for loadIndex = 1:options.LoadPointCount
        [supportRow, fxRow, fyRow] = evaluateLookupNode(config, ...
            normalLoadGrid(loadIndex), roadGripScale, roadMuLimit, camber);
        support(loadIndex, :, :) = reshape(supportRow, 1, directionCount, 4);
        fxMax(loadIndex, :) = fxRow;
        fyMax(loadIndex, :) = fyRow;
    end
end

theta = (0:directionCount - 1)' * (2.0 * pi / directionCount);
directions = [cos(theta), sin(theta)];

lookup = struct( ...
    "Version", 1, ...
    "Method", "MF62 combined-slip normal-load lookup", ...
    "NormalLoadGrid", normalLoadGrid, ...
    "NormalLoadUpper", normalLoadUpper, ...
    "Directions", directions, ...
    "Support", support, ...
    "FxMax", fxMax, ...
    "FyMax", fyMax, ...
    "RoadGripScale", roadGripScale, ...
    "RoadMuLimit", roadMuLimit, ...
    "CamberAngle", camber, ...
    "TireModel", config.Tire.Model, ...
    "TireProfile", config.Tire.Profile, ...
    "KappaGrid", config.Tire.KappaGrid(:), ...
    "AlphaGrid", config.Tire.AlphaGrid(:), ...
    "EnvelopePointCount", directionCount, ...
    "LoadPointCount", options.LoadPointCount, ...
    "PrecomputationParallel", options.UseParallel, ...
    "InterpolationMethod", "linear");
end

function [supportRow, fxRow, fyRow] = evaluateLookupNode( ...
        config, normalLoadValue, roadGripScale, roadMuLimit, camber)
loadVector = normalLoadValue .* ones(4, 1);
envelopes = evaluateTireEnvelopeMF62(config, loadVector, ...
    roadGripScale, roadMuLimit, camber);
supportRow = [envelopes.Support];
fxRow = [envelopes.FxMax];
fyRow = [envelopes.FyMax];
end

function normalLoadUpper = automaticNormalLoadUpper(config, speedGrid)
speedGrid = double(speedGrid(:));
assert(~isempty(speedGrid) && all(isfinite(speedGrid)) && ...
    all(speedGrid >= 0.0), "FSAE:QuasiStatic:EnvelopeLookupSpeedGrid", ...
    "Envelope lookup speed grid must contain finite nonnegative speeds.");
wind = config.Environment.WindVelocityBody(:);
endpointVelocity = [[0.0; 0.0] - wind, ...
    [max(speedGrid); 0.0] - wind];
maximumRelativeSpeed = max(vecnorm(endpointVelocity, 2, 1));
maximumDynamicPressure = 0.5 * config.Environment.AirDensity * ...
    maximumRelativeSpeed^2;
maximumDownforceScale = max(config.Aero.YawDownforceScale);
maximumDownforce = maximumDynamicPressure * ...
    (config.Aero.ClAFront + config.Aero.ClARear) * ...
    maximumDownforceScale;
maximumTotalNormalLoad = config.Vehicle.Mass * config.Solver.Gravity + ...
    maximumDownforce;
referenceTotalLoad = 0.0;
if isfield(config.Tire.Profile, "Reference") && ...
        isfield(config.Tire.Profile.Reference, "NormalLoadN")
    referenceTotalLoad = 4.0 * config.Tire.Profile.Reference.NormalLoadN;
end
normalLoadUpper = 1.05 * max(maximumTotalNormalLoad, referenceTotalLoad);
end

function value = resolveFour(override, fallback)
if isempty(override)
    value = double(fallback(:));
else
    value = double(override(:));
end
if isscalar(value)
    value = repmat(value, 4, 1);
end
assert(numel(value) == 4, "FSAE:QuasiStatic:EnvelopeLookupRoadInput", ...
    "Road inputs must be scalar or four-wheel vectors.");
end
