function config = createQuasiStaticConfiguration(parameters, options)
%CREATEQuasiStaticCONFIGURATION Normalize shared parameters for the QuasiStatic solvers.
%   CONFIG = CREATEQuasiStaticCONFIGURATION(PARAMETERS) converts the structured
%   VehicleData-style parameters into the explicit numeric contract used by
%   the steady-state and GGV solvers. Placeholder NaN values are rejected;
%   QuasiStatic must not silently turn missing vehicle data into a performance claim.

arguments
    parameters (1, 1) struct
    options.TireProfile (1, 1) struct = struct()
    options.TireModel (1, 1) string = "MF62"
    options.DynamicsModel (1, 1) string = "7DOF"
    options.AllocationMode (1, 1) string = "LP"
    options.Environment (1, 1) struct = struct()
    options.EnvelopePointCount (1, 1) double {mustBeInteger, mustBeGreaterThanOrEqual(options.EnvelopePointCount, 12)} = 48
    options.KappaGrid (1, :) double = linspace(-0.40, 0.40, 41)
    options.AlphaGrid (1, :) double = linspace(-0.35, 0.35, 41)
end

projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(projectRoot, "scripts", "tire"));
addpath(fullfile(projectRoot, "scripts", "simulation"));
dynamics = resolveVehicleDynamicsModel(options.DynamicsModel);

vehicle = struct( ...
    "Mass", requiredValue(parameters, "Vehicle", "Mass"), ...
    "Wheelbase", requiredValue(parameters, "Vehicle", "Wheelbase"), ...
    "TrackFront", requiredValue(parameters, "Vehicle", "TrackFront"), ...
    "TrackRear", requiredValue(parameters, "Vehicle", "TrackRear"), ...
    "CGHeight", requiredValue(parameters, "Vehicle", "CGHeight"), ...
    "CGToFrontAxle", requiredValue(parameters, "Vehicle", "CGToFrontAxle"), ...
    "RollStiffnessDistributionFront", requiredValue(parameters, ...
        "Vehicle", "RollStiffnessDistributionFront"));
vehicle.CGToRearAxle = vehicle.Wheelbase - vehicle.CGToFrontAxle;

tire = struct( ...
    "EffectiveRadius", requiredValue(parameters, "Tire", "EffectiveRadius"), ...
    "LowSpeedEpsilon", optionalValue(parameters, "Tire", ...
        "LowSpeedEpsilon", 0.1));

aero = struct( ...
    "CdA", requiredValue(parameters, "Aero", "CdA"), ...
    "ClAFront", requiredValue(parameters, "Aero", "ClAFront"), ...
    "ClARear", requiredValue(parameters, "Aero", "ClARear"), ...
    "YawCorrection", optionalValue(parameters, "Aero", "YawCorrection", 0.0), ...
    "YawAngleGrid", requiredVectorValue(parameters, "Aero", "YawAngleGrid"), ...
    "YawDownforceScale", requiredVectorValue(parameters, "Aero", ...
        "YawDownforceScale"));

powertrain = struct( ...
    "GearRatio", requiredValue(parameters, "Powertrain", "GearRatio"), ...
    "GearEfficiency", requiredValue(parameters, "Powertrain", "GearEfficiency"), ...
    "MotorTorqueLimit", requiredValue(parameters, ...
        "Powertrain", "MotorTorqueLimit"), ...
    "MotorSpeedLimit", requiredValue(parameters, ...
        "Powertrain", "MotorSpeedLimit"), ...
    "InverterEfficiency", optionalValue(parameters, ...
        "Powertrain", "InverterEfficiency", 1.0));

battery = struct( ...
    "PowerLimitDrive", requiredValue(parameters, "Battery", "PowerLimitDrive"), ...
    "PowerLimitRegen", requiredValue(parameters, "Battery", "PowerLimitRegen"));

brakes = struct("MaxTotalForce", Inf);
if isfield(parameters, "Brake") && isfield(parameters.Brake, "MaxTotalForce")
    brakes.MaxTotalForce = optionalValue(parameters, "Brake", ...
        "MaxTotalForce", Inf);
end

environment = makeEnvironment(options.Environment);
if isempty(fieldnames(options.TireProfile))
    profile = getSelectedTireProfile();
else
    profile = options.TireProfile;
end

model = upper(options.TireModel);
assert(any(model == ["MF62", "TTCMAP"]), "FSAE:QuasiStatic:TireModel", ...
    "TireModel must be MF62 or TTCMap.");
allocationMode = upper(options.AllocationMode);
assert(any(allocationMode == ["LP", "FAST"]), "FSAE:QuasiStatic:AllocationMode", ...
    "AllocationMode must be LP or Fast.");

validateattributes(vehicle.Mass, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(vehicle.Wheelbase, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(vehicle.CGToFrontAxle, {'double', 'single'}, {'scalar', '>=', 0, '<', vehicle.Wheelbase});
validateattributes(vehicle.TrackFront, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(vehicle.TrackRear, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(vehicle.CGHeight, {'double', 'single'}, {'scalar', 'nonnegative', 'finite'});
validateattributes(vehicle.RollStiffnessDistributionFront, {'double', 'single'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
validateattributes(tire.EffectiveRadius, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(aero.CdA, {'double', 'single'}, {'scalar', 'nonnegative', 'finite'});
validateattributes(aero.ClAFront, {'double', 'single'}, {'scalar', 'nonnegative', 'finite'});
validateattributes(aero.ClARear, {'double', 'single'}, {'scalar', 'nonnegative', 'finite'});
validateattributes(aero.YawAngleGrid, {'double', 'single'}, {'vector', 'finite'});
validateattributes(aero.YawDownforceScale, {'double', 'single'}, ...
    {'vector', 'nonnegative', 'finite'});
assert(numel(aero.YawAngleGrid) == numel(aero.YawDownforceScale) && ...
    numel(aero.YawAngleGrid) >= 2, "FSAE:QuasiStatic:YawGridSize", ...
    "Yaw angle and downforce scale grids must have equal length >= 2.");
assert(aero.YawAngleGrid(1) >= 0 && all(diff(aero.YawAngleGrid) > 0), ...
    "FSAE:QuasiStatic:YawGridOrder", ...
    "YawAngleGrid must be strictly increasing and start at a nonnegative angle.");
validateattributes(powertrain.GearRatio, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(powertrain.GearEfficiency, {'double', 'single'}, {'scalar', '>', 0, '<=', 1, 'finite'});
validateattributes(powertrain.MotorTorqueLimit, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(powertrain.MotorSpeedLimit, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(powertrain.InverterEfficiency, {'double', 'single'}, {'scalar', '>', 0, '<=', 1, 'finite'});
validateattributes(battery.PowerLimitDrive, {'double', 'single'}, {'scalar', 'positive', 'finite'});
validateattributes(battery.PowerLimitRegen, {'double', 'single'}, {'scalar', 'nonnegative', 'finite'});
validateattributes(environment.RoadGripScale, {'double', 'single'}, ...
    {'vector', 'nonnegative', 'finite'});
assert(isscalar(environment.RoadGripScale) || ...
    numel(environment.RoadGripScale) == 4, ...
    "FSAE:QuasiStatic:RoadGripScaleSize", ...
    "RoadGripScale must be scalar or a four-wheel vector.");
validateattributes(environment.RoadMuLimit, {'double', 'single'}, ...
    {'vector', 'nonnegative'});
assert(all(~isnan(environment.RoadMuLimit)) && ...
    (isscalar(environment.RoadMuLimit) || ...
    numel(environment.RoadMuLimit) == 4), ...
    "FSAE:QuasiStatic:RoadMuLimitSize", ...
    "RoadMuLimit must be scalar or a four-wheel vector without NaN values.");

vehicle.DynamicsModel = dynamics.Name;
vehicle.DegreesOfFreedom = dynamics.DegreesOfFreedom;
if dynamics.Name == "10DOF"
    suspension = make10DOFStaticSuspension(parameters, vehicle, ...
        environment.Gravity);
else
    suspension = struct( ...
        "Model", "7DOF", ...
        "ReductionMethod", dynamics.QuasiStaticMethod, ...
        "DamperForceAtEquilibrium", 0.0);
end

config = struct( ...
    "Vehicle", vehicle, ...
    "Suspension", suspension, ...
    "Tire", struct("Model", string(model), "Profile", profile, ...
        "EffectiveRadius", tire.EffectiveRadius, ...
        "LowSpeedEpsilon", tire.LowSpeedEpsilon, ...
        "KappaGrid", options.KappaGrid, "AlphaGrid", options.AlphaGrid), ...
    "Aero", aero, ...
    "Powertrain", powertrain, ...
    "Battery", battery, ...
    "Brake", brakes, ...
    "Environment", environment, ...
    "Solver", struct( ...
        "Gravity", environment.Gravity, ...
        "EnvelopePointCount", options.EnvelopePointCount, ...
        "EquilibriumTolerance", 1.0e-6, ...
        "BisectionTolerance", 1.0e-4, ...
        "MaxBisectionIterations", 32, ...
        "MaxLongitudinalAcceleration", 20.0, ...
        "AllocationMode", allocationMode, ...
        "MaxLateralAcceleration", 20.0, ...
        "PowerSpeedEpsilon", 0.5));

config.Metadata = struct( ...
    "TireDataSource", profile.Validity, ...
    "DynamicsModel", dynamics.Name, ...
    "DegreesOfFreedom", dynamics.DegreesOfFreedom, ...
        "QuasiStaticMethod", dynamics.QuasiStaticMethod, ...
        "RoadSurfaceContract", ...
            "RoadGripScale relative to tire reference; optional absolute RoadMuLimit", ...
        "ParameterContract", "QuasiStatic normalized numeric parameters; NaN placeholders rejected", ...
    "IsPerformanceClaim", false);
end

function suspension = make10DOFStaticSuspension(parameters, vehicle, gravity)
wheelRate = requiredNumericVector(parameters, "Vehicle10DOFSuspension", ...
    "WheelRate", 4);
additionalRollStiffness = requiredNumericVector(parameters, ...
    "Vehicle10DOFSuspension", "AdditionalRollStiffness", 2);
validateattributes(wheelRate, {'double'}, {'positive', 'finite'});
validateattributes(additionalRollStiffness, {'double'}, ...
    {'nonnegative', 'finite'});

distanceRear = vehicle.Wheelbase - vehicle.CGToFrontAxle;
staticFront = vehicle.Mass * gravity * distanceRear / ...
    vehicle.Wheelbase / 2.0;
staticRear = vehicle.Mass * gravity * vehicle.CGToFrontAxle / ...
    vehicle.Wheelbase / 2.0;
springRollStiffness = [ ...
    sum(wheelRate(1:2)) * (vehicle.TrackFront / 2.0)^2; ...
    sum(wheelRate(3:4)) * (vehicle.TrackRear / 2.0)^2];

suspension = struct( ...
    "Model", "10DOF", ...
    "ReductionMethod", "Vehicle10DOFStaticSuspensionEquilibrium", ...
    "WheelRate", wheelRate, ...
    "AdditionalRollStiffness", additionalRollStiffness, ...
    "SpringRollStiffness", springRollStiffness, ...
    "TotalRollStiffness", springRollStiffness + ...
        additionalRollStiffness, ...
    "StaticNormalLoad", [staticFront; staticFront; staticRear; staticRear], ...
    "DamperForceAtEquilibrium", 0.0);
end

function value = requiredValue(parameters, groupName, fieldName)
assert(isfield(parameters, groupName), "FSAE:QuasiStatic:MissingParameterGroup", ...
    "Missing parameter group %s.", groupName);
assert(isfield(parameters.(groupName), fieldName), ...
    "FSAE:QuasiStatic:MissingParameter", "Missing parameter %s.%s.", groupName, fieldName);
value = unwrapValue(parameters.(groupName).(fieldName));
assert(isscalar(value) && isnumeric(value) && isfinite(value) && ~isnan(value), ...
    "FSAE:QuasiStatic:PlaceholderParameter", ...
    "Parameter %s.%s must be a finite numeric scalar, not a placeholder.", ...
    groupName, fieldName);
value = double(value);
end

function value = requiredVectorValue(parameters, groupName, fieldName)
assert(isfield(parameters, groupName), "FSAE:QuasiStatic:MissingParameterGroup", ...
    "Missing parameter group %s.", groupName);
assert(isfield(parameters.(groupName), fieldName), ...
    "FSAE:QuasiStatic:MissingParameter", "Missing parameter %s.%s.", ...
    groupName, fieldName);
value = unwrapValue(parameters.(groupName).(fieldName));
assert(isvector(value) && isnumeric(value) && numel(value) >= 2 && ...
    all(isfinite(value)), "FSAE:QuasiStatic:InvalidVectorParameter", ...
    "Parameter %s.%s must be a finite numeric vector with at least two values.", ...
    groupName, fieldName);
value = double(value(:).');
end

function value = requiredNumericVector(parameters, groupName, fieldName, count)
assert(isfield(parameters, groupName), "FSAE:QuasiStatic:MissingParameterGroup", ...
    "Missing parameter group %s for the 10DOF quasi-static reduction.", ...
    groupName);
assert(isfield(parameters.(groupName), fieldName), ...
    "FSAE:QuasiStatic:MissingParameter", "Missing parameter %s.%s.", ...
    groupName, fieldName);
value = unwrapValue(parameters.(groupName).(fieldName));
assert(isnumeric(value) && isvector(value) && numel(value) == count && ...
    all(isfinite(value)), "FSAE:QuasiStatic:InvalidVectorParameter", ...
    "Parameter %s.%s must contain %d finite numeric values.", ...
    groupName, fieldName, count);
value = double(value(:));
end

function value = optionalValue(parameters, groupName, fieldName, defaultValue)
if ~isfield(parameters, groupName) || ~isfield(parameters.(groupName), fieldName)
    value = defaultValue;
    return
end
value = unwrapValue(parameters.(groupName).(fieldName));
if isempty(value) || ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || isnan(value)
    value = defaultValue;
end
value = double(value);
end

function value = unwrapValue(value)
if isstruct(value) && isfield(value, "Value")
    value = value.Value;
end
end

function environment = makeEnvironment(input)
environment = struct( ...
    "RoadGripScale", ones(4, 1), ...
    "RoadMuLimit", inf(4, 1), ...
    "AirDensity", 1.225, ...
    "Gravity", 9.80665, ...
    "WindVelocityBody", zeros(2, 1));
fields = fieldnames(input);
allowedFields = ["RoadGripScale", "RoadMuLimit", "RoadGrade", ...
    "RoadBank", "RoadHeight", "AirDensity", "WindVelocityGlobal", ...
    "WindVelocityBody", "AmbientTemperature", "Gravity", ...
    "EnableRoadDisturbance", "EnvironmentValid"];
unknownFields = setdiff(string(fields), allowedFields);
assert(isempty(unknownFields), "FSAE:QuasiStatic:UnknownEnvironmentField", ...
    "Unsupported Environment field(s): " + strjoin(unknownFields, ", "));
for index = 1:numel(fields)
    environment.(fields{index}) = input.(fields{index});
end
environment.RoadGripScale = expandEnvironmentFour( ...
    environment.RoadGripScale);
environment.RoadMuLimit = expandEnvironmentFour(environment.RoadMuLimit);
environment.WindVelocityBody = double(environment.WindVelocityBody(:));
assert(numel(environment.WindVelocityBody) == 2, "FSAE:QuasiStatic:WindSize", ...
    "WindVelocityBody must contain [u_wind, v_wind] in m/s.");
end

function value = expandEnvironmentFour(value)
value = double(value(:));
if isscalar(value)
    value = repmat(value, 4, 1);
end
end
