function validateTireEnvelopeLookup( ...
        config, lookup, roadGripScale, roadMuLimit, camber)
%VALIDATETIREENVELOPELOOKUP Verify lookup compatibility with GGV inputs.

arguments
    config (1, 1) struct
    lookup (1, 1) struct
    roadGripScale (4, 1) double
    roadMuLimit (4, 1) double
    camber (4, 1) double
end

requiredFields = ["Version", "Method", "NormalLoadGrid", ...
    "NormalLoadUpper", "Directions", "Support", "FxMax", "FyMax", ...
    "RoadGripScale", "RoadMuLimit", "CamberAngle", "TireModel", ...
    "TireProfile", "KappaGrid", "AlphaGrid", "EnvelopePointCount", ...
    "InterpolationMethod"];
assert(all(isfield(lookup, requiredFields)), ...
    "FSAE:QuasiStatic:InvalidTireEnvelopeLookup", ...
    "Tire-envelope lookup is missing compatibility metadata.");
compatible = lookup.Version == 1 && ...
    string(lookup.InterpolationMethod) == "linear" && ...
    string(lookup.TireModel) == config.Tire.Model && ...
    lookup.EnvelopePointCount == config.Solver.EnvelopePointCount && ...
    isequaln(lookup.TireProfile, config.Tire.Profile) && ...
    isequaln(lookup.KappaGrid(:), config.Tire.KappaGrid(:)) && ...
    isequaln(lookup.AlphaGrid(:), config.Tire.AlphaGrid(:)) && ...
    isequaln(lookup.RoadGripScale(:), roadGripScale) && ...
    isequaln(lookup.RoadMuLimit(:), roadMuLimit) && ...
    isequaln(lookup.CamberAngle(:), camber);
assert(compatible, "FSAE:QuasiStatic:TireEnvelopeLookupMismatch", ...
    "The tire-envelope lookup does not match the current tire, road, or camber configuration.");
end
