function result = createRaceReplayTestResult()
%CREATERACEREPLAYTESTRESULT Small result with known signs, units and commands.
time = [0; 1; 3];
torque = [10, 20, -10, -20; 20, 30, -20, -30; 0, 0, 0, 0];
omega = [100, 200, 300, 400; 200, 300, 400, 500; 50, 60, 70, 80];
fx = repmat([300, -300, 0, 600], 3, 1);
fy = repmat([400, 400, -500, 0], 3, 1);
geometry = struct("Wheelbase", 2, "CGToFrontAxle", 1, ...
    "TrackFront", 1.5, "TrackRear", 1.5, "TireWidth", 0.2, ...
    "WheelLength", 0.4, "Source", "测试车辆几何");
track = struct("X", [-10; 0; 10], "Y", [0; 0; 0], ...
    "Heading", [0; 0; 0], "LeftHalfWidth", 2, "RightHalfWidth", 2, ...
    "Length", 20, "IsClosed", false);
driver = struct("Model", "adaptive_autocross", ...
    "MaximumAcceleration", 4, "MaximumDeceleration", 6, "TireSectionWidth", 0.2);
tire = struct("Model", "simple", "RoadGripScale", 1, ...
    "RoadMuLimit", 0.9, "ForceEpsilon", 20);
snapshot = struct("Version", "1.0", "Track", track, ...
    "Geometry", geometry, "Driver", driver, "Tire", tire);
result = struct("SchemaVersion", "1.0", "Time", time, ...
    "Distance", [0; 5; 15], "Config", struct("Driver", driver));
result.Meta = struct("Replay", snapshot, "Valid", true, ...
    "ScenarioID", "replay-test", "Event", "autocross", ...
    "MissingSignals", strings(0, 1), "NonFiniteSignals", strings(0, 1), ...
    "DimensionIssues", strings(0, 1));
result.Vehicle = struct("X", [0; 5; 15], "Y", [0; 0; 0], ...
    "Psi", [0; 0; 0], "Speed", [5; 5; 5], "Ax", [0; 0; 0], "Ay", [0; 0; 0]);
result.Wheel = struct("SteerAngle", zeros(3, 4), "NormalLoad", ones(3, 4) * 1000, ...
    "CamberAngle", zeros(3, 4), "SlipRatio", ones(3, 4) * 0.1, ...
    "SlipAngle", zeros(3, 4));
result.Tire = struct("FxWheel", fx, "FyWheel", fy, ...
    "MuUtilization", hypot(fx, fy) / sqrt(900^2 + 20^2));
result.Powertrain = struct("MotorTorqueActual", torque, "MotorSpeed", omega, ...
    "MotorRPM", omega * 60 / (2 * pi), "MotorMechanicalPower", torque .* omega);
result.Battery = struct("Power", [2000; 3000; 0]);
result.Driver = struct("SteeringWheelAngleRequest", [0; 0.1; 0.2], ...
    "LongitudinalAccelerationRequest", [4; -6; 0]);
result.Track = struct("LapIndex", ones(3, 1), "PathS", [0; 5; 15], ...
    "Progress", [0; 0.25; 0.75]);
result.Actuator = struct;
result.Controller = struct;
result.Sensor = struct;
result.Metrics = struct;
end
