function parameters = installVehicle10DOFSuspensionData(options)
%INSTALLVehicle10DOFSUSPENSIONDATA Install Vehicle10DOF 10DOF suspension runtime parameters.
%   The spring, geometry, load distribution, and motion-ratio values come
%   from the E41 suspension/steering parameter table. The nonlinear damper
%   map is digitized from the C12/R12 page of the Ohlins TTX25 MkII dyno PDF.

arguments
    options.DictionaryPath (1, 1) string = defaultDictionaryPath()
end

dictionary = Simulink.data.dictionary.open(options.DictionaryPath);
cleanup = onCleanup(@() close(dictionary));
designData = getSection(dictionary, "Design Data");
vehicleEntry = getEntry(designData, "Vehicle");
vehicle = getValue(vehicleEntry);

% The directly tabulated suspension line stiffness is authoritative for Vehicle10DOF.
% It exactly reproduces the tabulated spring roll stiffness at each axle;
% the spring-rate/motion-ratio combination in the source does not.
vehicle.WheelRateFront = fixedRecord(76.74e3, "N/m", ...
    "E41SuspensionSteeringParameterTable", "High", ...
    "Direct front suspension line stiffness; also reproduces 964.34 N*m/deg roll stiffness.");
vehicle.WheelRateRear = fixedRecord(60.64e3, "N/m", ...
    "E41SuspensionSteeringParameterTable", "High", ...
    "Direct rear suspension line stiffness; also reproduces 712.07 N*m/deg roll stiffness.");
vehicle.InertiaRoll = placeholderRecord(50.0, "kg*m^2", ...
    "TypicalValue", "Low", ...
    "Vehicle10DOF baseline estimate; replace with CAD or pendulum identification.");
vehicle.InertiaPitch = placeholderRecord(80.0, "kg*m^2", ...
    "TypicalValue", "Low", ...
    "Vehicle10DOF baseline estimate; replace with CAD or pendulum identification.");
setValue(vehicleEntry, vehicle);

distanceFront = vehicle.CGToFrontAxle.Value;
distanceRear = vehicle.Wheelbase.Value - distanceFront;
staticFront = vehicle.Mass.Value * 9.80665 * distanceRear / ...
    vehicle.Wheelbase.Value / 2;
staticRear = vehicle.Mass.Value * 9.80665 * distanceFront / ...
    vehicle.Wheelbase.Value / 2;

velocityMmPerSecond = [0; 15; 25; 50; 75; 100; 125; 150; ...
    175; 200; 225; 250];
compressionForce = [0; 16.3; 20.4; 38.8; 63.3; 87.8; 124.5; ...
    161.2; 198.0; 240.8; 283.7; 324.5];
reboundForce = [0; 20.4; 24.5; 53.1; 89.8; 128.6; 173.5; ...
    220.4; 275.5; 328.6; 382.7; 436.7];

springRollStiffness = [vehicle.SpringRollStiffnessFront.Value; ...
    vehicle.SpringRollStiffnessRear.Value] * 180 / pi;
totalRollStiffness = [vehicle.RollStiffnessFront.Value; ...
    vehicle.RollStiffnessRear.Value] * 180 / pi;

parameters = struct( ...
    "Mass", vehicle.Mass.Value, ...
    "Gravity", 9.80665, ...
    "InertiaRoll", vehicle.InertiaRoll.Value, ...
    "InertiaPitch", vehicle.InertiaPitch.Value, ...
    "CGHeight", vehicle.CGHeight.Value, ...
    "CGToFrontAxle", distanceFront, ...
    "Wheelbase", vehicle.Wheelbase.Value, ...
    "TrackFront", vehicle.TrackFront.Value, ...
    "TrackRear", vehicle.TrackRear.Value, ...
    "WheelRate", [vehicle.WheelRateFront.Value; ...
        vehicle.WheelRateFront.Value; vehicle.WheelRateRear.Value; ...
        vehicle.WheelRateRear.Value], ...
    "MotionRatio", [vehicle.SuspensionLeverageRatioFront.Value; ...
        vehicle.SuspensionLeverageRatioFront.Value; ...
        vehicle.SuspensionLeverageRatioRear.Value; ...
        vehicle.SuspensionLeverageRatioRear.Value], ...
    "StaticNormalLoad", [staticFront; staticFront; staticRear; staticRear], ...
    "DamperVelocityBreakpoints", velocityMmPerSecond * 1.0e-3, ...
    "DamperCompressionForce", compressionForce, ...
    "DamperReboundForce", reboundForce, ...
    "AdditionalRollStiffness", max(0, totalRollStiffness - springRollStiffness), ...
    "NormalLoadFloor", 0.0, ...
    "InitialState", zeros(6, 1), ...
    "DamperValveSpecification", "C12/R12", ...
    "DamperExternalSetting", "10-4.3-10-4.3", ...
    "DamperSource", "_TTX25 MkII Dyno N vs mmps.pdf, page 2", ...
    "DamperDigitizationUncertaintyN", 8.0, ...
    "DamperSettingConfirmed", false);

setDictionaryEntry(designData, "Vehicle10DOFSuspension", parameters);
setDictionaryEntry(designData, "Vehicle10DOFInitialState", struct( ...
    "VerticalPosition", 0.0, "RollAngle", 0.0, "PitchAngle", 0.0, ...
    "VerticalVelocity", 0.0, "RollRate", 0.0, "PitchRate", 0.0));
saveChanges(dictionary);
end

function record = fixedRecord(value, unit, source, confidence, notes)
record = parameterRecord(value, unit, source, confidence, false, notes);
end

function record = placeholderRecord(value, unit, source, confidence, notes)
record = parameterRecord(value, unit, source, confidence, true, notes);
end

function record = parameterRecord(value, unit, source, confidence, isPlaceholder, notes)
record = struct( ...
    "Value", value, ...
    "LowerBound", NaN, ...
    "UpperBound", NaN, ...
    "Unit", char(unit), ...
    "Source", char(source), ...
    "Confidence", char(confidence), ...
    "LastUpdated", "2026-08-02", ...
    "IsMeasured", false, ...
    "IsPlaceholder", logical(isPlaceholder), ...
    "Notes", char(notes));
end

function setDictionaryEntry(section, name, value)
try
    entry = getEntry(section, name);
    setValue(entry, value);
catch exception
    if contains(exception.identifier, "EntryNotFound") || ...
            contains(exception.message, "does not exist", IgnoreCase = true)
        addEntry(section, name, value);
    else
        rethrow(exception)
    end
end
end

function path = defaultDictionaryPath()
projectRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
path = fullfile(projectRoot, "data", "VehicleData.sldd");
end
